'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path'),crypto=require('crypto');
var audit=require('../audit/accumulationComparativeAuditV1');
var labels=[],existing=[];for(var i=1;i<=60;i++){var id='case'+String(i).padStart(3,'0'),label=i<=32?'CLEAR_A':i<=44?'BORDERLINE_A':'NO_A',features={};audit.FEATURES.forEach(function(k){features[k]=k==='preRangeContext'?'NEUTRAL':k==='eqDependentConfirmation'?false:i/10;});features.featureSourceEndIndex=i;features.featureSourceConfirmedAt=i*1000;labels.push({caseId:id,humanLabel:label,labelSource:i===1?'HUMAN_CONFIRMED_IN_CHAT':'CHATGPT_VISUAL_REVIEW',comment:''});existing.push({caseId:id,detectorLabel:'POSITIVE',humanLabel:i===1?'CLEAR_A':'UNREVIEWED',featureSnapshot:features,notes:[]});}
var proposal={schemaVersion:'ACCUMULATION_HUMAN_LABEL_COMPLETION_V1',exportedAt:'2026-08-28T00:00:00.000Z',labels:labels,reviewAuditLog:[],machinePositiveUnreviewed:[]};
var passed=0,failed=0;function test(n,f){try{f();passed++;console.log('PASS  '+n);}catch(e){failed++;console.log('FAIL  '+n+' -> '+e.stack);}}
test('60 approved labels loaded with exact counts',function(){assert.deepStrictEqual(audit.validateProposal(proposal,existing),{CLEAR_A:32,BORDERLINE_A:12,NO_A:16});});
test('all case001-060 unique and no unreviewed',function(){var g=audit.finalizeGroundTruth(proposal,existing);assert.strictEqual(g.length,60);assert.strictEqual(new Set(g.map(x=>x.caseId)).size,60);assert.strictEqual(g.filter(x=>x.humanLabel==='UNREVIEWED').length,0);});
test('labels immutable during comparison',function(){var g=audit.finalizeGroundTruth(proposal,existing),before=JSON.stringify(g.map(x=>[x.caseId,x.humanLabel]));audit.buildComparison(g);assert.strictEqual(JSON.stringify(g.map(x=>[x.caseId,x.humanLabel])),before);});
test('existing features only',function(){var g=audit.finalizeGroundTruth(proposal,existing),c=audit.buildComparison(g);Object.values(c.groupSummary).forEach(x=>assert.deepStrictEqual(Object.keys(x.features),audit.FEATURES));});
test('feature snapshots are formation-only',function(){var g=audit.finalizeGroundTruth(proposal,existing);g.forEach(x=>{assert.ok(x.featureSnapshot.featureSourceEndIndex<=existing.find(y=>y.caseId===x.caseId).featureSnapshot.featureSourceEndIndex);assert.ok(x.featureSnapshot.featureSourceConfirmedAt<=existing.find(y=>y.caseId===x.caseId).featureSnapshot.featureSourceConfirmedAt);});});
test('no parameter search, new score, or new gate in module',function(){var src=fs.readFileSync(path.join(__dirname,'..','audit','accumulationComparativeAuditV1.js'),'utf8');assert.ok(!/grid search|\bROC\b|\bAUC\b|logistic regression|random forest/i.test(src));assert.ok(!/RejectGate|V2Score|balanceQualityScore/.test(src));});
test('production sources remain unchanged',function(){var root=path.join(__dirname,'..'),files=['amd/accumulationDetector.js','config/thresholds.js','events/displacementDetector.js','live/liveEngine.js','notify/watchNotificationPresentationV1.js'];function h(){return files.map(f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex'));}var before=h();audit.buildComparison(audit.finalizeGroundTruth(proposal,existing));assert.deepStrictEqual(h(),before);});
test('deterministic finalized ground truth and summaries',function(){var a=audit.finalizeGroundTruth(proposal,existing),b=audit.finalizeGroundTruth(proposal,existing);assert.deepStrictEqual(a,b);assert.deepStrictEqual(audit.buildComparison(a),audit.buildComparison(b));});
console.log('\nAccumulation Comparative Audit V1: '+passed+' passed, '+failed+' failed');if(failed)process.exit(1);
