'use strict';
var test=require('node:test'),assert=require('node:assert'),clientModule=require('../execution/binanceExecutionClientV1');
function client(){return clientModule.createClient({apiKey:'key',secret:'secret',liveTradingEnabled:true,transport:{request:async function(){var e=new Error('Request failed with status code 400');e.code='ERR_BAD_REQUEST';e.response={status:400,data:{code:-1102,msg:'Mandatory parameter was not sent'}};throw e;}}});}
function verify(e,operation,method){assert.equal(e.executionOperation,operation);assert.equal(e.executionEndpoint,'/fapi/v1/algoOrder');assert.equal(e.executionMethod,method);assert.equal(e.httpStatus,400);assert.equal(e.binanceCode,-1102);assert.equal(e.binanceMessage,'Mandatory parameter was not sent');assert.equal('signature' in e.sanitizedRequest,false);return true;}
var plan={symbol:'PROMUSDT',direction:'LONG',tradeId:'T',stopPrice:5,targetPrice:6};
test('SL POST 400 preserves operation endpoint and Binance body',async()=>{await assert.rejects(client().submitProtectionSmokeAlgo(plan,'SL','IMC_SMOKE2_PROM_A_SL'),e=>verify(e,'CREATE_SL_ALGO','POST'));});
test('TP POST 400 preserves operation endpoint and Binance body',async()=>{await assert.rejects(client().submitProtectionSmokeAlgo(plan,'TP','IMC_SMOKE2_PROM_A_TP'),e=>verify(e,'CREATE_TP_ALGO','POST'));});
test('Algo GET 400 preserves operation and sends algoId only',async()=>{await assert.rejects(client().queryAlgoOrder('PROMUSDT',123,'IMC_SMOKE2_PROM_A_SL'),e=>{verify(e,'QUERY_ALGO_ORDER','GET');assert.deepEqual(Object.keys(e.sanitizedRequest).sort(),['algoId','recvWindow','timestamp']);return true;});});
test('Algo GET by client id uses clientAlgoId not legacy fields',async()=>{await assert.rejects(client().queryAlgoOrder('PROMUSDT',null,'IMC_SMOKE2_PROM_A_SL'),e=>{verify(e,'QUERY_ALGO_ORDER','GET');assert.equal(e.sanitizedRequest.clientAlgoId,'IMC_SMOKE2_PROM_A_SL');assert.equal(e.sanitizedRequest.clientOrderId,undefined);assert.equal(e.sanitizedRequest.orderId,undefined);return true;});});
test('Algo DELETE 400 preserves operation endpoint and Binance body',async()=>{await assert.rejects(client().cancelProtectionSmokeAlgo('PROMUSDT','IMC_SMOKE2_PROM_A_SL'),e=>verify(e,'CANCEL_ALGO_ORDER','DELETE'));});
