'use strict';
var test=require('node:test'),assert=require('node:assert'),mod=require('../scripts/execution-protection-smoke');
function order(overrides){return Object.assign({symbol:'PROMUSDT',algoId:7,clientAlgoId:'IMC_SMOKE2_PROM_A_SL',algoStatus:'NEW',orderType:'STOP_MARKET',workingType:'MARK_PRICE',closePosition:true,triggerPrice:'5.586'},overrides||{});}
var expected={symbol:'PROMUSDT',algoId:7,clientAlgoId:'IMC_SMOKE2_PROM_A_SL',orderType:'STOP_MARKET',triggerPrice:5.586};
test('openAlgoOrders is primary verification',async()=>{var queries=0,r=await mod.verifyProtectionV2({getOpenAlgoOrders:async()=>[order()],queryAlgoOrder:async()=>{queries++;}},expected);assert.equal(r.ok,true);assert.equal(r.source,'OPEN_ALGO_ORDERS');assert.equal(queries,0);});
test('primary matches by clientAlgoId',async()=>{var r=await mod.verifyProtectionV2({getOpenAlgoOrders:async()=>[order({algoId:8})]},expected);assert.equal(r.ok,true);});
test('requires active algoStatus',async()=>{var r=await mod.verifyProtectionV2({getOpenAlgoOrders:async()=>[order({algoStatus:'CANCELED'})],queryAlgoOrder:async()=>order({algoStatus:'CANCELED'})},expected);assert.equal(r.ok,false);});
test('requires exact V2 fields',async()=>{for(const bad of [{symbol:'BTCUSDT'},{orderType:'TAKE_PROFIT_MARKET'},{workingType:'CONTRACT_PRICE'},{closePosition:false},{triggerPrice:'5.5'}]){var r=await mod.verifyProtectionV2({getOpenAlgoOrders:async()=>[order(bad)],queryAlgoOrder:async()=>order(bad)},expected);assert.equal(r.ok,false);}});
test('single-order GET is diagnostic fallback only',async()=>{var q=0,r=await mod.verifyProtectionV2({getOpenAlgoOrders:async()=>[],queryAlgoOrder:async()=>{q++;return order();}},expected);assert.equal(r.ok,true);assert.equal(r.source,'QUERY_ALGO_ORDER');assert.equal(q,1);});
test('ALGO_UPDATE is secondary verification before single-order GET',async()=>{var q=0,event={e:'ALGO_UPDATE',o:{caid:expected.clientAlgoId,aid:expected.algoId,X:'NEW',o:'STOP_MARKET',s:'PROMUSDT',wt:'MARK_PRICE',cp:true,tp:'5.586'}},r=await mod.verifyProtectionV2({getOpenAlgoOrders:async()=>[],queryAlgoOrder:async()=>{q++;}},Object.assign({},expected,{wsEvents:[event]}));assert.equal(r.ok,true);assert.equal(r.source,'USER_DATA_STREAM');assert.equal(r.wsSeen,true);assert.equal(q,0);});
test('primary REST error still permits ALGO_UPDATE secondary verification',async()=>{var event={e:'ALGO_UPDATE',o:{caid:expected.clientAlgoId,aid:expected.algoId,X:'NEW',o:'STOP_MARKET',s:'PROMUSDT',wt:'MARK_PRICE',cp:true,tp:'5.586'}},r=await mod.verifyProtectionV2({getOpenAlgoOrders:async()=>{throw new Error('primary unavailable');}},Object.assign({},expected,{wsEvents:[event]}));assert.equal(r.ok,true);assert.equal(r.source,'USER_DATA_STREAM');assert.equal(r.primaryError.message,'primary unavailable');});
test('GET -2013 after POST is visibility state',async()=>{var e=new Error('not found');e.binanceCode=-2013;var r=await mod.verifyProtectionV2({getOpenAlgoOrders:async()=>[],queryAlgoOrder:async()=>{throw e;}},expected);assert.equal(r.ok,false);assert.equal(r.pendingVisibility,true);assert.equal(r.reason,'POST_SUCCEEDED_QUERY_MINUS_2013');});
test('successful POST followed by GET -2013 never duplicates POST',async()=>{var posts=0,e=new Error('not found');e.binanceCode=-2013;e.executionOperation='QUERY_ALGO_ORDER';e.executionEndpoint='/fapi/v1/algoOrder';e.executionMethod='GET';e.binanceMessage='Order does not exist.';await assert.rejects(mod.placeProtectionOnce({submitProtectionSmokeAlgo:async()=>{posts++;return order();},getOpenAlgoOrders:async()=>[],queryAlgoOrder:async()=>{throw e;}},{symbol:'PROMUSDT',stopPrice:5.586,targetPrice:5.814},'SL',expected.clientAlgoId,[]),x=>{assert.equal(x.code,'POST_SUCCEEDED_QUERY_MINUS_2013');assert.equal(x.executionOperation,'QUERY_ALGO_ORDER');return true;});assert.equal(posts,1);});
test('TP contract validates TAKE_PROFIT_MARKET',async()=>{var x=order({clientAlgoId:'IMC_SMOKE2_PROM_A_TP',orderType:'TAKE_PROFIT_MARKET',triggerPrice:'5.814'}),r=await mod.verifyProtectionV2({getOpenAlgoOrders:async()=>[x]},Object.assign({},expected,{clientAlgoId:x.clientAlgoId,orderType:'TAKE_PROFIT_MARKET',triggerPrice:5.814}));assert.equal(r.ok,true);});

function cleanupTarget(id,clientId){return{algoId:id,clientAlgoId:clientId};}
function cleanupOrder(target){return{symbol:'PROMUSDT',algoId:target.algoId,clientAlgoId:target.clientAlgoId,algoStatus:'NEW'};}
test('cleanup A: flat position plus absent SL/TP sends zero cancels',async()=>{var counts={algoCancel:0},deletes=0,targets=[cleanupTarget(1,'IMC_SMOKE2_PROM_A_SL'),cleanupTarget(2,'IMC_SMOKE2_PROM_A_TP')];var r=await mod.cleanupProtection({client:{getOpenAlgoOrders:async()=>[],cancelProtectionSmokeAlgo:async()=>{deletes++;}},symbol:'PROMUSDT',targets,counts,positionQty:0,cancelAttemptedAlgoIds:new Set()});assert.equal(r.ok,true);assert.equal(counts.algoCancel,0);assert.equal(deletes,0);assert.deepEqual(r.results.map(x=>x.status),['ALREADY_NOT_OPEN','ALREADY_NOT_OPEN']);});
test('cleanup B: active SL and TP send exactly two cancels and finish absent',async()=>{var counts={algoCancel:0},targets=[cleanupTarget(1,'IMC_SMOKE2_PROM_A_SL'),cleanupTarget(2,'IMC_SMOKE2_PROM_A_TP')],open=targets.map(cleanupOrder),deletes=0;await mod.cleanupProtection({client:{getOpenAlgoOrders:async()=>open,cancelProtectionSmokeAlgo:async(s,c)=>{deletes++;open=open.filter(x=>x.clientAlgoId!==c);}},symbol:'PROMUSDT',targets,counts,positionQty:0,cancelAttemptedAlgoIds:new Set()});assert.equal(deletes,2);assert.equal(counts.algoCancel,2);assert.equal(open.length,0);});
test('cleanup C: DELETE -2011 followed by absence is idempotent success',async()=>{var counts={algoCancel:0},target=cleanupTarget(1,'IMC_SMOKE2_PROM_A_SL'),open=[cleanupOrder(target)],error=Object.assign(new Error('Unknown order sent.'),{binanceCode:-2011});var r=await mod.cleanupProtection({client:{getOpenAlgoOrders:async()=>open,cancelProtectionSmokeAlgo:async()=>{open=[];throw error;}},symbol:'PROMUSDT',targets:[target],counts,positionQty:0,cancelAttemptedAlgoIds:new Set()});assert.equal(r.ok,true);assert.equal(counts.algoCancel,1);assert.equal(r.results[0].status,'CANCEL_MINUS_2011_BUT_NOT_OPEN');});
test('cleanup D: DELETE -2011 while target remains open is critical inconsistent failure',async()=>{var counts={algoCancel:0},target=cleanupTarget(1,'IMC_SMOKE2_PROM_A_SL'),open=[cleanupOrder(target)],error=Object.assign(new Error('Unknown order sent.'),{binanceCode:-2011});await assert.rejects(mod.cleanupProtection({client:{getOpenAlgoOrders:async()=>open,cancelProtectionSmokeAlgo:async()=>{throw error;}},symbol:'PROMUSDT',targets:[target],counts,positionQty:0,cancelAttemptedAlgoIds:new Set()}),x=>x.code==='CLEANUP_INCONSISTENT'&&x.critical===true);assert.equal(counts.algoCancel,1);});
test('cleanup E: second invocation is absent and adds zero mutations',async()=>{var counts={algoCancel:0},attempted=new Set(),targets=[cleanupTarget(1,'IMC_SMOKE2_PROM_A_SL'),cleanupTarget(2,'IMC_SMOKE2_PROM_A_TP')],open=targets.map(cleanupOrder),deletes=0,client={getOpenAlgoOrders:async()=>open,cancelProtectionSmokeAlgo:async(s,c)=>{deletes++;open=open.filter(x=>x.clientAlgoId!==c);}};await mod.cleanupProtection({client,symbol:'PROMUSDT',targets,counts,positionQty:0,cancelAttemptedAlgoIds:attempted});var before=counts.algoCancel;var second=await mod.cleanupProtection({client,symbol:'PROMUSDT',targets,counts,positionQty:0,cancelAttemptedAlgoIds:attempted});assert.equal(counts.algoCancel,before);assert.equal(deletes,2);assert.deepEqual(second.results.map(x=>x.status),['ALREADY_NOT_OPEN','ALREADY_NOT_OPEN']);});
test('cleanup F: catch or finally style second call cannot duplicate cancel',async()=>{var counts={algoCancel:0},attempted=new Set(),target=cleanupTarget(1,'IMC_SMOKE2_PROM_A_SL'),open=[cleanupOrder(target)],deletes=0,error=Object.assign(new Error('Unknown order sent.'),{binanceCode:-2011}),client={getOpenAlgoOrders:async()=>open,cancelProtectionSmokeAlgo:async()=>{deletes++;throw error;}};for(var i=0;i<2;i++)await assert.rejects(mod.cleanupProtection({client,symbol:'PROMUSDT',targets:[target],counts,positionQty:0,cancelAttemptedAlgoIds:attempted}),x=>x.code==='CLEANUP_INCONSISTENT');assert.equal(deletes,1);assert.equal(counts.algoCancel,1);});
test('cleanup G: total algo cancel mutations have a hard cap of two',async()=>{var counts={algoCancel:0},targets=[cleanupTarget(1,'IMC_SMOKE2_A_SL'),cleanupTarget(2,'IMC_SMOKE2_A_TP'),cleanupTarget(3,'IMC_SMOKE2_A_X')],open=targets.map(cleanupOrder),deletes=0;await assert.rejects(mod.cleanupProtection({client:{getOpenAlgoOrders:async()=>open,cancelProtectionSmokeAlgo:async(s,c)=>{deletes++;open=open.filter(x=>x.clientAlgoId!==c);}},symbol:'PROMUSDT',targets,counts,positionQty:0,cancelAttemptedAlgoIds:new Set()}),x=>x.code==='ALGO_CANCEL_MUTATION_LIMIT_EXCEEDED');assert.equal(deletes,2);assert.equal(counts.algoCancel,2);});
test('cleanup refuses to remove protection while position is nonzero',async()=>{var deletes=0;await assert.rejects(mod.cleanupProtection({client:{getOpenAlgoOrders:async()=>[cleanupOrder(cleanupTarget(1,'IMC_SMOKE2_PROM_A_SL'))],cancelProtectionSmokeAlgo:async()=>{deletes++;}},symbol:'PROMUSDT',targets:[cleanupTarget(1,'IMC_SMOKE2_PROM_A_SL')],counts:{algoCancel:0},positionQty:1,cancelAttemptedAlgoIds:new Set()}),x=>x.code==='POSITION_NOT_FLAT_FOR_PROTECTION_CLEANUP'&&x.critical===true);assert.equal(deletes,0);});
