'use strict';

var test=require('node:test');var assert=require('node:assert/strict');
var flag=require('../config/sweepContextV1');var evidence=require('../stats/watchLiquidityEvidenceV1');
var prod=require('../stats/sweepContextV1');var shadow=require('../audit/liquiditySweepContextConsumptionV1');
var projectorModule=require('../audit/swingContextProjectorV1');
var runtime=require('../stats/runtimeSwingContextV1');
var liveEngine=require('../live/liveEngine');

function swing(id,side){return{canonicalSwingId:id,side:side,price:side==='HIGH'?110:90,occurredAt:10,confirmedAt:20,timeframeMembership:{'5m':{member:true,htfSwingId:id,occurredAt:10,confirmedAt:20},'15m':{member:true,htfSwingId:'15:'+id,occurredAt:0,confirmedAt:40},'1h':{member:true,htfSwingId:'1h:'+id,occurredAt:0,confirmedAt:60},'4h':{member:true,htfSwingId:'4h:'+id,occurredAt:0,confirmedAt:80}}};}
function projector(){var ss=[swing('H','HIGH'),swing('L','LOW'),swing('H2','HIGH')],ts=[];ss.forEach(function(s){ts.push({sourceSwingId:s.canonicalSwingId,role:'LOCAL_SWING',status:'CANDIDATE',confirmedAt:20,sequence:0});});ts.push({sourceSwingId:'H',role:'ACTIVE_PROTECTED',status:'ACTIVE_PROTECTED',confirmedAt:30,sequence:1},{sourceSwingId:'H',role:'BROKEN',status:'BROKEN',confirmedAt:90,sequence:2});return projectorModule.createSwingContextProjectorV1({swings:ss,structuralTransitions:ts});}
function cand(id,type,t){return{id:'SWEEP:'+id+':'+t,sourceId:id,sourceType:type,sourceTimeframe:'5m',sourcePrice:100,side:/HIGH|EQH|PDH/.test(type)?'BSL':'SSL',confirmedAt:t,candleIndex:t,relation:'BEFORE_LEG',barsBeforeLegStart:1};}
function registry(objects){var by={};objects.forEach(function(o){by[o.id]=o;});return{getById:function(id){return by[id]||null;}};}
function source(c,extra){return Object.assign({id:c.sourceId,type:c.sourceType,side:c.side,price:c.sourcePrice,confirmedAt:20,status:'SWEPT',sweptAt:c.confirmedAt,metadata:{}},extra||{});}
function watch(cs,primary){return{id:'W',direction:'BULLISH',createdAt:100,updatedAt:100,dailyBias:null,liquidityTaken:{primary:primary||cs[0],allCandidates:cs}};}
function opts(cs,p,on,objects){return{enabled:true,evaluationTime:100,candles:[],registry:registry(objects||cs.map(function(c){return source(c);})),sweepContextV1Enabled:on,projectSwingContextV1:p.projectSwingContextV1};}
function context(c,p,on,objects){return evidence.build(watch([c]),opts([c],p,on,objects)).allCandidates[0];}
function hash(v){return prod.hash(v);}

test('1 flag default false',function(){assert.equal(flag.DEFAULT_ENABLED,false);assert.equal(flag.isEnabled({}),false);});
test('2 flag OFF no sweepContextV1',function(){var p=projector(),x=context(cand('H','SWING_HIGH',50),p,false);assert.equal(x.sweepContextV1,undefined);});
test('3 flag OFF old behavior equivalent',function(){var p=projector(),c=cand('H','SWING_HIGH',50),a=evidence.build(watch([c]),opts([c],p,false)),b=evidence.build(watch([c]),Object.assign({},opts([c],p,false),{env:{}}));assert.deepEqual(a,b);});
test('4 flag ON adds context only',function(){var p=projector(),c=cand('H','SWING_HIGH',50),off=evidence.build(watch([c]),opts([c],p,false)),on=evidence.build(watch([c]),opts([c],p,true)),ctx=on.allCandidates[0].sweepContextV1;delete on.allCandidates[0].sweepContextV1;delete on.candidates[0].sweepContextV1;assert.ok(ctx);assert.deepEqual(on,off);});
test('5 SWING_HIGH context',function(){var x=context(cand('H','SWING_HIGH',50),projector(),true);assert.equal(x.sweepContextV1.canonicalSwingId,'H');});
test('6 SWING_LOW context',function(){var x=context(cand('L','SWING_LOW',50),projector(),true);assert.equal(x.sweepContextV1.swingContext.side,'LOW');});
test('7 Structural Role as-of Sweep',function(){assert.equal(context(cand('H','SWING_HIGH',50),projector(),true).sweepContextV1.swingContext.structural.currentRole,'ACTIVE_PROTECTED');});
test('8 future BROKEN hidden',function(){assert.notEqual(context(cand('H','SWING_HIGH',89),projector(),true).sweepContextV1.swingContext.structural.currentRole,'BROKEN');});
test('9 15m membership as-of Sweep',function(){assert.equal(context(cand('H','SWING_HIGH',40),projector(),true).sweepContextV1.swingContext.timeframeMembership['15m'].confirmed,true);});
test('9a future 15m membership hidden',function(){assert.equal(context(cand('H','SWING_HIGH',39),projector(),true).sweepContextV1.swingContext.timeframeMembership['15m'].confirmed,false);});
test('10 future 1H membership hidden',function(){assert.equal(context(cand('H','SWING_HIGH',59),projector(),true).sweepContextV1.swingContext.timeframeMembership['1h'].confirmed,false);});
test('10a 1H membership available at confirmation',function(){assert.equal(context(cand('H','SWING_HIGH',60),projector(),true).sweepContextV1.swingContext.timeframeMembership['1h'].confirmed,true);});
test('11 future 4H membership hidden',function(){assert.equal(context(cand('H','SWING_HIGH',79),projector(),true).sweepContextV1.swingContext.timeframeMembership['4h'].confirmed,false);});
test('11a 4H membership available at confirmation',function(){assert.equal(context(cand('H','SWING_HIGH',80),projector(),true).sweepContextV1.swingContext.timeframeMembership['4h'].confirmed,true);});
test('12 EQH point-in-time partner provenance preserved',function(){var p=projector(),c=cand('EQH1','EQH',80);c.eqPartnerProvenance={currentPivot:{id:'P',price:100},historicalPartners:[{id:'ZH'},{id:'ZH2'}]};var x=context(c,p,true);assert.equal(x.sweepContextV1.contextApplicability,'EQ_POINT_IN_TIME_CROSS_SOURCE');assert.deepEqual(x.sweepContextV1.provenance.historicalPartnerIds,['ZH','ZH2']);});
test('13 EQL point-in-time partner provenance preserved',function(){var p=projector(),c=cand('EQL1','EQL',80);c.eqPartnerProvenance={currentPivot:{id:'P',price:100},historicalPartners:[{id:'ZL'}]};var x=context(c,p,true);assert.deepEqual(x.sweepContextV1.provenance.historicalPartnerIds,['ZL']);});
test('14 EQ has no cluster member context or primary partner',function(){var p=projector(),c=cand('EQH1','EQH',80);c.eqPartnerProvenance={currentPivot:{id:'P',price:100},historicalPartners:[{id:'ZH'},{id:'ZH2'}]};var x=context(c,p,true).sweepContextV1;assert.equal(x.canonicalSwingId,null);assert.deepEqual(x.memberSwingContexts,[]);assert.equal(x.provenance.clusterIdentity,false);});
test('15 PDH remains NON_SWING_LIQUIDITY',function(){var x=context(cand('PDH1','PDH',50),projector(),true);assert.equal(x.sweepContextV1.contextApplicability,'NON_SWING_LIQUIDITY');assert.equal(x.sweepContextV1.swingContext,null);});
test('15a PDL remains NON_SWING_LIQUIDITY',function(){var x=context(cand('PDL1','PDL',50),projector(),true);assert.equal(x.sweepContextV1.contextApplicability,'NON_SWING_LIQUIDITY');assert.equal(x.sweepContextV1.swingContext,null);});
test('15b SESSION_HIGH remains NON_SWING_LIQUIDITY',function(){var x=context(cand('SH','SESSION_HIGH',50),projector(),true);assert.equal(x.sweepContextV1.contextApplicability,'NON_SWING_LIQUIDITY');assert.equal(x.sweepContextV1.canonicalSwingId,null);});
test('15c SESSION_LOW remains NON_SWING_LIQUIDITY',function(){var x=context(cand('SL','SESSION_LOW',50),projector(),true);assert.equal(x.sweepContextV1.contextApplicability,'NON_SWING_LIQUIDITY');assert.equal(x.sweepContextV1.canonicalSwingId,null);});
test('16 NEW_YORK_HIGH keeps native identity',function(){var x=context(cand('NYH','NEW_YORK_HIGH',50),projector(),true);assert.equal(x.sweepContextV1.liquidity.sourceId,'NYH');assert.equal(x.sweepContextV1.canonicalSwingId,null);});
test('17 unknown provenance is UNRESOLVED',function(){assert.equal(context(cand('X','UNKNOWN_TYPE',50),projector(),true).sweepContextV1.contextApplicability,'UNRESOLVED');});
test('18 unresolved does not drop candidate',function(){var p=projector(),cs=[cand('X','UNKNOWN_TYPE',50),cand('H','SWING_HIGH',50)],x=evidence.build(watch(cs),opts(cs,p,true));assert.equal(x.allCandidates.length,2);});
test('19 allCandidates count preserved',function(){var p=projector(),cs=[cand('L','SWING_LOW',40),cand('H','SWING_HIGH',50)];assert.equal(evidence.build(watch(cs),opts(cs,p,true)).allCandidates.length,cs.length);});
test('20 candidate ordering preserves existing serialization rule',function(){var p=projector(),a=cand('H','SWING_HIGH',50),b=cand('L','SWING_LOW',40),x=evidence.build(watch([a,b],a),opts([a,b],p,true));assert.deepEqual(x.allCandidates.map(function(c){return c.sourceId;}),['L','H']);});
test('21 current primary preserved',function(){var p=projector(),a=cand('H','SWING_HIGH',50),b=cand('L','SWING_LOW',40),x=evidence.build(watch([a,b],a),opts([a,b],p,true));assert.equal(x.currentPrimary.sourceId,'H');});
test('22 primary heuristic unchanged',function(){var p=projector(),x=context(cand('H','SWING_HIGH',50),p,true);assert.equal(evidence.PRIMARY_SELECTION_SEMANTIC,'CURRENT_PRODUCTION_RECENCY_HEURISTIC');assert.ok(x.sweepContextV1);});
test('23 WATCH count unchanged',function(){var p=projector(),ws=[watch([cand('H','SWING_HIGH',50)]),watch([cand('L','SWING_LOW',50)])];assert.equal(ws.map(function(w){return evidence.build(w,opts(w.liquidityTaken.allCandidates,p,true));}).length,2);});
test('24 WATCH timing unchanged',function(){var p=projector(),w=watch([cand('H','SWING_HIGH',50)]),x=evidence.build(w,opts(w.liquidityTaken.allCandidates,p,true));assert.equal(w.createdAt,100);assert.equal(x.evaluationTime,100);});
test('25 WATCH direction unchanged',function(){var p=projector(),w=watch([cand('H','SWING_HIGH',50)]);evidence.build(w,opts(w.liquidityTaken.allCandidates,p,true));assert.equal(w.direction,'BULLISH');});
test('26 Sweep count and timing unchanged',function(){var p=projector(),cs=[cand('H','SWING_HIGH',50),cand('L','SWING_LOW',60)],x=evidence.build(watch(cs),opts(cs,p,true));assert.deepEqual(x.allCandidates.map(function(c){return[c.sweepEventId,c.confirmedAt];}),cs.map(function(c){return[c.id,c.confirmedAt];}));});
test('27 shadow and production context equal',function(){var p=projector(),c=cand('H','SWING_HIGH',50),o={projectSwingContextV1:p.projectSwingContextV1,registry:registry([source(c)])};assert.deepEqual(prod.buildSweepContextV1(c,o),shadow.buildSweepContextV1(c,o));});
test('28 past context immutable',function(){var p=projector(),c=cand('H','SWING_HIGH',50),x=prod.buildSweepContextV1(c,{projectSwingContextV1:p.projectSwingContextV1}),h=hash(x);prod.buildSweepContextV1(cand('H','SWING_HIGH',100),{projectSwingContextV1:p.projectSwingContextV1});assert.equal(hash(x),h);});
test('29 deterministic serialization',function(){var p=projector(),c=cand('H','SWING_HIGH',50),o={projectSwingContextV1:p.projectSwingContextV1};assert.equal(hash(prod.buildSweepContextV1(c,o)),hash(prod.buildSweepContextV1(c,o)));});
test('30 no blocked score or ranking fields',function(){var p=projector(),text=JSON.stringify(context(cand('H','SWING_HIGH',50),p,true).sweepContextV1);assert.equal(/importanceScore|rankingScore|qualityScore|causalPrimary|recommendedPrimary|tradeDirectionOverride/.test(text),false);});
test('31 runtime 15m mapping reuses exact 2/2 extrema',function(){var rows=[],step=300000,groupHigh=[10,11,15,11,10];for(var g=0;g<5;g++)for(var i=0;i<3;i++){var n=g*3+i,h=groupHigh[g]-(i===1?0:0.5);rows.push({openTime:n*step,closeTime:(n+1)*step-1,open:h-1,high:h,low:h-2,close:h-1,closed:true});}var by=runtime.buildMembership('X',rows,{'1h':[],'4h':[]}),id='X:5m:SWING_HIGH:'+(7*step);assert.equal(by[id].timeframeMembership['15m'].member,true);assert.equal(by[id].timeframeMembership['15m'].mappingProvenance.nearestMatch,false);});
test('32 runtime structural history is projected as-of',function(){var c={id:'X:5m:SWING_HIGH:1',type:'SWING_HIGH',side:'BSL',price:10,sourceOpenTime:1,confirmedAt:20},reg=registry([c]),st={swingBySourceId:{}};st.swingBySourceId[c.id]={side:'HIGH',price:10,occurredAt:1,confirmedAt:20,history:[{role:'LOCAL_SWING',status:'CANDIDATE',confirmedAt:20},{role:'BROKEN',status:'BROKEN',confirmedAt:90}]};var r=runtime.createRuntimeSwingContextV1({symbol:'X',initialCandles5m:[],structureCandles:{},getCandles5m:function(){return[];},getRegistry:function(){return reg;},getStructuralState:function(){return st;}});assert.equal(r.projectSwingContextV1({canonicalSwingId:c.id,evaluationTime:50}).structural.currentRole,'LOCAL_SWING');});
test('33 runtime lookup fails safe without authoritative Swing source',function(){var r=runtime.createRuntimeSwingContextV1({symbol:'X',initialCandles5m:[],structureCandles:{},getRegistry:function(){return registry([]);},getStructuralState:function(){return{}}});assert.equal(r.projectSwingContextV1({canonicalSwingId:'missing',evaluationTime:50}),null);});
test('34 live enrichment helper forwards SweepContext flag without changing WATCH envelope',function(){var p=projector(),c=cand('H','SWING_HIGH',50),w=watch([c]),legacy=JSON.parse(JSON.stringify(w));liveEngine.attachWatchLiquidityEvidenceV1(w,Object.assign({},opts([c],p,true),{errors:[]}));assert.ok(w.liquidityEvidenceV1.allCandidates[0].sweepContextV1);delete w.liquidityEvidenceV1;assert.deepEqual(w,legacy);});
