'use strict';

var test=require('node:test');
var assert=require('node:assert/strict');
var producer=require('../liquidity/productionEqualLiquidityV1');
var replayState=require('../replay/replayState');
var eventRegistry=require('../events/eventRegistry');
var displacementWatch=require('../stats/displacementWatch');
var liveMessages=require('../scripts/live');

var BAR=300000;
function point(id,side,index,price){return{id:id,pointSide:side,price:price,occurredAt:index*BAR,confirmedAt:(index+2)*BAR-1,occurredBarIndex:index,status:'ACTIVE',violatedAt:null};}
function pivot(id,side,index,price){return{id:id,symbol:'X',timeframe:'5m',type:side==='HIGH'?'SWING_HIGH':'SWING_LOW',side:side==='HIGH'?'BSL':'SSL',price:price,sourceOpenTime:index*BAR,sourceCloseTime:(index+1)*BAR-1,confirmedAt:(index+3)*BAR-1,metadata:{index:index,right:2}};}
function makeEq(side,partners){var s=producer.createState({symbol:'X',timeframe:'5m'});s.fiveMinuteAtrValue=10;s.zigzag.confirmedPoints=partners;s.zigzag.recentSurvivalPoints=partners;return{producerState:s,event:producer.evaluatePivot(s,pivot('P:'+side,side,10,100))};}
function candle(index,high,low,close,open){return{openTime:index*BAR,closeTime:(index+1)*BAR-1,open:open===undefined?100:open,high:high,low:low,close:close,closed:true};}
function runtime(eq){var s=replayState.createReplayState({symbol:'X',timeframe:'5m'});s.eventRegistry=eventRegistry.createEventRegistry();assert.equal(s.registry.add(eq),true);return s;}
function eqh(){return makeEq('HIGH',[point('ZH','HIGH',2,100)]).event;}
function eql(){return makeEq('LOW',[point('ZL','LOW',2,100)]).event;}

test('CASE A EQH registers as BSL and strict future high emits one Taken',function(){var eq=eqh(),s=runtime(eq),c=candle(13,101,98,99),out=replayState.incrementalEvents(s,c,13,c.closeTime,[]);assert.equal(eq.type,'EQH');assert.equal(eq.side,'BSL');assert.equal(s.registry.getById(eq.id),eq);assert.equal(out.taken.length,1);assert.equal(out.taken[0].liquidityId,eq.id);assert.equal(out.taken[0].source.liquidityType,'EQH');assert.equal(s.eventRegistry.getByType('X','LIQUIDITY_TAKEN').length,1);});
test('CASE B EQL registers as SSL and strict future low emits one Taken',function(){var eq=eql(),s=runtime(eq),c=candle(13,102,99,101),out=replayState.incrementalEvents(s,c,13,c.closeTime,[]);assert.equal(eq.type,'EQL');assert.equal(eq.side,'SSL');assert.equal(out.taken.length,1);assert.equal(out.taken[0].source.liquidityType,'EQL');assert.equal(out.taken[0].source.eqPartnerProvenance.currentPivot.id,'P:LOW');});
test('EQH equality touch is not Taken; next strict trade-through is first Taken',function(){var s=runtime(eqh()),touch=candle(13,100,98,99),strict=candle(14,101,98,99);assert.equal(replayState.incrementalEvents(s,touch,13,touch.closeTime,[]).taken.length,0);assert.equal(replayState.incrementalEvents(s,strict,14,strict.closeTime,[]).taken.length,1);assert.equal(s.eventRegistry.getByType('X','LIQUIDITY_TAKEN').length,1);});
test('EQL equality touch is not Taken; next strict trade-through is first Taken',function(){var s=runtime(eql()),touch=candle(13,102,100,101),strict=candle(14,102,99,101);assert.equal(replayState.incrementalEvents(s,touch,13,touch.closeTime,[]).taken.length,0);assert.equal(replayState.incrementalEvents(s,strict,14,strict.closeTime,[]).taken.length,1);assert.equal(s.eventRegistry.getByType('X','LIQUIDITY_TAKEN').length,1);});
test('multi-partner current pivot creates one Registry item and one Taken',function(){var made=makeEq('HIGH',[point('ZA','HIGH',1,99),point('ZB','HIGH',2,101)]),eq=made.event,s=runtime(eq),c=candle(13,102,98,99);assert.equal(eq.metadata.partnerCount,2);assert.equal(s.registry.getByType('X','EQH').length,1);assert.equal(replayState.incrementalEvents(s,c,13,c.closeTime,[]).taken.length,1);assert.equal(s.eventRegistry.getByType('X','LIQUIDITY_TAKEN').length,1);});
test('same current pivot dedupes EQ and Registry identity',function(){var made=makeEq('HIGH',[point('ZH','HIGH',2,100)]),first=made.event;assert.equal(producer.evaluatePivot(made.producerState,pivot('P:HIGH','HIGH',10,100)),null);var s=runtime(first);assert.equal(s.registry.add(first),false);assert.equal(s.registry.getByType('X','EQH').length,1);});
test('Taken ledger prevents a second Taken for the same EQ liquidity',function(){var s=runtime(eqh()),a=candle(13,101,98,99),b=candle(14,102,98,99);assert.equal(replayState.incrementalEvents(s,a,13,a.closeTime,[]).taken.length,1);assert.equal(replayState.incrementalEvents(s,b,14,b.closeTime,[]).taken.length,0);assert.equal(s.eventRegistry.getByType('X','LIQUIDITY_TAKEN').length,1);});
test('Taken source freezes current pivot and all ATR50 partners',function(){var made=makeEq('HIGH',[point('ZA','HIGH',1,99),point('ZB','HIGH',2,101)]),s=runtime(made.event),c=candle(13,102,98,99),taken=replayState.incrementalEvents(s,c,13,c.closeTime,[]).taken[0];assert.equal(taken.source.eqPartnerProvenance.eqModelVersion,producer.VERSION);assert.equal(taken.source.eqPartnerProvenance.currentPivot.price,100);assert.deepEqual(taken.source.eqPartnerProvenance.historicalPartners.map(function(p){return p.id;}),['ZA','ZB']);});
test('unified Event Registry Taken is now a direct WATCH input',function(){var s=runtime(eqh()),c=candle(13,101,98,99);replayState.incrementalEvents(s,c,13,c.closeTime,[]);var rows=s.eventRegistry.getByType('X','LIQUIDITY_TAKEN');assert.equal(rows.length,1);var d={id:'D',type:'DISPLACEMENT',symbol:'X',timeframe:'5m',direction:'BEARISH',formationType:'SINGLE_CANDLE',startIndex:14,endIndex:14,startAt:14*BAR,endAt:15*BAR-1,confirmedAt:15*BAR-1,sourceDetections:[]};var watch=displacementWatch.buildWatch({symbol:'X',displacement:d,evaluationTime:d.confirmedAt,takenEvents:rows,candles:[]});assert.ok(watch);assert.equal(watch.liquidityTrigger,'LIQUIDITY_TAKEN');});
test('notification dry-run builds from direct EQ Taken→Displacement→WATCH path without sending',function(){var eq=eqh(),s=runtime(eq),takenCandle=candle(13,101,98,99),events=replayState.incrementalEvents(s,takenCandle,13,takenCandle.closeTime,[]);assert.equal(events.taken.length,1);var candles=[];for(var i=0;i<17;i++)candles.push(candle(i,101,99,100));candles[14]=candle(14,101,99,100);candles[15]=candle(15,101,89,90,100);candles[16]=candle(16,98,88,90,97);var d={id:'D',type:'DISPLACEMENT',symbol:'X',timeframe:'5m',direction:'BEARISH',formationType:'SINGLE_CANDLE',startIndex:15,endIndex:15,startAt:candles[15].openTime,endAt:candles[15].closeTime,confirmedAt:candles[15].closeTime,sourceDetections:[]};var watch=displacementWatch.buildWatch({symbol:'X',displacement:d,evaluationTime:candles[16].closeTime,takenEvents:events.taken,candles:candles});assert.ok(watch);assert.ok(watch.nativeFvg);watch.state='FVG_TOUCHED';var payload=liveMessages.buildFvgRetracementMessage(watch,watch.nativeFvg.midpoint,{zhEnabled:true,notificationGeneratedAt:candles[16].closeTime});assert.equal(typeof payload,'string');assert.ok(payload.includes('EQH'));assert.ok(payload.includes('100'));assert.ok(payload.includes('Liquidity Taken'));assert.ok(!/undefined|eqMemberProvenance|clusterSize|memberCount|Liquidity Sweep/.test(payload));});
