'use strict';
var assert=require('assert'),audit=require('../scripts/reactionLegParameterizationAuditV1'),base=require('../scripts/swingReactionLegStructuralAttributionAuditV1');
function candles(n){var a=[];for(var i=0;i<n;i++)a.push({openTime:i*300000,closeTime:(i+1)*300000-1,open:100,high:100,low:100,close:100,closed:true});return a;}
function feature(side){return{canonicalSwingId:'S:'+side,side:side,price:100,occurredAt:0,confirmedAt:899999,confirmationIndex:2,sourceIndex:0,atrAtConfirmedAt:2};}
function mss(id,i,d,ref,cs){return{id:id,candleIndex:i,direction:d,confirmedAt:cs[i].closeTime,source:{referenceSwingId:ref&&ref.id}};}
function index(events){var o={};events.forEach(function(e){(o[e.candleIndex]||(o[e.candleIndex]=[])).push(e);});return o;}

(function startsAfterConfirmation(){var cs=candles(12);cs[3]={...cs[3],low:98,close:99};var l=audit.buildPolicyLeg(feature('SWING_HIGH'),cs,{},audit.policySpec('A',1));assert(l.observationStartAt>l.confirmedAt);assert(l.reactionInitiatedIndex===3);})();
(function frontierNeverUsesFutureCandle(){var cs=candles(15);cs[3]={...cs[3],low:96,close:97};cs[4]={...cs[4],high:99,close:99};var a=audit.buildPolicyLeg(feature('SWING_HIGH'),cs.slice(0,8),{},audit.policySpec('A',1)),b=audit.buildPolicyLeg(feature('SWING_HIGH'),cs,{},audit.policySpec('A',1));assert.equal(a.endAt,b.endAt);assert.equal(a.frontierPrice,b.frontierPrice);})();
(function returnToOriginTiming(){var cs=candles(12);cs[3]={...cs[3],low:96,high:99,close:97};cs[4]={...cs[4],high:100,low:97,close:99};var l=audit.buildPolicyLeg(feature('SWING_HIGH'),cs,{},audit.policySpec('B'));assert.equal(l.terminationReason,'RETURN_TO_ORIGIN');assert.equal(l.endAt,cs[4].closeTime);})();
(function oppositeMssOnlyAfterConfirmed(){var cs=candles(12),f=feature('SWING_HIGH');cs[3]={...cs[3],low:96,close:97};var e=mss('RESET',4,'BULLISH',null,cs),before=audit.buildPolicyLeg(f,cs.slice(0,4),{},audit.policySpec('C')),after=audit.buildPolicyLeg(f,cs,index([e]),audit.policySpec('C'));assert.notEqual(before.terminationReason,'OPPOSITE_STRUCTURAL_RESET');assert.equal(after.endAt,e.confirmedAt);})();
(function hybridUsesFirstLegalBoundary(){var cs=candles(12),f=feature('SWING_HIGH');cs[3]={...cs[3],low:96,close:97};cs[4]={...cs[4],high:100,close:99};var e=mss('RESET',5,'BULLISH',null,cs),l=audit.buildPolicyLeg(f,cs,index([e]),audit.policySpec('D',1));assert.equal(l.terminationReason,'RETURN_TO_ORIGIN');assert.equal(l.endAt,cs[4].closeTime);})();
(function maxHorizonIsSafetyCap(){var cs=candles(60);cs[3]={...cs[3],low:99,close:99.5};var l=audit.buildPolicyLeg(feature('SWING_HIGH'),cs,{},audit.policySpec('C'));assert.equal(l.terminationReason,'MAX_HORIZON');assert.equal(l.legEndIndex,42);})();
(function dataEndHandled(){var cs=candles(8);cs[3]={...cs[3],low:99,close:99.5};var l=audit.buildPolicyLeg(feature('SWING_HIGH'),cs,{},audit.policySpec('C'));assert.equal(l.terminationReason,'DATA_END');assert.equal(l.endAt,cs[7].closeTime);})();
(function postTerminationMssCannotAttribute(){var cs=candles(15),f=feature('SWING_HIGH'),ref={id:'LOW',type:'SWING_LOW',price:95,confirmedAt:cs[1].closeTime},by={LOW:ref};cs[3]={...cs[3],low:96,close:97};cs[4]={...cs[4],high:100,close:99};var leg=audit.buildPolicyLeg(f,cs,{},audit.policySpec('B')),late=mss('LATE',5,'BEARISH',ref,cs),br={breakIndex:null},out=base.attributeMss(f,leg,br,{mss:[late],displacements:[]},by,{},cs);assert.equal(out.attributedMss,false);})();
(function newDeliveryCannotAttachToTerminatedLeg(){var cs=candles(15),f=feature('SWING_HIGH');cs[3]={...cs[3],low:96,close:97};cs[4]={...cs[4],high:100,close:99};var leg=audit.buildPolicyLeg(f,cs,{},audit.policySpec('B'));assert(leg.attributionEndIndex<5);})();
(function attributedMssKeepsExactReference(){var cs=candles(15),f=feature('SWING_HIGH'),ref={id:'LOW-X',type:'SWING_LOW',price:95,confirmedAt:cs[1].closeTime},by={'LOW-X':ref};cs[3]={...cs[3],low:96,close:97};cs[4]={...cs[4],low:94,close:94};var leg=audit.buildPolicyLeg(f,cs,{},audit.policySpec('C')),e=mss('M1',4,'BEARISH',ref,cs),snap=base.snapshotStructuralReferences(f,[ref],{}),br=base.structuralBreakFor(f,leg,snap,[e],by,{},cs),out=base.attributeMss(f,leg,br,{mss:[e],displacements:[]},by,{},cs);assert.equal(out.attributedMssReferenceId,'LOW-X');})();
(function sameDeliveryProvenanceContract(){var row={sameDeliveryDisplacement:true,sourceMssId:'M1'};assert(row.sourceMssId);})();
(function sensitivityPoliciesDeterministic(){var cs=candles(20),f=feature('SWING_HIGH');cs[3]={...cs[3],low:96,close:97};[.75,1,1.25].forEach(function(x){assert.deepStrictEqual(audit.buildPolicyLeg(f,cs,{},audit.policySpec('A',x)),audit.buildPolicyLeg(f,cs,{},audit.policySpec('A',x)));});})();
(function historicalSnapshotImmutable(){var cs=candles(20),f=feature('SWING_HIGH');cs[3]={...cs[3],low:96,close:97};cs[4]={...cs[4],high:100,close:99};var old=audit.buildPolicyLeg(f,cs.slice(0,8),{},audit.policySpec('B')),full=audit.buildPolicyLeg(f,cs,{},audit.policySpec('B'));assert.equal(old.endAt,full.endAt);assert.equal(old.terminationReason,full.terminationReason);})();
(function longShortMirrored(){var hi=candles(12),lo=candles(12);hi[3]={...hi[3],low:96,close:97};lo[3]={...lo[3],high:104,close:103};var a=audit.buildPolicyLeg(feature('SWING_HIGH'),hi,{},audit.policySpec('A',1)),b=audit.buildPolicyLeg(feature('SWING_LOW'),lo,{},audit.policySpec('A',1));assert.equal(a.mfeATR,b.mfeATR);assert.equal(a.barsAlive,b.barsAlive);})();
(function futureLeakGuards(){var cs=candles(12),f=feature('SWING_HIGH');cs[3]={...cs[3],low:96,close:97};var p={rows:[Object.assign({},f,audit.buildPolicyLeg(f,cs,{},audit.policySpec('A',1)))],spec:audit.policySpec('A',1)};assert.equal(audit.futureLeaks([p],{}).length,0);})();

console.log('Reaction Leg Parameterization Audit V1 tests passed');
