'use strict';
var test=require('node:test'),assert=require('node:assert/strict');
var dynamicD=require('../liquidity/causalDynamicDHistoricalExtremes');
var methods=require('../research/historical-turning-point-method-audit-v1/methods');
var capture=require('../research/same-process-wick-localization-v1/replayImpactCapture');
var producer=require('../liquidity/productionEqualLiquidityV1');
var watchModel=require('../live/eqFvgCountWatchV1');
var BAR=300000;
function c(i,o,h,l,cl){return{openTime:i*BAR,closeTime:(i+1)*BAR-1,open:o,high:h,low:l,close:cl,volume:1,closed:true,source:'futures'};}
function loc(rows,start,end,side){return dynamicD.chooseSameProcessWickExtreme(rows,start,end,side);}
function runProduction(symbol,rows){var state=dynamicD.createState({symbol:symbol,timeframe:'5m'}),points=[];rows.forEach(function(row,i){points=points.concat(dynamicD.step(state,row,i,rows).dynamicDPoints);});return points;}
function comparablePoint(p){return{side:p.pointSide,selectorOpenTime:p.selectorOccurredAt,selectorPrice:p.selectorPrice,selectorWick:p.selectorWickPrice,localizedOpenTime:p.occurredAt,price:p.price,confirmedAt:p.confirmedAt,theta:p.thetaAtExtreme,processStart:p.processStartBarIndex,processEnd:p.processEndBarIndex,processId:p.processId};}

test('01 LOW chooses the lowest wick rather than the lowest-close candle',function(){var rows=[c(0,10,11,8,9),c(1,10,11,7,10),c(2,10,11,9,10)];assert.deepEqual(loc(rows,0,2,'LOW'),{index:1,openTime:BAR,price:7});});
test('02 HIGH chooses the highest wick rather than the highest-close candle',function(){var rows=[c(0,10,12,9,11),c(1,10,14,9,10),c(2,10,11,9,10)];assert.deepEqual(loc(rows,0,2,'HIGH'),{index:1,openTime:BAR,price:14});});
test('03 already-correct selector localization remains unchanged',function(){var rows=[c(0,10,11,9,10),c(1,10,15,9,14),c(2,10,12,9,10)];assert.equal(loc(rows,0,2,'HIGH').index,1);});
test('04 localized wick may be earlier than selector while confirmation remains separate',function(){var rows=[c(0,10,11,5,10),c(1,9,10,7,8),c(2,10,11,8,10)];var x=loc(rows,0,2,'LOW');assert.equal(x.index,0);assert.equal(rows[2].closeTime,3*BAR-1);});
test('05 localized wick may be later than selector inside the same segment',function(){var rows=[c(0,10,11,8,9),c(1,10,11,6,10),c(2,10,11,9,10)];assert.equal(loc(rows,0,2,'LOW').index,1);});
test('06 localization covers the complete final candidate segment through confirmation',function(){var rows=[c(0,10,11,9,10),c(1,10,12,9,11),c(2,10,13,9,10),c(3,10,16,9,9)];assert.equal(loc(rows,1,3,'HIGH').index,3);});
test('07 equal LOW wick tie preserves the earliest candle',function(){var rows=[c(0,10,11,5,10),c(1,10,11,5,10)];assert.equal(loc(rows,0,1,'LOW').index,0);});
test('08 equal HIGH wick tie preserves the earliest candle',function(){var rows=[c(0,10,15,9,10),c(1,10,15,9,10)];assert.equal(loc(rows,0,1,'HIGH').index,0);});
test('09 candles after confirmation are excluded even when more extreme',function(){var rows=[c(0,10,11,8,10),c(1,10,11,7,10),c(2,10,11,1,10)];assert.equal(loc(rows,0,1,'LOW').price,7);});

var datasets={};Object.keys(capture.SPECS).forEach(function(symbol){datasets[symbol]=capture.candles(capture.SPECS[symbol]);});
test('10 process count, direction, confirmedAt and theta stay equal to frozen close process',function(){Object.keys(datasets).forEach(function(symbol){var rows=datasets[symbol],prod=runProduction(symbol,rows),ab=methods.runAandB(rows,{symbol:symbol});assert.equal(prod.length,ab.A.length,symbol);prod.forEach(function(p,i){assert.equal(p.pointSide,ab.A[i].side);assert.equal(p.confirmedAt,ab.A[i].confirmedAtMs);assert.equal(p.thetaAtExtreme,ab.A[i].thetaSnapshot);assert.equal(p.selectorOccurredAt,ab.A[i].openTimeMs);});});});
test('11 new Production equals frozen Research Method B on all five datasets',function(){Object.keys(datasets).forEach(function(symbol){var rows=datasets[symbol],prod=runProduction(symbol,rows),b=methods.runAandB(rows,{symbol:symbol}).B;assert.equal(prod.length,b.length);prod.forEach(function(p,i){assert.equal(p.occurredAt,b[i].openTimeMs,symbol+' '+i);assert.equal(p.price,b[i].price,symbol+' '+i);assert.equal(p.confirmedAt,b[i].confirmedAtMs);});});});
test('12 BTC regression localizes 23:05 selector to 22:30 wick with unchanged confirmation',function(){var rows=datasets.BTCUSDT,points=runProduction('BTCUSDT',rows),selector=Date.parse('2026-09-06T15:05:00.000Z'),localized=Date.parse('2026-09-06T14:30:00.000Z'),confirmed=Date.parse('2026-09-06T16:34:59.999Z');var p=points.find(function(x){return x.selectorOccurredAt===selector&&x.pointSide==='LOW';});assert.ok(p);assert.equal(p.selectorWickPrice,79466.8);assert.equal(p.occurredAt,localized);assert.equal(p.price,79125.3);assert.equal(p.confirmedAt,confirmed);});
test('13 RAYSOL 20:05 same-candle control remains LOW 1.4935',function(){var rows=datasets.RAYSOLUSDT,points=runProduction('RAYSOLUSDT',rows),when=Date.parse('2026-09-11T12:05:00.000Z');var p=points.find(function(x){return x.selectorOccurredAt===when&&x.pointSide==='LOW';});assert.ok(p);assert.equal(p.occurredAt,when);assert.equal(p.price,1.4935);assert.equal(p.selectorWickPrice,1.4935);});
test('14 versioned canonical id differs from stable close-process identity',function(){var p=runProduction('BTCUSDT',datasets.BTCUSDT)[0];assert.match(p.id,/^DYNDW:SAME_PROCESS_WICK_V1:/);assert.match(p.processId,/^DYNDPROC:/);assert.equal(p.localizationMode,dynamicD.LOCALIZATION_VERSION);});
test('15 production prefix invariance holds with full provenance on 20 cutoffs per symbol',function(){Object.keys(datasets).forEach(function(symbol){var rows=datasets[symbol],full=runProduction(symbol,rows),start=rows.findIndex(function(x){return x.openTime===Date.parse('2026-09-05T16:00:00.000Z');});for(var i=0;i<20;i++){var end=Math.round(start+i*(rows.length-1-start)/19),cutoff=rows[end].closeTime,prefix=runProduction(symbol,rows.slice(0,end+1));var expected=full.filter(function(p){return p.confirmedAt<=cutoff;}).map(comparablePoint);assert.deepEqual(prefix.map(comparablePoint),expected,symbol+' cutoff '+end);}});});
test('16 EQ partner snapshot carries selector and localized provenance without changing current point',function(){var p=runProduction('BTCUSDT',datasets.BTCUSDT).find(function(x){return x.selectorOccurredAt===Date.parse('2026-09-06T15:05:00.000Z');});var state=producer.createState({symbol:'BTCUSDT',timeframe:'5m'});state.fiveMinuteAtrValue=1000;state.dynamicD.recentSurvivalPoints=[p];var pivot={id:'CURRENT',symbol:'BTCUSDT',type:'SWING_LOW',price:p.price,occurredAt:p.confirmedAt+BAR,sourceOpenTime:p.confirmedAt+BAR,sourceCloseTime:p.confirmedAt+2*BAR-1,confirmedAt:p.confirmedAt+3*BAR,metadata:{index:p.occurredBarIndex+1}};var eq=producer.evaluatePivot(state,pivot),partner=eq.metadata.historicalPartners[0];assert.equal(eq.metadata.currentPivot.id,'CURRENT');assert.equal(eq.metadata.historicalExtremeLocalization,dynamicD.LOCALIZATION_VERSION);assert.equal(partner.selectorOpenTime,p.selectorOccurredAt);assert.equal(partner.selectorWickPrice,79466.8);assert.equal(partner.localizedExtremeOpenTime,p.occurredAt);assert.equal(partner.localizedExtremePrice,79125.3);});
test('17 restored WATCH keeps its already-frozen historical partner snapshot immutable',function(){var saved={watchId:'EQ_FVG_COUNT_WATCH_V1:OLD_EQ',version:'EQ_FVG_COUNT_WATCH_V1',symbol:'RAYSOLUSDT',timeframe:'5m',liquidityId:'OLD_EQ',liquidityType:'EQL',liquidityPrice:1.5,liquidityAnchorPrice:1.5,expectedDirection:'BULLISH',openedAt:1,eqSourceContext:{status:'AVAILABLE',historicalPartners:[{id:'OLD',price:1.5,occurredAt:0,confirmedAt:1}]},bullFvgCount:0,bearFvgCount:0,status:'OPEN',consumedRawFvgIds:[]};var machine=watchModel.createStateMachine({watches:[saved]}),before=JSON.stringify(machine.getAll()[0].eqSourceContext);machine.step({evaluationTime:2,newEqualLiquidity:[],rawFvg:null});assert.equal(JSON.stringify(machine.getAll()[0].eqSourceContext),before);});
