'use strict';

var test=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto');
var live=require('../scripts/live'),helper=require('../notify/sweepContextPresentationV1');
function hash(v){return crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');}
function membership(tfs){var o={};['5m','15m','1h','4h'].forEach(function(tf){o[tf]={confirmed:tf==='5m'||tfs.indexOf(tf)>=0,swingId:null,occurredAt:null,confirmedAt:null,provenance:null};});return o;}
function swingContext(side,role,tfs){return{schemaVersion:'SweepContextV1',contextApplicability:'SWING_DERIVED',canonicalSwingId:'S',swingContext:{canonicalSwingId:'S',side:side,structural:{currentRole:role,currentStatus:'CANDIDATE',roleAsOf:20,provenance:{}},timeframeMembership:membership(tfs||[])},memberSwingContexts:[],evaluationTime:50,provenance:{}};}
function candidate(type,side,context){return{id:'SWEEP:1',sweepEventId:'SWEEP:1',sourceId:'SOURCE:1',sourceType:type,sourceTimeframe:'5m',sourcePrice:78690.1,side:side,confirmedAt:50,relation:'BEFORE_LEG',sweepContextV1:context};}
function watch(direction,type,context){var short=direction==='BEARISH',p=candidate(type|| (short?'SWING_HIGH':'SWING_LOW'),short?'BSL':'SSL',context);return{id:'W',symbol:'BTCUSDT',direction:direction,state:'FVG_TOUCHED',createdAt:100,updatedAt:100,notificationKey:'N',liquidityTaken:{primary:{id:p.id,sourceId:p.sourceId,sourceType:p.sourceType,sourceTimeframe:p.sourceTimeframe,sourcePrice:p.sourcePrice,side:p.side,confirmedAt:p.confirmedAt,relation:p.relation},allCandidates:[p]},liquidityEvidenceV1:{currentPrimary:{sweepEventId:p.id,sourceId:p.sourceId,selectionSemantic:'CURRENT_PRODUCTION_RECENCY_HEURISTIC',causalPrimaryClaim:false},candidates:[p],allCandidates:[p],liquidity:{liquiditySide:p.side}},displacement:{direction:direction,quality:'NORMAL',startIndex:1,endIndex:1},nativeFvg:{low:1,high:2,midpoint:1.5},mss:{exists:true,direction:direction,referencePrice:3,referenceRole:'LOCAL',protectedBreak:false},dailyBias:{bias:direction,confidence:'MEDIUM',alignment:'MATCH',status:'VALID'}};}
function render(w,on){return live.buildFvgRetracementMessage(w,1.5,{zhEnabled:true,sweepContextEnabled:on,notificationGeneratedAt:1});}

test('1 structural role maps with LOW side',function(){var s=render(watch('BULLISH','SWING_LOW',swingContext('LOW','ACTIVE_PROTECTED',[])),true);assert.ok(s.includes('结构：受保护低点'));});
test('2 structural role maps symmetrically with HIGH side',function(){var s=render(watch('BEARISH','SWING_HIGH',swingContext('HIGH','ACTIVE_PROTECTED',[])),true);assert.ok(s.includes('结构：受保护高点'));});
test('3 INTERNAL mapping',function(){assert.equal(helper.roleLabel('INTERNAL','LOW'),'内部结构低点');});
test('4 position mapping remains Chinese',function(){var s=render(watch('BULLISH','SWING_LOW',swingContext('LOW','LOCAL_SWING',[])),true);assert.ok(s.includes('时机：位移形成前（BEFORE_LEG）'));});
test('5 bullish and bearish mapping remain symmetric',function(){assert.ok(render(watch('BULLISH','SWING_LOW',swingContext('LOW','LOCAL_SWING',[])),true).includes('方向：向上（BULLISH）'));assert.ok(render(watch('BEARISH','SWING_HIGH',swingContext('HIGH','LOCAL_SWING',[])),true).includes('方向：向下（BEARISH）'));});
test('6 HTF ordering is deterministic 15m then 1H then 4H',function(){var s=render(watch('BULLISH','SWING_LOW',swingContext('LOW','LOCAL_SWING',['4h','15m','1h'])),true);assert.ok(s.includes('高周期：15m / 1H / 4H 摆动低点'));});
test('7 individual 15m context',function(){assert.ok(render(watch('BULLISH','SWING_LOW',swingContext('LOW','LOCAL_SWING',['15m'])),true).includes('高周期：15m 摆动低点'));});
test('8 individual 1H and 4H context',function(){var s=render(watch('BEARISH','SWING_HIGH',swingContext('HIGH','LOCAL_SWING',['1h','4h'])),true);assert.ok(s.includes('高周期：1H / 4H 摆动高点'));});
test('9 EQH/EQL retain multi-member semantics without primary member',function(){var c={contextApplicability:'EQ_MULTI_MEMBER',memberSwingContexts:[{side:'HIGH',timeframeMembership:membership(['15m'])},{side:'HIGH',timeframeMembership:membership(['1h'])}]},w=watch('BEARISH','EQH',c),s=render(w,true);assert.ok(s.includes('等高点（EQH）'));assert.ok(s.includes('结构：EQ 多成员（2 个，不指定主成员）'));assert.ok(s.includes('成员高周期：15m / 1H 摆动高点'));assert.ok(!/主成员：/.test(s));});
test('10 P(D/W/M) native labels do not invent context',function(){[['PDH','前一日高点'],['PDL','前一日低点'],['PWH','前一周高点'],['PWL','前一周低点'],['PMH','前一月高点'],['PML','前一月低点']].forEach(function(x){var s=render(watch(/H$/.test(x[0])?'BEARISH':'BULLISH',x[0],{contextApplicability:'NON_SWING_LIQUIDITY',swingContext:null,memberSwingContexts:[]}),true);assert.ok(s.includes(x[1]+'（'+x[0]+'）'));assert.ok(!s.includes('结构：'));});});
test('11 unresolved fails safe without error wording',function(){var s=render(watch('BULLISH','SWING_LOW',{contextApplicability:'UNRESOLVED',swingContext:null,memberSwingContexts:[],unresolvedReason:'MISSING_PROVENANCE'}),true);assert.ok(s.includes('5m 摆动低点（SWING_LOW）'));assert.ok(!/ERROR|FAILED|MISSING_PROVENANCE|结构：未解析/.test(s));});
test('12 missing context fails safe',function(){var w=watch('BULLISH','SWING_LOW',null);delete w.liquidityEvidenceV1.candidates[0].sweepContextV1;assert.doesNotThrow(function(){render(w,true);});assert.ok(!render(w,true).includes('结构：'));});
test('13 unknown structural enum falls back to raw role',function(){var s=render(watch('BULLISH','SWING_LOW',swingContext('LOW','CUSTOM_ROLE',[])),true);assert.ok(s.includes('结构：CUSTOM_ROLE低点'));});
test('14 formatter does not mutate evidence or WATCH',function(){var w=watch('BULLISH','SWING_LOW',swingContext('LOW','ACTIVE_PROTECTED',['15m'])),before=hash(w);render(w,true);assert.equal(hash(w),before);});
test('15 SweepContext flag OFF preserves current Chinese text exactly',function(){var w=watch('BULLISH','SWING_LOW',swingContext('LOW','ACTIVE_PROTECTED',['15m'])),without=JSON.parse(JSON.stringify(w));delete without.liquidityEvidenceV1.candidates[0].sweepContextV1;delete without.liquidityEvidenceV1.allCandidates[0].sweepContextV1;assert.equal(render(w,false),render(without,false));assert.ok(!render(w,false).includes('结构：受保护低点'));});
test('16 flag ON changes presentation only',function(){var w=watch('BULLISH','SWING_LOW',swingContext('LOW','ACTIVE_PROTECTED',['15m'])),before=hash(w),off=render(w,false),on=render(w,true);assert.notEqual(on,off);assert.equal(hash(w),before);assert.ok(on.includes('结构：受保护低点'));});
test('17 primary and candidate ordering remain unchanged',function(){var w=watch('BULLISH','SWING_LOW',swingContext('LOW','LOCAL_SWING',[])),p2=candidate('PDL','SSL',{contextApplicability:'NON_SWING_LIQUIDITY',swingContext:null,memberSwingContexts:[]}),before=hash(w.liquidityEvidenceV1.currentPrimary),order=[w.liquidityEvidenceV1.candidates[0].sourceId,p2.sourceId];w.liquidityEvidenceV1.candidates.push(p2);render(w,true);assert.equal(hash(w.liquidityEvidenceV1.currentPrimary),before);assert.deepEqual(w.liquidityEvidenceV1.candidates.map(function(c){return c.sourceId;}),order);});
test('18 notification count target and dedup key are unchanged',function(){var ws=[watch('BULLISH','SWING_LOW',swingContext('LOW','LOCAL_SWING',[])),watch('BEARISH','SWING_HIGH',swingContext('HIGH','LOCAL_SWING',[]))],keys=ws.map(function(w){return w.notificationKey;}),out=ws.map(function(w){return render(w,true);});assert.equal(out.length,ws.length);assert.deepEqual(ws.map(function(w){return w.notificationKey;}),keys);});
