#!/usr/bin/env node
'use strict';
var crypto=require('crypto'),fs=require('fs'),path=require('path');
var liveEngine=require('../live/liveEngine'),thresholds=require('../config/thresholds');
var ROOT=path.resolve(__dirname,'..'),OUT=path.resolve(process.argv[2]||path.join(ROOT,'.audit-displacement-watch-lifecycle-v1'));
var SOURCE=path.join(ROOT,'.audit-displacement-centric-watch-fvg-retracement-v1');
var SYMBOL='BTCUSDT',START=Date.parse('2026-07-23T16:40:00.000Z'),END=Date.parse('2026-08-22T16:39:59.999Z'),ENGINE_START=Date.parse('2026-06-23T16:40:00.000Z'),BAR=300000;
var productionFiles=['stats/displacementWatch.js','live/liveEngine.js','live/futuresPriceStream.js','scripts/live.js','events/displacementDetector.js','events/sweepEventAdapter.js','liquidity/liquidityLifecycle.js','config/thresholds.js'];
var hashesBefore=hashes(productionFiles),watches=read('watch-ledger.json'),notifications=read('simulated-notifications.json'),data=loadData();
var candles=data['5m'].filter(function(c){return c.closeTime>=ENGINE_START&&c.closeTime<=END;});
var candleByClose={};candles.forEach(function(c,i){candleByClose[c.closeTime]=Object.assign({index:i},c);});
var engine=liveEngine.createLiveEngine({symbol:SYMBOL,exchangeInfo:data.exchangeInfo,structureCandles:{'1d':data['1d'],'4h':data['4h'],'1h':data['1h']},calendarCandles:{'1d':data['1d'],'1w':data['1w'],'1M':data['1M']},fetcher:function(s,tf){return Promise.resolve(data[tf]||[]);},thresholds:thresholds},{snapshotInterval:12,baseIndex:0,dailyBiasProvider:function(){return{bias:'UNKNOWN',confidence:null,alignment:'UNKNOWN',status:'BYPASSED',evaluationTime:null,ageMs:null};}});
var chain=Promise.resolve();candles.forEach(function(c,i){chain=chain.then(function(){return engine.onBar(c,i).then(function(){engine.drainDisplacementWatchUpdates();});});});
chain.then(build).catch(function(e){console.error(e&&e.stack||e);process.exitCode=1;});

function build(){
 var state=engine.getState(),disps=state.eventRegistry.getByType(SYMBOL,'DISPLACEMENT'),structural=state.eventRegistry.getByType(SYMBOL,'STRUCTURAL_MSS');
 var liquidity=state.registry.getAll(SYMBOL),liqById={};liquidity.forEach(function(x){liqById[x.id]=x;});
 var wById={};watches.forEach(function(w){wById[w.id]=w;});
 var detailed=notifications.map(function(n){
  var w=wById[n.watchId],from=w.createdAt,to=n.firstTouchAt;
  var between=disps.filter(function(d){return d.confirmedAt>from&&d.confirmedAt<to;});
  var same=between.filter(function(d){return d.direction===w.direction;}),opp=between.filter(function(d){return d.direction!==w.direction;});
  var sourceId=w.liquidityTaken&&w.liquidityTaken.primary&&w.liquidityTaken.primary.sourceId,lo=liqById[sourceId]||null;
  var life=[];if(lo){[['touchedAt','TOUCHED'],['sweptAt','SWEPT'],['brokenAt','BROKEN']].forEach(function(x){var t=lo[x[0]];if(t>from&&t<to)life.push({state:x[1],at:t,atIso:iso(t)});});}
  var se=structural.filter(function(e){return e.confirmedAt>from&&e.confirmedAt<to;});
  var f=w.nativeFvg,monitoringStart=Math.max(w.createdAt,f.confirmedAt),preTouch=candles.filter(function(c){return c.closeTime>monitoringStart&&c.closeTime<to;});
  var penetrations=preTouch.filter(function(c){return w.direction==='BULLISH'?c.low<f.low:c.high>f.high;});
  return Object.assign({},n,{newSameDirectionDisplacementCount:same.length,newOppositeDirectionDisplacementCount:opp.length,
   newSameDirectionDisplacements:same.map(compactEvent),newOppositeDirectionDisplacements:opp.map(compactEvent),
   sourceLiquidityObject:lo?compactLiquidity(lo):null,sourceLiquidityLifecycleChanges:life,sourceLiquidityLifecycleChanged:life.length>0,
   nativeFvgFullyPenetratedBeforeTouch:penetrations.length>0,penetrationCandles:penetrations.map(compactCandle),
   structuralStateChanged:se.length>0,structuralStateChanges:se.map(compactStructural),dailyBiasAtFormation:w.dailyBias||null});
 });
 var freshness={TOTAL:buckets(notifications),LONG:buckets(notifications.filter(function(n){return n.direction==='BULLISH';})),SHORT:buckets(notifications.filter(function(n){return n.direction==='BEARISH';}))};
 var narrativeMap={};watches.forEach(function(w){var p=w.liquidityTaken.primary||{},key=w.direction+'|'+(p.id||p.sourceId||'UNKNOWN');if(!narrativeMap[key])narrativeMap[key]={narrativeId:key,direction:w.direction,sweepId:p.id||null,sourceLiquidityId:p.sourceId||null,sourceType:p.sourceType||'UNKNOWN',watches:[],notifications:[]};narrativeMap[key].watches.push(w.id);});
 notifications.forEach(function(n){var w=wById[n.watchId],p=w.liquidityTaken.primary||{},key=w.direction+'|'+(p.id||p.sourceId||'UNKNOWN');if(narrativeMap[key])narrativeMap[key].notifications.push(n.notificationKey);});
 var narratives=Object.keys(narrativeMap).map(function(k){var x=narrativeMap[k];x.watchCount=x.watches.length;x.notificationCount=x.notifications.length;return x;}).sort(function(a,b){return b.watchCount-a.watchCount||a.narrativeId.localeCompare(b.narrativeId);});
 var watchDist={},notifPerNarrative={};narratives.forEach(function(x){watchDist[x.watchCount]=(watchDist[x.watchCount]||0)+1;var k=x.watchCount+' WATCH / '+x.notificationCount+' notifications';notifPerNarrative[k]=(notifPerNarrative[k]||0)+1;});
 var strictClusters=buildStrictClusters(watches,wById);
 var overlap=overlapAudit(watches);
 var typeStats=primaryTypeStats(watches,notifications,wById);
 var samples={};['0–30m','30m–2h','2–8h','8–24h','1–3d','>3d'].forEach(function(label){samples[label]=detailed.filter(function(n){return sampleBand(n.minutesFromWatchToTouch)===label;}).sort(function(a,b){return sha(a.notificationKey).localeCompare(sha(b.notificationKey));}).slice(0,5).map(sampleRecord);});
 var hashesAfter=hashes(productionFiles),changed=productionFiles.filter(function(f){return hashesBefore[f]!==hashesAfter[f];});
 var staleGt24=notifications.filter(function(n){return n.minutesFromWatchToTouch>1440;}).length,staleGt3d=notifications.filter(function(n){return n.minutesFromWatchToTouch>4320;}).length;
 var multiNarr=narratives.filter(function(x){return x.watchCount>1;}),swingW=watches.filter(function(w){return /^SWING_(HIGH|LOW)$/.test((w.liquidityTaken.primary||{}).sourceType||'');}).length;
 var densityCause=(swingW/watches.length>=0.75&&multiNarr.length/narratives.length<0.35)?'COMMON_SWING_LIQUIDITY':((multiNarr.length/narratives.length>=0.35&&staleGt24/notifications.length>=0.1)?'MIXED':(multiNarr.length/narratives.length>=0.35?'WATCH_DUPLICATION':(staleGt24/notifications.length>=0.1?'LONG_LIVED_WATCHES':'MANY_INDEPENDENT_NARRATIVES')));
 var staleRisk=staleGt3d/notifications.length>=0.05?'HIGH':(staleGt24/notifications.length>=0.03?'MEDIUM':'LOW');
 var duplicateShare=narratives.reduce(function(s,x){return s+Math.max(0,x.watchCount-1);},0)/watches.length;
 var dupRisk=duplicateShare>=0.3?'HIGH':(duplicateShare>=0.1?'MEDIUM':'LOW');
 var future=[];detailed.forEach(function(n){var w=wById[n.watchId];if(w.updatedAt>n.firstTouchAt)future.push({watchId:w.id,reason:'FORMATION_UPDATED_AFTER_TOUCH'});(w.liquidityTaken.allCandidates||[]).forEach(function(c){if(c.confirmedAt>w.updatedAt)future.push({watchId:w.id,id:c.id,reason:'SWEEP_AFTER_FORMATION'});});});
 var result={audit:{version:'Displacement Watch Lifecycle Audit V1',symbol:SYMBOL,startIso:iso(START),endIso:iso(END),readOnly:true,outcomeUsed:false,
   narrativeIdentity:'direction + production primary sweep id',strictClusterDefinition:'same narrative; adjacent displacement start <= 60m; native FVG overlap >=75%. Audit-only, no merge/dedupe.',overlapRatioDefinition:'intersection width / smaller FVG width among same-direction watches whose active intervals overlap.'},
  watchToFirstTouchDistribution:freshness,intervalDiagnostics:diagnosticCounts(detailed),clustering:{UNIQUE_LIQUIDITY_NARRATIVES:narratives.length,WATCHES_PER_NARRATIVE_DISTRIBUTION:watchDist,WATCH_NOTIFICATION_COMBINATIONS:notifPerNarrative,MULTI_WATCH_NARRATIVES:multiNarr.length,STRICT_DUPLICATE_CLUSTERS:strictClusters.length,STRICT_CLUSTERED_WATCHES:uniqueCount(strictClusters.reduce(function(a,x){return a.concat(x.watchIds);},[]))},
  fvgOverlap:overlap,primaryLiquidityType:typeStats,populationFacts:{notifications:notifications.length,watches:watches.length,staleOver24h:staleGt24,staleOver3d:staleGt3d,commonSwingWatchCount:swingW,commonSwingWatchPercent:round(swingW/watches.length*100),duplicateWatchSharePercent:round(duplicateShare*100)},
  final:{NOTIFICATION_DENSITY_PRIMARY_CAUSE:densityCause,STALE_NOTIFICATION_RISK:staleRisk,WATCH_DUPLICATION_RISK:dupRisk},
  invariants:{PRODUCTION_CHANGED:changed.length>0,FUTURE_LEAK_VIOLATIONS:future.length,OUTCOME_USED:false},futureLeakDetails:future,productionHashChanges:changed};
 if(!fs.existsSync(OUT))fs.mkdirSync(OUT,{recursive:true});
 fs.writeFileSync(path.join(OUT,'summary.json'),JSON.stringify(result,null,2));fs.writeFileSync(path.join(OUT,'notification-lifecycle-ledger.json'),JSON.stringify(detailed,null,2));fs.writeFileSync(path.join(OUT,'narrative-clusters.json'),JSON.stringify(narratives,null,2));fs.writeFileSync(path.join(OUT,'strict-overlap-clusters.json'),JSON.stringify(strictClusters,null,2));fs.writeFileSync(path.join(OUT,'freshness-review-samples.json'),JSON.stringify(samples,null,2));fs.writeFileSync(path.join(OUT,'DISPLACEMENT_WATCH_LIFECYCLE_AUDIT_V1_REPORT.md'),render(result));
 console.log(JSON.stringify({distribution:freshness,diagnostics:result.intervalDiagnostics,clustering:result.clustering,fvgOverlap:overlap,primaryLiquidityType:typeStats,populationFacts:result.populationFacts,final:result.final,invariants:result.invariants,output:OUT},null,2));if(changed.length||future.length)process.exitCode=1;
}
function buckets(rows){var o={'<=15m':0,'>15m–30m':0,'>30m–1h':0,'>1h–2h':0,'>2h–4h':0,'>4h–8h':0,'>8h–12h':0,'>12h–24h':0,'>1d–2d':0,'>2d–3d':0,'>3d':0};rows.forEach(function(n){var m=n.minutesFromWatchToTouch,k=m<=15?'<=15m':m<=30?'>15m–30m':m<=60?'>30m–1h':m<=120?'>1h–2h':m<=240?'>2h–4h':m<=480?'>4h–8h':m<=720?'>8h–12h':m<=1440?'>12h–24h':m<=2880?'>1d–2d':m<=4320?'>2d–3d':'>3d';o[k]++;});return o;}
function diagnosticCounts(rows){return{NEW_SAME_DIRECTION_DISPLACEMENT:rows.filter(function(x){return x.newSameDirectionDisplacementCount>0;}).length,NEW_OPPOSITE_DIRECTION_DISPLACEMENT:rows.filter(function(x){return x.newOppositeDirectionDisplacementCount>0;}).length,LIQUIDITY_LIFECYCLE_CHANGED:rows.filter(function(x){return x.sourceLiquidityLifecycleChanged;}).length,NATIVE_FVG_FULLY_PENETRATED_BEFORE_TOUCH:rows.filter(function(x){return x.nativeFvgFullyPenetratedBeforeTouch;}).length,STRUCTURAL_STATE_CHANGED:rows.filter(function(x){return x.structuralStateChanged;}).length};}
function activeInterval(w){return{start:Math.max(w.createdAt,w.nativeFvg?w.nativeFvg.confirmedAt:w.createdAt),end:w.firstTouchAt||w.invalidatedAt||END};}
function overlapRatio(a,b){var x=Math.max(0,Math.min(a.high,b.high)-Math.max(a.low,b.low)),den=Math.min(a.high-a.low,b.high-b.low);return den>0?x/den:0;}
function intervalsOverlap(a,b){return Math.max(a.start,b.start)<Math.min(a.end,b.end);}
function overlapAudit(ws){var f=ws.filter(function(w){return!!w.nativeFvg;}),o={EXACT_DUPLICATE:0,'>=75%_LT_EXACT':0,'>=50%_LT75%':0,'>=25%_LT50%':0,'>0%_LT25%':0,NO_OVERLAP:0,TOTAL_ACTIVE_PAIRS:0};for(var i=0;i<f.length;i++)for(var j=i+1;j<f.length;j++){if(f[i].direction!==f[j].direction||!intervalsOverlap(activeInterval(f[i]),activeInterval(f[j])))continue;o.TOTAL_ACTIVE_PAIRS++;var r=overlapRatio(f[i].nativeFvg,f[j].nativeFvg),same=f[i].nativeFvg.low===f[j].nativeFvg.low&&f[i].nativeFvg.high===f[j].nativeFvg.high;if(same)o.EXACT_DUPLICATE++;else if(r>=.75)o['>=75%_LT_EXACT']++;else if(r>=.5)o['>=50%_LT75%']++;else if(r>=.25)o['>=25%_LT50%']++;else if(r>0)o['>0%_LT25%']++;else o.NO_OVERLAP++;}return o;}
function buildStrictClusters(ws){var groups={};ws.filter(function(w){return!!w.nativeFvg;}).forEach(function(w){var p=w.liquidityTaken.primary||{},k=w.direction+'|'+(p.id||p.sourceId||'UNKNOWN');(groups[k]||(groups[k]=[])).push(w);});var out=[];Object.keys(groups).forEach(function(k){var g=groups[k].sort(function(a,b){return a.displacement.firstConfirmedAt-b.displacement.firstConfirmedAt;}),cur=[];g.forEach(function(w){if(!cur.length){cur=[w];return;}var prev=cur[cur.length-1],near=w.displacement.firstConfirmedAt-prev.displacement.firstConfirmedAt<=3600000,ov=overlapRatio(prev.nativeFvg,w.nativeFvg)>=.75;if(near&&ov)cur.push(w);else{if(cur.length>1)out.push(clusterRec(k,cur));cur=[w];}});if(cur.length>1)out.push(clusterRec(k,cur));});return out;}
function clusterRec(k,g){return{narrativeId:k,watchIds:g.map(function(w){return w.id;}),watchCount:g.length,notificationCount:g.filter(function(w){return!!w.firstTouchAt;}).length,start:g[0].createdAt,end:g[g.length-1].updatedAt};}
function primaryTypeStats(ws,ns,wById){var names=['SWING_HIGH','SWING_LOW','EQH','EQL','PDH','PDL','PWH','PWL','SESSION','OTHER'],o={};names.forEach(function(k){o[k]={watchCount:0,nativeFvgCount:0,firstTouchCount:0,medianWatchToTouchMinutes:null};});var mins={};names.forEach(function(k){mins[k]=[];});ws.forEach(function(w){var k=typeBucket((w.liquidityTaken.primary||{}).sourceType);o[k].watchCount++;if(w.nativeFvg)o[k].nativeFvgCount++;});ns.forEach(function(n){var w=wById[n.watchId],k=typeBucket((w.liquidityTaken.primary||{}).sourceType);o[k].firstTouchCount++;mins[k].push(n.minutesFromWatchToTouch);});names.forEach(function(k){o[k].medianWatchToTouchMinutes=median(mins[k]);});return o;}
function typeBucket(t){t=String(t||'OTHER').toUpperCase();if(['SWING_HIGH','SWING_LOW','EQH','EQL','PDH','PDL','PWH','PWL'].indexOf(t)>=0)return t;if(/^(ASIA|LONDON|NEW_YORK)_(HIGH|LOW)$/.test(t))return'SESSION';return'OTHER';}
function sampleBand(m){return m<=30?'0–30m':m<=120?'30m–2h':m<=480?'2–8h':m<=1440?'8–24h':m<=4320?'1–3d':'>3d';}
function sampleRecord(n){var w=watches.filter(function(x){return x.id===n.watchId;})[0],touch=candleByClose[n.firstTouchAt],ki=w.nativeFvg?candleByClose[w.nativeFvg.confirmedAt]:null;return{notificationKey:n.notificationKey,freshnessBand:sampleBand(n.minutesFromWatchToTouch),watchToTouchMinutes:n.minutesFromWatchToTouch,formation:{watchId:w.id,createdAt:w.createdAt,direction:w.direction,liquidityTaken:w.liquidityTaken,displacement:w.displacement,nativeFvg:w.nativeFvg,mss:w.mss,structuralProvenance:w.structuralProvenance,dailyBias:w.dailyBias,nativeFvgFormationCandles:ki?candles.slice(Math.max(0,ki.index-2),ki.index+1).map(compactCandle):[]},touch:{firstTouchAt:n.firstTouchAt,candle:compactCandle(touch)},outcomeAfterTouchIncluded:false};}
function compactEvent(e){return{id:e.id,direction:e.direction,confirmedAt:e.confirmedAt,confirmedAtIso:iso(e.confirmedAt),candleIndex:e.candleIndex};}function compactStructural(e){return{id:e.id,direction:e.direction,confirmedAt:e.confirmedAt,stateBefore:e.structuralStateBefore,stateAfter:e.structuralStateAfter};}function compactLiquidity(l){return{id:l.id,type:l.type,side:l.side,price:l.price,confirmedAt:l.confirmedAt,status:l.status,touchedAt:l.touchedAt,sweptAt:l.sweptAt,brokenAt:l.brokenAt};}function compactCandle(c){return c?{openTime:c.openTime,closeTime:c.closeTime,open:c.open,high:c.high,low:c.low,close:c.close,closed:c.closed,source:c.source}:null;}
function uniqueCount(a){return new Set(a).size;}function median(a){if(!a.length)return null;var x=a.slice().sort(function(p,q){return p-q;});return x[Math.floor((x.length-1)/2)];}function round(n){return Math.round(n*1e6)/1e6;}function iso(t){return new Date(t).toISOString();}function sha(s){return crypto.createHash('sha256').update(String(s)).digest('hex');}
function read(f){return JSON.parse(fs.readFileSync(path.join(SOURCE,f),'utf8'));}function hashes(files){var o={};files.forEach(function(f){o[f]=sha(fs.readFileSync(path.join(ROOT,f)));});return o;}
function loadData(){var dir=path.join(ROOT,'data-cache'),out={};['5m','1h','4h','1d','1w','1M'].forEach(function(tf){var by={};fs.readdirSync(dir).filter(function(f){return f.indexOf(SYMBOL+'_'+tf+'_')===0&&/\.json$/.test(f);}).forEach(function(f){var rows;try{rows=JSON.parse(fs.readFileSync(path.join(dir,f),'utf8'));}catch(e){return;}(rows||[]).forEach(function(c){if(c&&c.source==='futures'&&c.closed!==false&&c.closeTime>=ENGINE_START&&c.closeTime<=END)by[c.openTime]=c;});});out[tf]=Object.keys(by).map(function(k){return by[k];}).sort(function(a,b){return a.openTime-b.openTime;});});var ep=path.join(dir,SYMBOL+'_EXCHANGE.json');out.exchangeInfo=fs.existsSync(ep)?JSON.parse(fs.readFileSync(ep,'utf8')):{symbol:SYMBOL,tickSize:.1};return out;}
function render(r){return['# Displacement Watch Lifecycle Audit V1','','- Read-only: true','- Outcome used: false','','## Final','','- NOTIFICATION_DENSITY_PRIMARY_CAUSE = '+r.final.NOTIFICATION_DENSITY_PRIMARY_CAUSE,'- STALE_NOTIFICATION_RISK = '+r.final.STALE_NOTIFICATION_RISK,'- WATCH_DUPLICATION_RISK = '+r.final.WATCH_DUPLICATION_RISK,'','## Invariants','','- PRODUCTION_CHANGED = '+r.invariants.PRODUCTION_CHANGED,'- FUTURE_LEAK_VIOLATIONS = '+r.invariants.FUTURE_LEAK_VIOLATIONS,''].join('\n');}
