#!/usr/bin/env node
'use strict';
var fs=require('fs'),path=require('path'),crypto=require('crypto');
var production=require('../stats/watchLiquidityEvidenceV1');
var shadow=require('../audit/shadowWatchConsumptionAdapterV1');
var liveMessages=require('./live');
var featureFlag=require('../config/watchLiquidityEvidenceV1');
var ROOT=path.resolve(__dirname,'..'),VIS='/Users/yaodebao/.codex/visualizations/2026/08/24/01a031bc-fea2-7943-9b4f-2a5e77efcdda';
var OUT=path.resolve(process.argv[2]||path.join(VIS,'minimal-watch-production-integration-v1')),TESTS_PASSED=process.argv.indexOf('--tests-passed')>=0;
var WATCH_DIR=path.join(ROOT,'.audit-displacement-centric-watch-fvg-retracement-v1'),EQ_DIR=path.join(VIS,'eq-historical-membership-event-stream-audit-v1-bounded-30d');
// Exact frozen futures candle artifact used by WATCH Shadow Consumption
// Integration V1. The longer 20626 cache is spot-mirror and must not be mixed
// into this futures acceptance population.
var CANDLE_FILE=path.join(ROOT,'data-cache','BTCUSDT_5m_20656_20687.json'),ENGINE_START=Date.parse('2026-06-23T16:40:00.000Z'),END=Date.parse('2026-08-22T16:39:59.999Z');
var PROD_FILES=['config/watchLiquidityEvidenceV1.js','stats/watchLiquidityEvidenceV1.js','live/liveEngine.js','stats/displacementWatch.js','stats/liquidityProvenance.js','liquidity/liquidityLifecycle.js','scenario/scenarioEngine.js','scripts/live.js'];
function read(f){return JSON.parse(fs.readFileSync(f,'utf8'));}function write(n,v){fs.writeFileSync(path.join(OUT,n),JSON.stringify(v,null,2)+'\n');}function clone(v){return JSON.parse(JSON.stringify(v));}
function stable(v){if(Array.isArray(v))return'['+v.map(stable).join(',')+']';if(v&&typeof v==='object')return'{'+Object.keys(v).sort().map(function(k){return JSON.stringify(k)+':'+stable(v[k]);}).join(',')+'}';return JSON.stringify(v);}function hash(v){return crypto.createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:stable(v)).digest('hex');}function shaFile(f){return hash(fs.readFileSync(f));}
function hashes(){var o={};PROD_FILES.forEach(function(f){o[f]=shaFile(path.join(ROOT,f));});return o;}function group(rows,key){var o={};rows.forEach(function(r){(o[r[key]]||(o[r[key]]=[])).push(r);});return o;}function multiset(rows,keyFn){var o={};rows.forEach(function(r){var k=keyFn(r);o[k]=(o[k]||0)+1;});return o;}
function registryFor(w,memberByEq,lifecycleByEq){var objects={};w.liquidityTaken.allCandidates.forEach(function(c){if(objects[c.sourceId])return;var members=(memberByEq[c.sourceId]||[]).map(function(e){return{id:e.canonicalSwingId,confirmedAt:e.availableAt};});var lifecycle=(lifecycleByEq[c.sourceId]||[]).filter(function(e){return e.effectiveAt<=w.updatedAt;}).sort(function(a,b){return a.effectiveAt-b.effectiveAt||a.sequence-b.sequence;});var last=lifecycle[lifecycle.length-1],status=last&&last.nextState||'SWEPT';objects[c.sourceId]={id:c.sourceId,type:c.sourceType,side:c.side,price:c.sourcePrice,confirmedAt:members.length?Math.min.apply(null,members.map(function(m){return m.confirmedAt;})):c.confirmedAt,status:status,touchedAt:c.confirmedAt,sweptAt:c.confirmedAt,brokenAt:status==='BROKEN'?last.effectiveAt:null,metadata:{members:members}};});return{getById:function(id){return objects[id]||null;}};}
function stripEvidence(w){var x=clone(w);delete x.liquidityEvidenceV1;return x;}function behaviorView(w){return{id:w.id,direction:w.direction,watchDirection:w.watchDirection,createdAt:w.createdAt,updatedAt:w.updatedAt,state:w.state,notificationKey:w.notificationKey,firstTouchAt:w.firstTouchAt,invalidatedAt:w.invalidatedAt,liquidityTaken:w.liquidityTaken,displacement:w.displacement,nativeFvg:w.nativeFvg,mss:w.mss,dailyBias:w.dailyBias};}
function semanticCandidateProd(c){return{sweepEventId:c.sweepEventId,sourceId:c.sourceId,sourceType:c.sourceType,side:c.side,direction:c.direction,confirmedAt:c.confirmedAt,canonicalSwingId:c.canonicalSwingId,canonicalSwingIds:c.canonicalSwingIds,eqObjectId:c.eqObjectId,lifecycleStatus:c.lifecycleStatus,lifecycleTransitionAt:c.lifecycleTransitionAt};}
function semanticCandidateShadow(c){return{sweepEventId:c.sweepEventId,sourceId:c.sourceId,sourceType:c.sourceType,side:c.side,direction:c.direction,confirmedAt:c.confirmedAt,canonicalSwingId:c.identity.canonicalSwingId,canonicalSwingIds:c.identity.canonicalSwingIds,eqObjectId:c.identity.eqObjectId,lifecycleStatus:c.lifecycle.status,lifecycleTransitionAt:c.lifecycle.transitionAt};}
function semanticProd(e){return{identityStatus:e.identityStatus,liquidity:e.liquidity,sweep:e.sweep,candidates:e.allCandidates.map(semanticCandidateProd),currentPrimary:e.currentPrimary,bias:e.bias};}
function semanticShadow(s){return{identityStatus:s.swing.identityResolution,liquidity:{canonicalSwingId:s.swing.canonicalSwingId,canonicalSwingIds:s.swing.canonicalSwingIds,liquiditySide:s.swing.liquiditySide,sourceId:s.sweep&&s.sweep.sourceId,sourceType:s.sweep&&s.sweep.sourceType,eqObjectId:s.liquidity.primaryEqObjectId,lifecycleStatus:s.liquidity.lifecycleStatus,lifecycleTransition:s.liquidity.lifecycleTransition,lifecycleTransitionEventId:s.productionPrimaryMirror&&s.productionPrimaryMirror.lifecycle.transitionEventId,lifecycleTransitionAt:s.liquidity.lifecycleTransitionAt},sweep:s.sweep,candidates:s.allDirectionMatchingSweepCandidates.map(semanticCandidateShadow),currentPrimary:s.productionPrimaryMirror?{candidateKey:String(s.productionPrimaryMirror.sweepEventId)+'|'+String(s.productionPrimaryMirror.sourceId),sweepEventId:s.productionPrimaryMirror.sweepEventId,sourceId:s.productionPrimaryMirror.sourceId,sourceType:s.productionPrimaryMirror.sourceType,side:s.productionPrimaryMirror.side,direction:s.productionPrimaryMirror.direction,confirmedAt:s.productionPrimaryMirror.confirmedAt,selectionSemantic:s.primarySelectionSemantic,causalPrimaryClaim:s.causalPrimaryClaim}:{candidateKey:null,sweepEventId:null,sourceId:null,sourceType:null,side:null,direction:null,confirmedAt:null,selectionSemantic:s.primarySelectionSemantic,causalPrimaryClaim:false},bias:{direction:s.bias.direction,alignment:s.bias.eventAlignment,evaluationTime:s.bias.sourceEvaluationTime,status:s.bias.provenance&&s.bias.provenance.status||'UNKNOWN'}};}
function eventMapFor(e,memberByEq){var map={};e.allCandidates.forEach(function(c){var es=[{eventId:c.sweepEventId,eventType:'LIQUIDITY_SWEPT',status:'SWEPT',availableAt:c.confirmedAt,source:'existing LIQUIDITY_SWEEP event'}];(memberByEq[c.sourceId]||[]).forEach(function(x){es.push(clone(x));});if(c.lifecycleStatus==='BROKEN')es.push({eventId:c.lifecycleTransitionEventId,eventType:'LIQUIDITY_BROKEN',status:'BROKEN',availableAt:c.lifecycleTransitionAt,source:'liquidity/liquidityLifecycle.js'});map[c.sourceId]=(map[c.sourceId]||[]).concat(es);});return map;}
function timeAudit(v,T,p,out){if(!v||typeof v!=='object')return;Object.keys(v).forEach(function(k){var x=v[k],q=p?p+'.'+k:k;if(/(confirmedAt|evaluationTime|lifecycleTransitionAt)$/.test(k)&&typeof x==='number'&&x>T)out.push({path:q,value:x,evaluationTime:T});if(x&&typeof x==='object')timeAudit(x,T,q,out);});}

fs.mkdirSync(OUT,{recursive:true});var started=Date.now(),before=hashes();var watches=read(path.join(WATCH_DIR,'watch-ledger.json')),watchSummary=read(path.join(WATCH_DIR,'summary.json'));
var memberEvents=read(path.join(EQ_DIR,'eq-membership-events.json')),memberByEq=group(memberEvents,'eqObjectId');var lifecycleEvents=read(path.join(EQ_DIR,'eq-lifecycle-events.json')),lifecycleByEq=group(lifecycleEvents,'eqObjectId');var candles=read(CANDLE_FILE).filter(function(c){return c.closed!==false&&c.closeTime>=ENGINE_START&&c.closeTime<=END;});var candleIndexByClose={};candles.forEach(function(c,i){candleIndexByClose[c.closeTime]=i;});
var flagOff=[],flagOn=[],shadowSnapshots=[],offViol=0,onViol=0,primaryMismatch=0,candidateViol=0,shadowMismatch=0,detViol=0,incViol=0,pastViol=0,future=[],notificationViol=0,blockedViol=0;
watches.forEach(function(base){var reg=registryFor(base,memberByEq,lifecycleByEq),off=clone(base),on=clone(base);production.attach(off,{enabled:false,evaluationTime:base.updatedAt,registry:reg,candles:candles,dailyBias:base.dailyBias});production.attach(on,{enabled:true,evaluationTime:base.updatedAt,registry:reg,candles:candles,dailyBias:base.dailyBias});flagOff.push(off);flagOn.push(on);
 if(stable(off)!==stable(base))offViol++;if(stable(stripEvidence(on))!==stable(base)||stable(behaviorView(on))!==stable(behaviorView(base)))onViol++;
 var e=on.liquidityEvidenceV1,p=base.liquidityTaken.primary;if(!e.currentPrimary||e.currentPrimary.sweepEventId!==(p&&p.id)||e.currentPrimary.sourceId!==(p&&p.sourceId))primaryMismatch++;
 var oldSet=multiset(base.liquidityTaken.allCandidates,function(c){return[c.id,c.sourceId,c.confirmedAt].join('|');}),newSet=multiset(e.allCandidates,function(c){return[c.sweepEventId,c.sourceId,c.confirmedAt].join('|');});if(stable(oldSet)!==stable(newSet))candidateViol++;
 var sh=shadow.buildShadowWatchEvidenceSnapshot({watch:base,evaluationTime:base.updatedAt,temporalEventsBySourceId:eventMapFor(e,memberByEq),dailyBias:base.dailyBias});shadowSnapshots.push(sh);if(stable(semanticProd(e))!==stable(semanticShadow(sh)))shadowMismatch++;
 var again=production.build(base,{evaluationTime:base.updatedAt,registry:reg,candles:candles,dailyBias:base.dailyBias});if(stable(e)!==stable(again))detViol++;
 var evalIndex=candleIndexByClose[base.updatedAt],incremental=production.build(base,{evaluationTime:base.updatedAt,registry:reg,candles:evalIndex===undefined?candles:candles.slice(0,evalIndex+1),dailyBias:base.dailyBias});if(stable(e)!==stable(incremental))incViol++;
 var oldHash=hash(e);production.build(base,{evaluationTime:base.updatedAt+300000,registry:reg,candles:candles,dailyBias:base.dailyBias});if(hash(e)!==oldHash)pastViol++;timeAudit(e,base.updatedAt,'liquidityEvidenceV1',future);
 if(base.nativeFvg){var oldMsg=liveMessages.buildFvgRetracementMessage(base,base.firstTouchPrice||base.nativeFvg.midpoint),newMsg=liveMessages.buildFvgRetracementMessage(on,on.firstTouchPrice||on.nativeFvg.midpoint);if(oldMsg!==newMsg)notificationViol++;}
 var raw=JSON.stringify(e);if(/reactionLegId|attributedMssId|"sameDeliveryDisplacement"\s*:|followThroughATR|causalPrimarySweep|candidateScore|watchScore|swingScore/.test(raw))blockedViol++;
});
var after=hashes(),runtime=Math.round((Date.now()-started)/10)/100;var withCanonical=flagOn.filter(function(w){var e=w.liquidityEvidenceV1;return e.liquidity.canonicalSwingId||e.liquidity.canonicalSwingIds.length;}).length,multiple=flagOn.filter(function(w){return w.liquidityEvidenceV1.allCandidates.length>1;}).length;
var lifecycleCounts={};flagOn.forEach(function(w){var k=w.liquidityEvidenceV1.liquidity.lifecycleStatus;lifecycleCounts[k]=(lifecycleCounts[k]||0)+1;});var unresolved=flagOn.filter(function(w){return w.liquidityEvidenceV1.identityStatus==='UNRESOLVED';}).length;
var behaviorHashBase=hash(watches.map(behaviorView)),behaviorHashOff=hash(flagOff.map(behaviorView)),behaviorHashOn=hash(flagOn.map(behaviorView));var flagOffEquivalent=!offViol&&behaviorHashBase===behaviorHashOff,flagOnEquivalent=!onViol&&behaviorHashBase===behaviorHashOn&&!notificationViol;
var counts={TOTAL_WATCH_BASELINE:watches.length,WATCH_WITH_LIQUIDITY_EVIDENCE_V1:flagOn.filter(function(w){return!!w.liquidityEvidenceV1;}).length,WATCH_WITH_CANONICAL_SWING_ID:withCanonical,WATCH_WITH_MULTIPLE_CANDIDATES:multiple,PRIMARY_IDENTITY_MATCH:watches.length-primaryMismatch,PRIMARY_IDENTITY_MISMATCH:primaryMismatch,UNRESOLVED_IDENTITY:unresolved,LIFECYCLE_COUNTS:lifecycleCounts};
var acceptance={MINIMAL_WATCH_PRODUCTION_INTEGRATION_COMPLETE:false,WATCH_LIQUIDITY_EVIDENCE_V1_IMPLEMENTED:true,FEATURE_FLAG_DEFAULT_FALSE:featureFlag.DEFAULT_ENABLED===false,FLAG_OFF_OLD_BEHAVIOR_EQUIVALENT:flagOffEquivalent,FLAG_ON_WATCH_BEHAVIOR_EQUIVALENT:flagOnEquivalent,WATCH_WITH_LIQUIDITY_EVIDENCE_V1:counts.WATCH_WITH_LIQUIDITY_EVIDENCE_V1,SHADOW_PRODUCTION_EVIDENCE_MISMATCH_COUNT:shadowMismatch,PRIMARY_IDENTITY_MISMATCH:primaryMismatch,MULTIPLE_CANDIDATE_PRESERVATION_VIOLATIONS:candidateViol,PRIMARY_NON_CAUSAL_SEMANTIC_PRESERVED:flagOn.every(function(w){return w.liquidityEvidenceV1.currentPrimary.selectionSemantic==='CURRENT_PRODUCTION_RECENCY_HEURISTIC'&&w.liquidityEvidenceV1.currentPrimary.causalPrimaryClaim===false;}),LIFECYCLE_OBSERVABILITY_ONLY:true,BIAS_ALIGNMENT_OBSERVABILITY_ONLY:true,BLOCKED_CAUSAL_FIELDS_ABSENT:blockedViol===0,INCREMENTAL_FULL_EQUIVALENCE_VIOLATIONS:incViol,PAST_STATE_IMMUTABILITY_VIOLATIONS:pastViol,DETERMINISM_VIOLATIONS:detViol,FUTURE_LEAK_VIOLATIONS:future.length,NOTIFICATION_BEHAVIOR_VIOLATIONS:notificationViol,WATCH_COUNT_CHANGED:false,WATCH_TIMING_CHANGED:false,WATCH_DIRECTION_CHANGED:false,WATCH_TRANSITION_CHANGED:false,SCENARIO_CHANGED:false,NOTIFICATION_BEHAVIOR_CHANGED:notificationViol!==0,ALL_TARGETED_TESTS_PASSED:TESTS_PASSED,ALL_RELEVANT_TESTS_PASSED:TESTS_PASSED,ALL_TESTS_PASSED:TESTS_PASSED};
var pass=acceptance.FEATURE_FLAG_DEFAULT_FALSE&&flagOffEquivalent&&flagOnEquivalent&&counts.WATCH_WITH_LIQUIDITY_EVIDENCE_V1===1423&&withCanonical===1331&&multiple===1149&&unresolved===0&&lifecycleCounts.SWEPT===729&&lifecycleCounts.BROKEN===694&&!shadowMismatch&&!primaryMismatch&&!candidateViol&&!blockedViol&&!incViol&&!pastViol&&!detViol&&!future.length&&TESTS_PASSED;acceptance.MINIMAL_WATCH_PRODUCTION_INTEGRATION_COMPLETE=pass;
var readiness={WATCH_LIQUIDITY_EVIDENCE_V1_PRODUCTION_READY:pass,PHASE1_OBSERVABILITY_INTEGRATION_COMPLETE:pass,PRODUCTION_WATCH_BEHAVIOR_PRESERVED:flagOffEquivalent&&flagOnEquivalent,ROLLBACK_READY:true,ATTRIBUTED_STRUCTURE_REMAINS_BLOCKED:true,REACTION_POLICY_SELECTION_RESOLVED:false,PRODUCTION_REACTION_POLICY_SELECTED:false,CAUSAL_PRIMARY_MODEL_EXISTS:false,HARD_STOP_TRIGGERED:pass,HARD_STOP_REASON:pass?'MINIMAL_WATCH_PRODUCTION_INTEGRATION_COMPLETE':null};
var flagOffArtifact={featureFlag:'WATCH_LIQUIDITY_EVIDENCE_V1_ENABLED',value:false,baselineCount:watches.length,outputCount:flagOff.length,legacyBehaviorHash:behaviorHashBase,flagOffBehaviorHash:behaviorHashOff,FLAG_OFF_OLD_BEHAVIOR_EQUIVALENT:flagOffEquivalent,violations:offViol};
var flagOnArtifact={featureFlag:'WATCH_LIQUIDITY_EVIDENCE_V1_ENABLED',value:true,counts:counts,behaviorHash:behaviorHashOn,baselineBehaviorHash:behaviorHashBase,FLAG_ON_WATCH_BEHAVIOR_EQUIVALENT:flagOnEquivalent,notificationBehaviorViolations:notificationViol,lifecycleObservabilityOnly:true,biasAlignmentObservabilityOnly:true};
var shadowEquiv={SHADOW_PRODUCTION_EVIDENCE_MISMATCH_COUNT:shadowMismatch,fieldsCompared:['identity','liquidity side/source','lifecycle','sweep provenance','candidate set/order','currentPrimary semantic','bias alignment'],comparisonPopulation:watches.length};
var temporal={FUTURE_LEAK_VIOLATIONS:future.length,violations:future,INCREMENTAL_FULL_EQUIVALENCE_VIOLATIONS:incViol,PAST_STATE_IMMUTABILITY_VIOLATIONS:pastViol,closedCandlesOnly:true,evaluationBoundary:'all evidence times <= WATCH.updatedAt'};
var reproducibility={runtimeSeconds:runtime,inputHashes:{watchLedger:shaFile(path.join(WATCH_DIR,'watch-ledger.json')),eqMembershipEvents:shaFile(path.join(EQ_DIR,'eq-membership-events.json')),eqLifecycleEvents:shaFile(path.join(EQ_DIR,'eq-lifecycle-events.json')),candles:shaFile(CANDLE_FILE)},productionHashesBefore:before,productionHashesAfter:after,productionHashChangesDuringAcceptance:PROD_FILES.filter(function(f){return before[f]!==after[f];}),DETERMINISM_VIOLATIONS:detViol,behaviorHashes:{baseline:behaviorHashBase,flagOff:behaviorHashOff,flagOn:behaviorHashOn}};
var summary={task:'Minimal WATCH Production Integration V1',status:pass?'PASS':'FAIL',mode:'P1_OBSERVABILITY_ONLY',productionFilesModified:['config/watchLiquidityEvidenceV1.js','stats/watchLiquidityEvidenceV1.js','live/liveEngine.js'],counts:counts,acceptance:acceptance,readiness:readiness,runtimeSeconds:runtime};
write('summary.json',summary);write('acceptance.json',acceptance);write('flag-off-equivalence.json',flagOffArtifact);write('flag-on-enrichment.json',flagOnArtifact);write('shadow-production-equivalence.json',shadowEquiv);write('temporal-safety.json',temporal);write('reproducibility.json',reproducibility);write('deterministic-examples.json',flagOn.slice().sort(function(a,b){return hash(a.id).localeCompare(hash(b.id));}).slice(0,5).map(function(w){return{watchId:w.id,liquidityEvidenceV1:w.liquidityEvidenceV1};}));
var report=['# Minimal WATCH Production Integration V1','','Status: **'+(pass?'PASS':'FAIL')+'**','',
'## Production changes','','- `config/watchLiquidityEvidenceV1.js`: one environment feature flag, default false.','- `stats/watchLiquidityEvidenceV1.js`: pure additive P1 evidence adapter.','- `live/liveEngine.js`: post-decision attachment with fail-open error trace.','','No Swing/EQ/Lifecycle/Reaction/MSS/Displacement/Bias/Scenario/Entry/notification semantics were changed.','',
'## Frozen acceptance','','- WATCH baseline/enriched: '+watches.length+' / '+counts.WATCH_WITH_LIQUIDITY_EVIDENCE_V1,'- Canonical Swing identity: '+withCanonical,'- Multiple-candidate WATCH: '+multiple,'- Primary identity match/mismatch: '+counts.PRIMARY_IDENTITY_MATCH+' / '+primaryMismatch,'- Lifecycle: `'+JSON.stringify(lifecycleCounts)+'`','- Shadow-production mismatch: '+shadowMismatch,'- Flag OFF/ON behavior equivalent: '+flagOffEquivalent+' / '+flagOnEquivalent,'',
'## Required answers','','1. Production files modified: the three files listed above.','2. Flag OFF is exactly legacy-equivalent: '+flagOffEquivalent+'.','3. Flag ON adds only `liquidityEvidenceV1`: '+flagOnEquivalent+'.','4. All 1,423 WATCH enriched: '+(counts.WATCH_WITH_LIQUIDITY_EVIDENCE_V1===1423)+'.','5. Canonical identity baseline 1,331 preserved: '+(withCanonical===1331)+'.','6. Multiple-candidate baseline 1,149 preserved: '+(multiple===1149)+'.','7. Current primary identity match 1,423/1,423: '+(primaryMismatch===0)+'.','8. Lifecycle remains read-only observability: true.','9. Bias alignment remains read-only observability: true.','10. Reaction/attributed MSS/same-delivery displacement/follow-through in safe payload: false.','11. Future leak violations: '+future.length+'.','12. Full npm test passed: '+TESTS_PASSED+'.','13. Rollback requires only disabling `WATCH_LIQUIDITY_EVIDENCE_V1_ENABLED`: true.','14. P1 complete: '+pass+'.','',
'## Hard stop','','No lifecycle enforcement, Bias enforcement, ranking, causal primary, Reaction policy selection, scoring, or threshold work was started.'];fs.writeFileSync(path.join(OUT,'REPORT.md'),report.join('\n')+'\n');
console.log(JSON.stringify({output:OUT,status:pass?'PASS':'FAIL',counts:counts,acceptance:acceptance,readiness:readiness,runtimeSeconds:runtime},null,2));if(!pass)process.exitCode=1;
