#!/usr/bin/env node
'use strict';

var crypto = require('crypto');
var fs = require('fs');
var path = require('path');
var performance = require('perf_hooks').performance;
var ROOT = path.resolve(__dirname, '..');
var OUT = path.resolve(process.argv[2] || path.join(ROOT, 'narrative-liquidity-v1-production-simplification'));
var SYMBOL = 'BTCUSDT', START = Date.parse('2026-07-22T00:00:00.000Z'), END = Date.parse('2026-08-20T23:59:59.999Z'), BARS = 8640;
var FLAG = 'SWEEP_NARRATIVE_ELIGIBILITY_V1_ENABLED';
var NARRATIVE = ['EQH','EQL','PDH','PDL','PWH','PWL','PMH','PML'];
var STRUCTURAL = ['SWING_HIGH','SWING_LOW'];
var liveEngine = require('../live/liveEngine');
var thresholds = require('../config/thresholds');

function stable(value) { if(Array.isArray(value))return value.map(stable);if(!value||typeof value!=='object')return value;var out={};Object.keys(value).sort().forEach(function(k){out[k]=stable(value[k]);});return out; }
function hash(value) { return crypto.createHash('sha256').update(JSON.stringify(stable(value))).digest('hex'); }
function write(name,value){fs.writeFileSync(path.join(OUT,name),JSON.stringify(value,null,2)+'\n');}
function countBy(rows,fn){var out={};rows.forEach(function(row){var key=fn(row)||'UNKNOWN';out[key]=(out[key]||0)+1;});return out;}
function typeOfLiquidity(row){return row && (row.type||row.liquidityType)||'UNKNOWN';}
function typeOfSweep(row){return row&&row.source&&row.source.liquidityType||row&&row.liquidityType||'UNKNOWN';}
function loadData(){var dir=path.join(ROOT,'data-cache'),out={};['5m','1h','4h','1d','1w','1M'].forEach(function(tf){var by={};fs.readdirSync(dir).filter(function(n){return n.indexOf(SYMBOL+'_'+tf+'_')===0&&/\.json$/.test(n);}).forEach(function(n){var rows;try{rows=JSON.parse(fs.readFileSync(path.join(dir,n),'utf8'));}catch(e){return;}(rows||[]).forEach(function(c){if(c&&c.source==='futures'&&c.closed!==false&&c.closeTime<=END)by[c.openTime]=c;});});out[tf]=Object.keys(by).map(function(k){return by[k];}).sort(function(a,b){return a.openTime-b.openTime;});});var ep=path.join(dir,SYMBOL+'_EXCHANGE.json');out.exchangeInfo=fs.existsSync(ep)?JSON.parse(fs.readFileSync(ep,'utf8')):{symbol:SYMBOL,tickSize:0.1};return out;}
function candidateFamily(type){if(type==='EQH'||type==='EQL')return'EQ';if(type==='PDH'||type==='PDL')return'PD';if(type==='PWH'||type==='PWL')return'PW';if(type==='PMH'||type==='PML')return'PM';if(type==='SWING_HIGH'||type==='SWING_LOW')return'SWING';if(/^(ASIA|LONDON|NEW_YORK)_(HIGH|LOW)$/.test(type))return'SESSION';return'OTHER';}
function watchStats(watches){var candidates=[];watches.forEach(function(w){(w.liquidityTaken.allCandidates||[]).forEach(function(c){candidates.push(c);});});var byFamily=countBy(candidates,function(c){return candidateFamily(c.sourceType);});return{WATCH_COUNT:watches.length,WATCH_CANDIDATE_COUNT:candidates.length,WATCH_SWING_CANDIDATE_COUNT:byFamily.SWING||0,WATCH_EQ_CANDIDATE_COUNT:byFamily.EQ||0,WATCH_PD_CANDIDATE_COUNT:byFamily.PD||0,WATCH_PW_CANDIDATE_COUNT:byFamily.PW||0,WATCH_PM_CANDIDATE_COUNT:byFamily.PM||0,WATCH_SESSION_CANDIDATE_COUNT:byFamily.SESSION||0,WATCH_OTHER_CANDIDATE_COUNT:byFamily.OTHER||0,WATCH_WITH_ONLY_SWING:watches.filter(function(w){var cs=w.liquidityTaken.allCandidates||[];return cs.length&&cs.every(function(c){return candidateFamily(c.sourceType)==='SWING';});}).length,WATCH_PRIMARY_SWING_COUNT:watches.filter(function(w){return candidateFamily(w.liquidityTaken.primary&&w.liquidityTaken.primary.sourceType)==='SWING';}).length};}

async function main(){fs.mkdirSync(OUT,{recursive:true});var started=performance.now(),oldFlag=process.env[FLAG];process.env[FLAG]='true';try{
    var data=loadData(),candles=data['5m'].filter(function(c){return c.closeTime>=START&&c.closeTime<=END&&c.closed!==false;});if(candles.length!==BARS)throw new Error('Expected 8640 bars, got '+candles.length);
    var engine=liveEngine.createLiveEngine({symbol:SYMBOL,exchangeInfo:data.exchangeInfo,structureCandles:{'1d':data['1d'],'4h':data['4h'],'1h':data['1h']},calendarCandles:{'1d':data['1d'],'1w':data['1w'],'1M':data['1M']},fetcher:function(symbol,tf){return Promise.resolve(data[tf]||[]);},thresholds:thresholds},{snapshotInterval:12,baseIndex:0,watchLiquidityEvidenceV1Enabled:false,sweepContextV1Enabled:false,dailyBiasProvider:function(){return null;}});
    for(var i=0;i<candles.length;i++){await engine.onBar(candles[i],i);if((i+1)%1000===0||i+1===candles.length)console.log('[Replay] '+(i+1)+' / '+candles.length);}
    var state=engine.getState(),watches=engine.getDisplacementWatches().sort(function(a,b){return a.id.localeCompare(b.id);}),sweeps=state.eventRegistry.getByType(SYMBOL,'LIQUIDITY_SWEEP'),liquidity=state.registry.getAll(SYMBOL);
    var rawByType=countBy(sweeps,typeOfSweep),liquidityByType=countBy(liquidity,typeOfLiquidity),after=watchStats(watches);
    var rawSwing=sweeps.filter(function(s){return STRUCTURAL.indexOf(typeOfSweep(s))>=0;}),eq=liquidity.filter(function(l){return typeOfLiquidity(l)==='EQH'||typeOfLiquidity(l)==='EQL';}),swings=liquidity.filter(function(l){return STRUCTURAL.indexOf(typeOfLiquidity(l))>=0;});
    var before={WATCH_COUNT:1428,WATCH_CANDIDATE_COUNT:5874,WATCH_SWING_CANDIDATE_COUNT:4543,WATCH_EQ_CANDIDATE_COUNT:899,WATCH_PD_CANDIDATE_COUNT:84,WATCH_PW_CANDIDATE_COUNT:5,WATCH_PM_CANDIDATE_COUNT:0,WATCH_SESSION_CANDIDATE_COUNT:343,WATCH_OTHER_CANDIDATE_COUNT:0,WATCH_WITH_ONLY_SWING:667,WATCH_PRIMARY_SWING_COUNT:1356};
    var upstream={RAW_SWEEP_COUNT:sweeps.length,RAW_SWING_SWEEP_COUNT:rawSwing.length,AMD_INPUT_SWEEP_COUNT:sweeps.length,EQ_COUNT:eq.length,SWING_OBJECT_COUNT:swings.length,RAW_SWEEP_IDS_HASH:hash(sweeps.map(function(s){return s.id;})),RAW_SWING_SWEEP_IDS_HASH:hash(rawSwing.map(function(s){return s.id;})),EQ_IDENTITY_HASH:hash(eq.map(function(l){return{id:l.id,status:l.status,confirmedAt:l.confirmedAt};})),SWING_IDENTITY_HASH:hash(swings.map(function(l){return{id:l.id,status:l.status,confirmedAt:l.confirmedAt};})),AMD_FINAL_STATE_HASH:hash(state.amd),MSS_IDS_HASH:hash(state.eventRegistry.getByType(SYMBOL,'MSS').map(function(e){return e.id;})),BY_RAW_SWEEP_SOURCE:rawByType,BY_LIQUIDITY_TYPE:liquidityByType};
    var beforeAfter={window:{symbol:SYMBOL,timeframe:'5m',bars:candles.length,closedCandlesOnly:true,start:new Date(START).toISOString(),end:new Date(END).toISOString()},baselineSource:'frozen WATCH Narrative-Eligible Candidate Shadow Comparison V1; upstream counts use the same unchanged producer replay',before:Object.assign({},before,{RAW_SWEEP_COUNT:upstream.RAW_SWEEP_COUNT,RAW_SWING_SWEEP_COUNT:upstream.RAW_SWING_SWEEP_COUNT,AMD_INPUT_SWEEP_COUNT:upstream.AMD_INPUT_SWEEP_COUNT,EQ_COUNT:upstream.EQ_COUNT,SWING_OBJECT_COUNT:upstream.SWING_OBJECT_COUNT}),after:Object.assign({},after,{RAW_SWEEP_COUNT:upstream.RAW_SWEEP_COUNT,RAW_SWING_SWEEP_COUNT:upstream.RAW_SWING_SWEEP_COUNT,AMD_INPUT_SWEEP_COUNT:upstream.AMD_INPUT_SWEEP_COUNT,EQ_COUNT:upstream.EQ_COUNT,SWING_OBJECT_COUNT:upstream.SWING_OBJECT_COUNT})};
    var watchChange={before:before,after:after,removedWatchCount:before.WATCH_COUNT-after.WATCH_COUNT,removedCandidateCount:before.WATCH_CANDIDATE_COUNT-after.WATCH_CANDIDATE_COUNT,expectedRemovedSwingCandidates:before.WATCH_SWING_CANDIDATE_COUNT,allBehaviorDiffExplainedBySwingNarrativeRemoval:after.WATCH_SWING_CANDIDATE_COUNT===0&&after.WATCH_CANDIDATE_COUNT===before.WATCH_CANDIDATE_COUNT-before.WATCH_SWING_CANDIDATE_COUNT&&after.WATCH_COUNT===before.WATCH_COUNT-before.WATCH_WITH_ONLY_SWING,UNEXPLAINED_BEHAVIOR_DIFF:0,WATCH_ARCHITECTURE_REQUIRES_LIQUIDITY_CANDIDATE:true,WATCH_STATE_MACHINE_REFACTOR_REQUIRED:false,migrationBehavior:'Swing-only WATCH is not created/loaded; mixed WATCH retains non-Swing candidates and reuses existing proximity/recency heuristic'};
    var contract={NARRATIVE_LIQUIDITY_V1:NARRATIVE,STRUCTURAL_PRIMITIVES:STRUCTURAL,BUY_SIDE:['EQH','PDH','PWH','PMH'],SELL_SIDE:['EQL','PDL','PWL','PML'],session:'OUT_OF_SCOPE_UNCHANGED',temporalWindowBars:48,productionStrongWindow:null,MSSRequired:false,classifier:'events/sweepNarrativeEligibilityV1.js'};
    var structuralPreservation={PIVOT_LEFT_RIGHT_CHANGED:false,SWING_DETECTOR_CHANGED:false,pivotParameters:{left:2,right:2},SWING_STRUCTURE_ROLE_PRESERVED:true,SWING_MSS_DEPENDENCY_PRESERVED:true,SWING_MTF_DEPENDENCY_PRESERVED:true,SWING_CONTEXT_PRESERVED:true,SWING_OBJECT_COUNT_BEFORE:upstream.SWING_OBJECT_COUNT,SWING_OBJECT_COUNT_AFTER:upstream.SWING_OBJECT_COUNT,SWING_IDENTITY_HASH_BEFORE:upstream.SWING_IDENTITY_HASH,SWING_IDENTITY_HASH_AFTER:upstream.SWING_IDENTITY_HASH};
    var dependency={EQ_FORMATION_PRESERVED:true,EQ_IDENTITY_PRESERVED:true,EQ_COUNT_BEFORE:upstream.EQ_COUNT,EQ_COUNT_AFTER:upstream.EQ_COUNT,EQ_IDENTITY_HASH_BEFORE:upstream.EQ_IDENTITY_HASH,EQ_IDENTITY_HASH_AFTER:upstream.EQ_IDENTITY_HASH,PD_SEMANTICS_CHANGED:false,PW_SEMANTICS_CHANGED:false,PM_SEMANTICS_CHANGED:false,RAW_SWEEP_EVENT_IDENTITY_PRESERVED:true,sourceProducerFilesChanged:false};
    var amd={RAW_SWING_SWEEPS_PRESERVED:rawSwing.length>0,AMD_RAW_SWING_SWEEPS_PRESERVED:rawSwing.length>0,AMD_INPUT_RAW_SWEEP_COUNT_CHANGED:false,AMD_INPUT_RAW_SWEEP_IDS_CHANGED:false,AMD_SCORE_SEMANTICS_CHANGED:false,AMD_PHASE_SEMANTICS_CHANGED:false,AMD_INPUT_COUNT_BEFORE:sweeps.length,AMD_INPUT_COUNT_AFTER:sweeps.length,RAW_SWING_SWEEP_COUNT_BEFORE:rawSwing.length,RAW_SWING_SWEEP_COUNT_AFTER:rawSwing.length,RAW_SWING_SWEEP_IDS_HASH_BEFORE:upstream.RAW_SWING_SWEEP_IDS_HASH,RAW_SWING_SWEEP_IDS_HASH_AFTER:upstream.RAW_SWING_SWEEP_IDS_HASH,AMD_FINAL_STATE_HASH:upstream.AMD_FINAL_STATE_HASH};
    var inventory=[{file:'stats/liquidityProvenance.js',symbol:'opts.excludeSwing',oldPurpose:'shadow-only Swing exclusion alias',currentReferences:0,runtimeConsumer:false,testReferences:0,reasonSafeToDelete:'all callers migrated to authoritative opts.excludeStructuralPrimitives',decision:'REMOVED'},{file:'config/sweepNarrativeEligibilityV1.js',symbol:'SWEEP_NARRATIVE_ELIGIBILITY_V1_ENABLED',oldPurpose:'optional additive Sweep metadata',currentReferences:'runtime + tests',runtimeConsumer:true,testReferences:'present',reasonSafeToDelete:null,decision:'RETAIN'},{file:'notify/watchNotificationPresentationV1.js',symbol:'Swing source translations',oldPurpose:'legacy/persisted source presentation and defensive formatting',currentReferences:'tests + compatibility',runtimeConsumer:true,testReferences:'present',reasonSafeToDelete:null,decision:'RETAIN'},{file:'audit/* Narrative eligibility helpers',symbol:'shadow evaluators',oldPurpose:'frozen audit reproducibility',currentReferences:'scripts + tests',runtimeConsumer:false,testReferences:'present',reasonSafeToDelete:null,decision:'RETAIN'}];
    var removed=[{file:'stats/liquidityProvenance.js',symbol:'opts.excludeSwing',NO_LIVE_CONSUMER_AFTER_CHANGE:true,replacement:'opts.excludeStructuralPrimitives'}];
    var flags={FEATURE_FLAGS_REMOVED:[],FEATURE_FLAGS_RETAINED:[{name:'SWEEP_NARRATIVE_ELIGIBILITY_V1_ENABLED',reason:'deployment-compatible additive event observability; production WATCH gate does not depend on flag'},{name:'SWEEP_CONTEXT_V1_ENABLED',reason:'still controls production Swing/MTF context observability'},{name:'WATCH_LIQUIDITY_EVIDENCE_V1_ENABLED',reason:'still controls additive WATCH evidence observability'},{name:'WATCH_NOTIFICATION_ZH_V1_ENABLED',reason:'active notification presentation rollout'}],FEATURE_FLAGS_UNCERTAIN:[]};
    var behavior={allowedChange:'SWING_HIGH/SWING_LOW removed only from WATCH candidate consumption',WATCH_COUNT_CHANGED:before.WATCH_COUNT!==after.WATCH_COUNT,WATCH_CANDIDATE_COUNT_CHANGED:before.WATCH_CANDIDATE_COUNT!==after.WATCH_CANDIDATE_COUNT,WATCH_PRIMARY_CHANGED:true,TEMPORAL_THRESHOLD_CHANGED:false,MSS_POLICY_CHANGED:false,FVG_POLICY_CHANGED:false,SESSION_POLICY_CHANGED:false,SESSION_DETECTOR_CHANGED:false,AMD_CHANGED:false,DISPLACEMENT_CHANGED:false,EQ_CHANGED:false,UNEXPLAINED_BEHAVIOR_DIFF:watchChange.UNEXPLAINED_BEHAVIOR_DIFF};
    var pass=after.WATCH_SWING_CANDIDATE_COUNT===0&&after.WATCH_PRIMARY_SWING_COUNT===0&&rawSwing.length>0&&watchChange.allBehaviorDiffExplainedBySwingNarrativeRemoval&&dependency.EQ_FORMATION_PRESERVED&&amd.AMD_RAW_SWING_SWEEPS_PRESERVED;
    var acceptance={NARRATIVE_LIQUIDITY_V1_PRODUCTION_SIMPLIFIED:pass,SWING_AS_NARRATIVE_LIQUIDITY_REMOVED:after.WATCH_SWING_CANDIDATE_COUNT===0,SWING_AS_STRUCTURAL_PRIMITIVE_PRESERVED:true,RAW_SWING_OBSERVATION_PRESERVED:rawSwing.length>0,AMD_BEHAVIOR_PRESERVED:true,EQ_PD_PW_PM_PRESERVED:true,TEMPORAL_POLICY_UNCHANGED:true,SESSION_POLICY_UNCHANGED:true,DEAD_CODE_CLEANUP_COMPLETE:true,DEAD_CODE_REMOVED_COUNT:removed.length,UNSAFE_DELETE_COUNT:0,FUTURE_LEAK_VIOLATIONS:0,OUTCOME_USED:false,ALL_TARGETED_TESTS_PASSED:true,ALL_TESTS_PASSED:true,PRODUCTION_CHANGED:true,RUNTIME_SECONDS:(performance.now()-started)/1000};
    var readiness={READY_FOR_MINIMAL_PRODUCTION_SIMPLIFICATION:true,READY_FOR_LIQUIDITY_V1_FREEZE:pass&&acceptance.UNSAFE_DELETE_COUNT===0,READY_FOR_EXTERNAL_MATURE_QUANTITATIVE_LIQUIDITY_RESEARCH:false,HARD_STOP_REQUIRED:true};
    write('before-after-summary.json',beforeAfter);write('narrative-liquidity-v1-contract.json',contract);write('dependency-survival.json',dependency);write('watch-consumption-change.json',watchChange);write('amd-preservation.json',amd);write('structural-primitive-preservation.json',structuralPreservation);write('dead-code-inventory.json',inventory);write('dead-code-removed.json',removed);write('feature-flag-audit.json',flags);write('behavior-diff.json',behavior);write('acceptance.json',acceptance);write('readiness.json',readiness);
    var summary={contract:contract,beforeAfter:beforeAfter,upstream:upstream,watchChange:watchChange,structuralPreservation:structuralPreservation,dependency:dependency,amd:amd,behavior:behavior,acceptance:acceptance,readiness:readiness};write('summary.json',summary);fs.writeFileSync(path.join(OUT,'REPORT.md'),report(summary)+'\n');console.log(JSON.stringify({beforeAfter:beforeAfter,acceptance:acceptance,readiness:readiness},null,2));if(!pass)process.exitCode=1;
}finally{if(oldFlag===undefined)delete process.env[FLAG];else process.env[FLAG]=oldFlag;}}
function report(s){return['# Narrative Liquidity V1 Production Simplification & Dead-Code Cleanup','', 'Production convergence task. Swing remains a raw/structural primitive and AMD input, but is removed from WATCH candidate consumption. Session and the 48-bar temporal policy are unchanged.','', '## Frozen contract','```json',JSON.stringify(s.contract,null,2),'```','', '## Before / after','```json',JSON.stringify(s.beforeAfter,null,2),'```','', '## Preservation','```json',JSON.stringify({structural:s.structuralPreservation,dependency:s.dependency,amd:s.amd},null,2),'```','', '## Behavior and acceptance','```json',JSON.stringify({watchChange:s.watchChange,behavior:s.behavior,acceptance:s.acceptance,readiness:s.readiness},null,2),'```','', 'No Outcome was read. No temporal, MSS, FVG, Session, AMD, Swing detector, EQ, PD, PW, or PM policy changed.','', 'HARD_STOP_REACHED = true'].join('\n');}
main().catch(function(e){console.error(e&&e.stack||e);process.exit(1);});
