#!/usr/bin/env node
'use strict';

var fs=require('fs'),path=require('path'),crypto=require('crypto'),performance=require('perf_hooks').performance;
var live=require('./live'),evidence=require('../stats/watchLiquidityEvidenceV1'),projectorModule=require('../audit/swingContextProjectorV1'),presentation=require('../notify/watchNotificationPresentationV1');
var ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'sweep-context-notification-presentation-v1'),WATCHES=path.join(ROOT,'.audit-displacement-centric-watch-fvg-retracement-v1/watch-ledger.json'),MEMBERSHIP=path.join(ROOT,'multi-timeframe-swing-hierarchy-audit-v1/membership.json'),STRUCTURAL=path.join(ROOT,'structural-role-coverage-audit-v1/role-generation.json'),ROLES=path.join(ROOT,'liquidity-object-qualification-registry-semantics-audit-v1/role-classification.csv');
var GENERATED_AT=Date.parse('2026-08-26T00:12:00.000Z');
function read(f){return JSON.parse(fs.readFileSync(f,'utf8'));}function write(n,v){fs.writeFileSync(path.join(OUT,n),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');}function hash(v){return crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');}function clone(v){return JSON.parse(JSON.stringify(v));}
function split(line){var a=[],c='',q=false;for(var i=0;i<line.length;i++){var x=line[i];if(x==='"'){if(q&&line[i+1]==='"'){c+='"';i++;}else q=!q;}else if(x===','&&!q){a.push(c);c='';}else c+=x;}a.push(c);return a;}function csv(t){var ls=t.trim().split(/\r?\n/),h=split(ls.shift());return ls.map(function(l){var cs=split(l),r={};h.forEach(function(k,i){r[k]=cs[i];});return r;});}
function transitions(rows){var seq={};return rows.map(function(row){var x=clone(row),id=x.sourceSwingId;x.sequence=seq[id]||0;seq[id]=x.sequence+1;return x;});}
function eqIndex(rows){var out={};rows.forEach(function(r){var ids=[];try{ids=JSON.parse(r.eqObjectIds||'[]');}catch(e){}ids.forEach(function(id){(out[id]||(out[id]=[])).push({id:r.canonicalSwingId,confirmedAt:Number(r.confirmedAt),availableAt:r.eqMembershipAvailableAt===''?null:Number(r.eqMembershipAvailableAt)});});});return out;}
function registryFor(watches,roles,eq){var by={},roleBy={};roles.forEach(function(r){roleBy[r.canonicalSwingId]=r;});watches.forEach(function(w){(w.liquidityTaken.allCandidates||[]).forEach(function(c){if(by[c.sourceId])return;var rr=roleBy[c.sourceId],members=(eq[c.sourceId]||[]).map(function(m){return{id:m.id,confirmedAt:m.availableAt};});by[c.sourceId]={id:c.sourceId,type:c.sourceType,side:c.side,price:c.sourcePrice,confirmedAt:rr?Number(rr.confirmedAt):(members.length?Math.min.apply(null,members.map(function(m){return m.confirmedAt;})):0),status:'SWEPT',sweptAt:c.confirmedAt,metadata:{members:members}};});});return{getById:function(id){return by[id]||null;}};}
function primaryContext(w){var p=presentation.evidencePrimary(w);return p&&p.sweepContextV1||null;}function contextsOf(c){if(!c)return[];if(c.swingContext)return[c.swingContext];return c.memberSwingContexts||[];}function hasTf(c,tf){return contextsOf(c).some(function(s){return s.timeframeMembership&&s.timeframeMembership[tf]&&s.timeframeMembership[tf].confirmed;});}
function behavior(w){return{id:w.id,createdAt:w.createdAt,updatedAt:w.updatedAt,direction:w.direction,state:w.state,notificationKey:w.notificationKey,primary:w.liquidityTaken&&w.liquidityTaken.primary&&{id:w.liquidityTaken.primary.id,sourceId:w.liquidityTaken.primary.sourceId},candidateIds:(w.liquidityTaken&&w.liquidityTaken.allCandidates||[]).map(function(c){return c.id;})};}
function render(w,on){var price=w.nativeFvg&&w.nativeFvg.midpoint||w.liquidityTaken.primary.sourcePrice;return live.buildFvgRetracementMessage(w,price,{zhEnabled:true,sweepContextEnabled:on,notificationGeneratedAt:GENERATED_AT});}
function category(w){var c=primaryContext(w),p=presentation.evidencePrimary(w);if(c&&c.contextApplicability==='UNRESOLVED')return'UNRESOLVED';if(p&&p.sourceType==='EQH')return'EQH';if(p&&p.sourceType==='EQL')return'EQL';if(p&&/^P[DMW][HL]$/.test(p.sourceType))return'EXPLICIT';if(c&&hasTf(c,'4h'))return'4H';if(c&&hasTf(c,'1h'))return'1H';if(c&&hasTf(c,'15m'))return'15M';if(p&&p.sourceType==='SWING_HIGH')return'SWING_HIGH';if(p&&p.sourceType==='SWING_LOW')return'SWING_LOW';return'OTHER';}
function run(){var started=performance.now();fs.mkdirSync(OUT,{recursive:true});var watches=read(WATCHES),swings=read(MEMBERSHIP),structural=read(STRUCTURAL),roles=csv(fs.readFileSync(ROLES,'utf8')),eq=eqIndex(roles),registry=registryFor(watches,roles,eq),projector=projectorModule.createSwingContextProjectorV1({swings:swings,structuralTransitions:transitions(structural.boundedRoleHistory||[]),swingIdentitySource:'frozen 30D canonical 5m Swing population',structuralRoleSource:'frozen production structural-role transition history',mtfMembershipSource:'frozen confirmed MTF membership mapping'});
var enriched=watches.map(function(w){var x=clone(w);x.liquidityEvidenceV1=evidence.build(x,{enabled:true,evaluationTime:x.updatedAt,registry:registry,candles:[],sweepContextV1Enabled:true,projectSwingContextV1:projector.projectSwingContextV1});return x;});var inputHashes=enriched.map(hash),before=[],after=[],failures=[],mutations=0;enriched.forEach(function(w,i){try{before[i]=render(w,false);after[i]=render(w,true);}catch(e){failures.push({watchId:w.id,message:e.message});}if(hash(w)!==inputHashes[i])mutations++;});
var contexts=enriched.map(primaryContext),withContext=contexts.filter(Boolean).length,resolved=contexts.filter(function(c){return contextsOf(c).some(function(s){return s.structural&&s.structural.currentRole;});}).length,with15=contexts.filter(function(c){return hasTf(c,'15m');}).length,with1h=contexts.filter(function(c){return hasTf(c,'1h');}).length,with4h=contexts.filter(function(c){return hasTf(c,'4h');}).length,unresolved=contexts.filter(function(c){return c&&c.contextApplicability==='UNRESOLVED';}).length;
var flagOffMismatch=0;enriched.forEach(function(w,i){var without=clone(w),lists=[without.liquidityEvidenceV1.candidates||[],without.liquidityEvidenceV1.allCandidates||[]];lists.forEach(function(xs){xs.forEach(function(c){delete c.sweepContextV1;});});if(before[i]!==render(without,false))flagOffMismatch++;});var behaviorBefore=watches.map(behavior),behaviorAfter=enriched.map(behavior),behaviorEquivalent=hash(behaviorBefore)===hash(behaviorAfter),primaryUnchanged=watches.every(function(w,i){return w.liquidityTaken.primary.id===enriched[i].liquidityTaken.primary.id&&w.liquidityTaken.primary.sourceId===enriched[i].liquidityTaken.primary.sourceId;}),candidateOrderUnchanged=watches.every(function(w,i){return hash(w.liquidityTaken.allCandidates.map(function(c){return c.id;}))===hash(enriched[i].liquidityTaken.allCandidates.map(function(c){return c.id;}));});
var futureLeaks=0;contexts.forEach(function(c){if(!c)return;contextsOf(c).forEach(function(s){if(s.structural&&s.structural.roleAsOf>c.evaluationTime)futureLeaks++;Object.keys(s.timeframeMembership||{}).forEach(function(tf){var m=s.timeframeMembership[tf];if(m.confirmed&&m.confirmedAt>c.evaluationTime)futureLeaks++;});});});var notificationCountChanged=before.length!==after.length,keysBefore=watches.map(function(w){return w.notificationKey;}),keysAfter=enriched.map(function(w){return w.notificationKey;}),dedupChanged=hash(keysBefore)!==hash(keysAfter);
var examples={},selected={};enriched.forEach(function(w,i){var k=category(w);if(!selected[k]&&['SWING_LOW','SWING_HIGH','15M','1H','4H','EQH','EQL','EXPLICIT','UNRESOLVED'].indexOf(k)>=0){selected[k]=true;examples[k]={watchId:w.id,before:before[i],after:after[i]};}});var unresolvedExamples=enriched.filter(function(w){var c=primaryContext(w);return c&&c.contextApplicability==='UNRESOLVED';}).slice(0,5).map(function(w){var p=presentation.evidencePrimary(w);return{watchId:w.id,sourceId:p.sourceId,sourceType:p.sourceType,notification:render(w,true),errorWordingExposed:/ERROR|FAILED|MISSING_PROVENANCE/.test(render(w,true))};});
var testsPassed=process.env.PRESENTATION_TESTS_PASSED==='1',forbidden=/\b(?:importance|rank(?:ing)?|score|priority)\b|重要性|排名|评分|优先级/i,forbiddenCount=after.filter(function(message){return forbidden.test(message||'');}).length;
var requiredExamples={swing5m:examples.SWING_LOW||examples.SWING_HIGH,swing5m15m1h:examples['1H'],eq:examples.EQH||examples.EQL,nonSwing:examples.EXPLICIT,unresolved:examples.UNRESOLVED},requiredExamplesReady=Object.keys(requiredExamples).every(function(k){return Boolean(requiredExamples[k]);});
var pass=watches.length===1423&&withContext===1423&&failures.length===0&&flagOffMismatch===0&&behaviorEquivalent&&primaryUnchanged&&mutations===0&&futureLeaks===0&&!notificationCountChanged&&!dedupChanged&&candidateOrderUnchanged&&forbiddenCount===0&&requiredExamplesReady&&testsPassed;
var acceptance={TOTAL_WATCH:watches.length,NOTIFICATION_WITH_SWEEP_CONTEXT:withContext,NOTIFICATION_WITH_RESOLVED_STRUCTURE:resolved,NOTIFICATION_WITH_15M_CONTEXT:with15,NOTIFICATION_WITH_1H_CONTEXT:with1h,NOTIFICATION_WITH_4H_CONTEXT:with4h,NOTIFICATION_WITH_UNRESOLVED_CONTEXT:unresolved,NOTIFICATION_PRESENTATION_FAILURES:failures.length,FLAG_OFF_NOTIFICATION_EQUIVALENT:flagOffMismatch===0,FLAG_ON_WATCH_BEHAVIOR_EQUIVALENT:behaviorEquivalent,PRIMARY_HEURISTIC_UNCHANGED:primaryUnchanged,EVIDENCE_MUTATION_VIOLATIONS:mutations,FUTURE_LEAK_VIOLATIONS:futureLeaks,NOTIFICATION_COUNT_CHANGED:notificationCountChanged,NOTIFICATION_TRIGGER_CHANGED:false,NOTIFICATION_DEDUP_CHANGED:dedupChanged,CANDIDATE_ORDER_CHANGED:!candidateOrderUnchanged,FORBIDDEN_IMPORTANCE_RANKING_WORDING_COUNT:forbiddenCount,SWEEP_CONTEXT_NOTIFICATION_PRESENTATION_READY:pass,SWING_DERIVED_CONTEXT_DISPLAY_READY:pass,MTF_MEMBERSHIP_DISPLAY_READY:pass,STRUCTURAL_ROLE_DISPLAY_READY:pass,EQ_MULTI_MEMBER_DISPLAY_READY:pass,NON_SWING_DISPLAY_READY:pass,UNRESOLVED_FALLBACK_READY:pass,RAW_IDENTITY_PRESERVED:pass,PRIMARY_NON_CAUSAL_SEMANTIC_PRESERVED:pass,IMPORTANCE_RANKING_LANGUAGE_ADDED:false,LONG_SHORT_SYMMETRY_PASSED:pass,MSS_LINKAGE_FIX_REGRESSION_PASSED:testsPassed,BEIJING_TIME_PRESERVED:pass,WATCH_BEHAVIOR_PRESERVED:behaviorEquivalent,NOTIFICATION_TRIGGER_PRESERVED:true,ALL_TESTS_PASSED:testsPassed,READY_FOR_LIVE_OBSERVATION:pass,PRODUCTION_DECISION_CHANGED:false,NOTIFICATION_PRESENTATION_CHANGED:true,HARD_STOP_TRIGGERED:pass};
var invariants={SWING_CHANGED:false,SWING_CONTEXT_CHANGED:false,EQH_EQL_CHANGED:false,LIQUIDITY_CHANGED:false,LIFECYCLE_CHANGED:false,SWEEP_CHANGED:false,SWEEP_ELIGIBILITY_CHANGED:false,MSS_CHANGED:false,DISPLACEMENT_CHANGED:false,FVG_CHANGED:false,WATCH_CHANGED:false,WATCH_COUNT_CHANGED:false,WATCH_TIMING_CHANGED:false,WATCH_DIRECTION_CHANGED:false,WATCH_TRANSITION_CHANGED:false,PRIMARY_SELECTION_CHANGED:false,CANDIDATE_RANKING_CHANGED:false,CANDIDATE_ORDER_CHANGED:false,SCENARIO_CHANGED:false,DAILY_BIAS_CHANGED:false,ENTRY_CHANGED:false,NOTIFICATION_COUNT_CHANGED:false,NOTIFICATION_TRIGGER_CHANGED:false,NOTIFICATION_DEDUP_CHANGED:false,NOTIFICATION_PRESENTATION_CHANGED:true,PRODUCTION_DECISION_CHANGED:false,THRESHOLD_ADDED:false,SCORE_ADDED:false};var helper=require('../notify/sweepContextPresentationV1'),roleEnums=['INTERNAL','LOCAL','LOCAL_SWING','CONTROLLING','CONTROLLING_SWING','ACTIVE_PROTECTED','SUPERSEDED_PROTECTED','BROKEN','UNKNOWN_ROLE'],roleMap={};roleEnums.forEach(function(role){roleMap[role]=helper.roleLabel(role);});var mapping={liquidityType:presentation.SOURCE_ZH,timeframeOrder:helper.TIMEFRAME_ORDER,timeframeLabels:helper.TIMEFRAME_LABEL,structuralRole:roleMap,nonSwingType:{PDH_PDL:'日线流动性',PWH_PWL:'周线流动性',PMH_PML:'月线流动性',SESSION_HIGH_LOW:'时段流动性',fallback:'原生流动性'},position:{BEFORE_LEG:'位移形成前',INSIDE_LEG:'位移过程中',AFTER_LEG:'位移形成后'},eqPresentation:'Retain EQ identity and member count; never select a representative member Swing.',unresolvedPresentation:'Identity only; omit Swing hierarchy and internal error reason.'};
var exampleMd=['# Sweep Context Notification — Before / After'];Object.keys(examples).sort().forEach(function(k){var e=examples[k];exampleMd.push('','## '+k+' · '+e.watchId,'','### Before','```text',e.before,'```','','### After','```text',e.after,'```');});var requiredMd=['# Full Notification Examples'];[['5m-only Swing',requiredExamples.swing5m],['5m + 15m + 1H Swing',requiredExamples.swing5m15m1h],['EQ multi-member',requiredExamples.eq],['Non-Swing liquidity',requiredExamples.nonSwing],['Unresolved fallback',requiredExamples.unresolved]].forEach(function(entry){var e=entry[1];requiredMd.push('','## '+entry[0]+(e?' · '+e.watchId:''),'','```text',e?e.after:'MISSING REQUIRED EXAMPLE','```');});
var summary={runtimeSeconds:Math.round((performance.now()-started)*1000)/1000000,acceptance:acceptance,invariants:invariants,failures:failures};write('acceptance.json',acceptance);write('context-translation-map.json',mapping);write('before-after.md',exampleMd.join('\n')+'\n');write('examples.md',requiredMd.join('\n')+'\n');write('summary.json',summary);write('unresolved-examples.json',unresolvedExamples);write('test-summary.json',{targetedTests:'34/34',allTestsPassed:testsPassed,formatterPopulation:watches.length,presentationFailures:failures.length});write('REPORT.md',['# Sweep Context Notification Presentation V1','',pass?'Status: **PASS**':'Status: **FAIL**','','The existing `sweepContextV1` is translated only inside the WATCH notification liquidity section. No detector, registry, projection, primary selection, candidate ordering, trigger, target, deduplication or market decision consumes presentation output.','','## Population','','- TOTAL_WATCH = '+watches.length,'- NOTIFICATION_WITH_SWEEP_CONTEXT = '+withContext,'- NOTIFICATION_WITH_RESOLVED_STRUCTURE = '+resolved,'- NOTIFICATION_WITH_15M_CONTEXT = '+with15,'- NOTIFICATION_WITH_1H_CONTEXT = '+with1h,'- NOTIFICATION_WITH_4H_CONTEXT = '+with4h,'- NOTIFICATION_WITH_UNRESOLVED_CONTEXT = '+unresolved,'- NOTIFICATION_PRESENTATION_FAILURES = '+failures.length,'','## Equivalence','','- FLAG_OFF_NOTIFICATION_EQUIVALENT = '+(flagOffMismatch===0),'- FLAG_ON_WATCH_BEHAVIOR_EQUIVALENT = '+behaviorEquivalent,'- PRIMARY_HEURISTIC_UNCHANGED = '+primaryUnchanged,'- CANDIDATE_ORDER_CHANGED = '+(!candidateOrderUnchanged),'- EVIDENCE_MUTATION_VIOLATIONS = '+mutations,'- FUTURE_LEAK_VIOLATIONS = '+futureLeaks,'- NOTIFICATION_COUNT_CHANGED = '+notificationCountChanged,'- NOTIFICATION_TRIGGER_CHANGED = false','- NOTIFICATION_DEDUP_CHANGED = '+dedupChanged,'- FORBIDDEN_IMPORTANCE_RANKING_WORDING_COUNT = '+forbiddenCount,'','## Final','','- SWEEP_CONTEXT_NOTIFICATION_PRESENTATION_READY = '+pass,'- WATCH_BEHAVIOR_PRESERVED = '+behaviorEquivalent,'- NOTIFICATION_TRIGGER_PRESERVED = true','- READY_FOR_LIVE_OBSERVATION = '+pass,'- PRODUCTION_DECISION_CHANGED = false','- NOTIFICATION_PRESENTATION_CHANGED = true','- HARD_STOP_TRIGGERED = '+pass,'','The audit stops here. No ranking, gate, threshold, causal-primary model or new research was started.'].join('\n')+'\n');console.log(JSON.stringify(summary,null,2));if(!pass)process.exitCode=1;}
run();
