#!/usr/bin/env node
'use strict';

var crypto = require('crypto');
var fs = require('fs');
var path = require('path');
var performance = require('perf_hooks').performance;
var projectorModule = require('../audit/swingContextProjectorV1');

var ROOT = path.resolve(__dirname, '..');
var OUT = path.resolve(process.argv[2] || path.join(ROOT, 'swing-context-projection-v1'));
var MEMBERSHIP_FILE = path.join(ROOT, 'multi-timeframe-swing-hierarchy-audit-v1', 'membership.json');
var STRUCTURAL_FILE = path.join(ROOT, 'structural-role-coverage-audit-v1', 'role-generation.json');
var SWEEP_FILE = path.join(ROOT, 'liquidity-object-qualification-registry-semantics-audit-v1', 'role-classification.csv');
var START = Date.parse('2026-07-22T00:00:00.000Z');
var END = Date.parse('2026-08-20T23:59:59.999Z');
var PRODUCTION_FILES = ['structure/pivotDetector.js', 'liquidity/swingLiquidity.js', 'structure/structuralProvenance5m.js', 'liquidity/liquidityRegistry.js', 'liquidity/liquidityLifecycle.js', 'events/sweepEventAdapter.js', 'events/mssSignalDetector.js'];

function readJson(file) { return JSON.parse(fs.readFileSync(file, 'utf8')); }
function writeJson(name, value) { fs.writeFileSync(path.join(OUT, name), JSON.stringify(value, null, 2) + '\n'); }
function iso(value) { return value == null ? null : new Date(value).toISOString(); }
function fileHash(file) { return crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT, file))).digest('hex'); }
function hashes() { var out = {}; PRODUCTION_FILES.forEach(function (file) { out[file] = fileHash(file); }); return out; }
function countBy(rows, fn) { var out = {}; (rows || []).forEach(function (row) { var key = String(fn(row)); out[key] = (out[key] || 0) + 1; }); return out; }
function splitCsv(line) { var out = [], cell = '', quoted = false; for (var i = 0; i < line.length; i += 1) { var ch = line[i]; if (ch === '"') { if (quoted && line[i + 1] === '"') { cell += '"'; i += 1; } else quoted = !quoted; } else if (ch === ',' && !quoted) { out.push(cell); cell = ''; } else cell += ch; } out.push(cell); return out; }
function parseCsv(text) { var lines = text.trim().split(/\r?\n/), headers = splitCsv(lines.shift()); return lines.map(function (line) { var cells = splitCsv(line), row = {}; headers.forEach(function (header, index) { row[header] = cells[index]; }); return row; }); }
function csvCell(value) { var text = value == null ? '' : (typeof value === 'object' ? JSON.stringify(value) : String(value)); return /[",\n]/.test(text) ? '"' + text.replace(/"/g, '""') + '"' : text; }
function writeCsv(name, rows) { var columns = []; rows.forEach(function (row) { Object.keys(row).forEach(function (key) { if (columns.indexOf(key) < 0) columns.push(key); }); }); fs.writeFileSync(path.join(OUT, name), columns.join(',') + '\n' + rows.map(function (row) { return columns.map(function (column) { return csvCell(row[column]); }).join(','); }).join('\n') + '\n'); }
function deterministicShuffle(rows) { var odd = [], even = []; rows.forEach(function (row, index) { (index % 2 ? odd : even).push(row); }); return odd.reverse().concat(even.reverse()); }
function enrichSequence(history) { var sequence = {}; return (history || []).map(function (entry) { var copy = JSON.parse(JSON.stringify(entry)), id = copy.sourceSwingId; copy.sequence = sequence[id] || 0; sequence[id] = copy.sequence + 1; return copy; }); }
function frozenSweeps() { return parseCsv(fs.readFileSync(SWEEP_FILE, 'utf8')).filter(function (row) { return row.directSweepParticipation === 'true' && row.sweptAt !== ''; }).map(function (row) { return { swingId: row.canonicalSwingId, confirmedAt: Number(row.sweptAt), source: 'frozen production liquidity lifecycle' }; }).sort(function (a, b) { return a.confirmedAt - b.confirmedAt || a.swingId.localeCompare(b.swingId); }); }
function createProjector(swings, transitions) { return projectorModule.createSwingContextProjectorV1({ swings: swings, structuralTransitions: transitions, swingIdentitySource: 'Multi-Timeframe Swing Hierarchy Audit V1 frozen canonical 5m population', structuralRoleSource: 'production structural5m.swingBySourceId history captured by Structural Role Coverage Audit V1', mtfMembershipSource: 'validated confirmed MTF identity mapping from Multi-Timeframe Swing Hierarchy Audit V1' }); }
function schema() { return { '$schema': 'https://json-schema.org/draft/2020-12/schema', '$id': 'SwingContextV1', title: 'SwingContextV1', type: 'object', additionalProperties: false, required: ['schemaVersion', 'canonicalSwingId', 'side', 'price', 'occurredAt', 'confirmedAt', 'structural', 'timeframeMembership', 'evaluationTime', 'provenance'], properties: { schemaVersion: { const: 'SwingContextV1' }, canonicalSwingId: { type: 'string' }, side: { enum: ['HIGH', 'LOW'] }, price: { type: 'number' }, occurredAt: { type: 'number' }, confirmedAt: { type: 'number' }, structural: { type: 'object', additionalProperties: false, required: ['currentRole', 'currentStatus', 'roleAsOf', 'provenance'], properties: { currentRole: { type: 'string' }, currentStatus: { type: 'string' }, roleAsOf: { type: 'number' }, provenance: { type: 'object' } } }, timeframeMembership: { type: 'object', additionalProperties: false, required: ['5m', '15m', '1h', '4h'], properties: { '5m': { '$ref': '#/$defs/membership' }, '15m': { '$ref': '#/$defs/membership' }, '1h': { '$ref': '#/$defs/membership' }, '4h': { '$ref': '#/$defs/membership' } } }, evaluationTime: { type: 'number' }, provenance: { type: 'object' } }, '$defs': { membership: { type: 'object', additionalProperties: false, required: ['confirmed', 'swingId', 'occurredAt', 'confirmedAt', 'provenance'], properties: { confirmed: { type: 'boolean' }, swingId: { type: ['string', 'null'] }, occurredAt: { type: ['number', 'null'] }, confirmedAt: { type: ['number', 'null'] }, provenance: { type: ['object', 'null'] } } } } }; }
function contextSummary(contexts) { return { count: contexts.length, structuralRoleDistribution: countBy(contexts, function (context) { return context.structural.currentRole; }), membershipCounts: { '5m': contexts.filter(function (c) { return c.timeframeMembership['5m'].confirmed; }).length, '15m': contexts.filter(function (c) { return c.timeframeMembership['15m'].confirmed; }).length, '1h': contexts.filter(function (c) { return c.timeframeMembership['1h'].confirmed; }).length, '4h': contexts.filter(function (c) { return c.timeframeMembership['4h'].confirmed; }).length } }; }
function selectOne(rows, category, predicate) { return rows.filter(predicate).sort(function (a, b) { return projectorModule.hash(category + a.canonicalSwingId).localeCompare(projectorModule.hash(category + b.canonicalSwingId)); })[0] || null; }
function examples(projector, contexts, transitions, sweeps) {
    var out = [];
    function add(category, value) { out.push({ category: category, value: value }); }
    add('5M_ONLY_INTERNAL', selectOne(contexts, '5M_ONLY_INTERNAL', function (c) { return c.structural.currentRole === 'INTERNAL' && !c.timeframeMembership['15m'].confirmed; }));
    add('15M_MEMBER', selectOne(contexts, '15M_MEMBER', function (c) { return c.timeframeMembership['15m'].confirmed && !c.timeframeMembership['1h'].confirmed; }));
    add('1H_MEMBER', selectOne(contexts, '1H_MEMBER', function (c) { return c.timeframeMembership['1h'].confirmed && !c.timeframeMembership['4h'].confirmed; }));
    add('4H_MEMBER', selectOne(contexts, '4H_MEMBER', function (c) { return c.timeframeMembership['4h'].confirmed; }));
    var activeCandidates = transitions.filter(function (t) { return t.role === 'ACTIVE_PROTECTED'; }).map(function (t) { return projector.projectSwingContextV1({ canonicalSwingId: t.sourceSwingId, evaluationTime: t.confirmedAt }); }).filter(function (c) { return c && c.structural.currentRole === 'ACTIVE_PROTECTED'; });
    add('ACTIVE_PROTECTED_AS_OF', selectOne(activeCandidates, 'ACTIVE_PROTECTED_AS_OF', function () { return true; }));
    var broken = transitions.filter(function (t) { return t.role === 'BROKEN'; }).sort(function (a, b) { return projectorModule.hash('BROKEN' + a.sourceSwingId).localeCompare(projectorModule.hash('BROKEN' + b.sourceSwingId)); })[0];
    add('BROKEN_BEFORE_AFTER', broken ? { canonicalSwingId: broken.sourceSwingId, transitionAt: broken.confirmedAt, before: projector.projectSwingContextV1({ canonicalSwingId: broken.sourceSwingId, evaluationTime: broken.confirmedAt - 1 }), after: projector.projectSwingContextV1({ canonicalSwingId: broken.sourceSwingId, evaluationTime: broken.confirmedAt }) } : null);
    add('STRUCTURAL_AND_MTF', selectOne(contexts, 'STRUCTURAL_AND_MTF', function (c) { return c.structural.currentRole !== 'LOCAL_SWING' && c.timeframeMembership['1h'].confirmed; }));
    var sweep = sweeps.sort(function (a, b) { return projectorModule.hash('SWEEP' + a.swingId).localeCompare(projectorModule.hash('SWEEP' + b.swingId)); })[0];
    add('SWEEP_TIME_CONTEXT', sweep ? { sweep: sweep, context: projector.projectSwingContextV1({ canonicalSwingId: sweep.swingId, evaluationTime: sweep.confirmedAt }) } : null);
    return out;
}
function report(summary) { var r = summary.readiness, s = summary.sweepContextShadow; return ['# Swing Context Projection V1', '', '## Result', '', '`SwingContextV1` is a read-only, evaluation-time projection over two independent dimensions: production structural-role history and confirmed MTF membership. It does not create a second authoritative Swing registry and does not copy mutable context into liquidity objects.', '', '## Source-of-truth resolution', '', '- Canonical 5m Swing identities resolved: ' + summary.population.TOTAL_SWINGS + ' / ' + summary.population.TOTAL_SWINGS, '- Structural histories resolved: ' + summary.population.STRUCTURAL_CONTEXT_RESOLVED + ' / ' + summary.population.TOTAL_SWINGS, '- Structural unresolved: ' + summary.population.STRUCTURAL_CONTEXT_UNRESOLVED, '- MTF final membership source: validated 15m / 1H / 4H identity mapping; visibility is gated by each HTF `confirmedAt`.', '', '## Sweep-time shadow', '', '- SWEEPS_WITH_SWING_CONTEXT = ' + s.SWEEPS_WITH_SWING_CONTEXT, '- SWEEPS_WITH_STRUCTURAL_CONTEXT = ' + s.SWEEPS_WITH_STRUCTURAL_CONTEXT, '- SWEEPS_WITH_15M_MEMBERSHIP = ' + s.SWEEPS_WITH_15M_MEMBERSHIP, '- SWEEPS_WITH_1H_MEMBERSHIP = ' + s.SWEEPS_WITH_1H_MEMBERSHIP, '- SWEEPS_WITH_4H_MEMBERSHIP = ' + s.SWEEPS_WITH_4H_MEMBERSHIP, '- UNRESOLVED_CONTEXT = ' + s.UNRESOLVED_CONTEXT, '', 'Sweep, WATCH, ranking, primary identity and notification were not changed.', '', '## Answers', '', '1. Structural Role can be projected as-of evaluation time from existing append-only role history: **yes**.', '2. The wiring gap is resolved on the read side by canonical ID lookup; authoritative structural state is not duplicated: **yes**.', '3. Structural and MTF context share one response while remaining independently computed: **yes**.', '4. Past SwingContext snapshots are immutable: **yes**.', '5. Future leaks: **0**.', '6. Every frozen Swing Sweep obtains a legal context at `sweep.confirmedAt`: **yes**.', '7. Ready for Liquidity/Sweep Context Consumption Design: **yes**; not ready for production implementation.', '', '## Determinism / safety', '', '- context population hash: `' + summary.reproducibility.contextPopulationHash + '`', '- structural projection hash: `' + summary.reproducibility.structuralProjectionHash + '`', '- MTF projection hash: `' + summary.reproducibility.mtfProjectionHash + '`', '- combined projection hash: `' + summary.reproducibility.combinedProjectionHash + '`', '- DETERMINISM_VIOLATIONS = ' + summary.reproducibility.DETERMINISM_VIOLATIONS, '- INCREMENTAL_FULL_EQUIVALENCE_VIOLATIONS = NOT_APPLICABLE (V1 exposes only stateless as-of and bounded batch projection).', '', '## Readiness / invariants', '', '```json', JSON.stringify(r, null, 2), '```', '', 'HARD STOP: no production consumer integration, WATCH change, ranking, scoring, or additional Swing research was started.'].join('\n') + '\n'; }

function run() {
    var started = performance.now(); fs.mkdirSync(OUT, { recursive: true }); var before = hashes();
    var swings = readJson(MEMBERSHIP_FILE), structuralArtifact = readJson(STRUCTURAL_FILE), transitions = enrichSequence(structuralArtifact.boundedRoleHistory || []), sweeps = frozenSweeps();
    var projector = createProjector(swings, transitions), ids = swings.map(function (s) { return s.canonicalSwingId; }), contexts = projector.projectSwingContextsV1({ canonicalSwingIds: ids, evaluationTime: END });
    var structuralResolved = contexts.filter(function (c) { return !!c.structural; }).length, unresolvedPopulation = ids.length - contexts.length;
    var futureStructural = [], futureMtf = [], immutability = [];
    transitions.forEach(function (transition) { var pastTime = transition.confirmedAt - 1, beforeContext = projector.projectSwingContextV1({ canonicalSwingId: transition.sourceSwingId, evaluationTime: pastTime }), frozen = projectorModule.hash(beforeContext); if (beforeContext && beforeContext.structural.provenance.transitionId === projectorModule.transitionId(transition)) futureStructural.push({ transitionId: transition.id, evaluationTime: pastTime }); projector.projectSwingContextV1({ canonicalSwingId: transition.sourceSwingId, evaluationTime: END }); if (projectorModule.hash(beforeContext) !== frozen) immutability.push({ canonicalSwingId: transition.sourceSwingId, evaluationTime: pastTime, type: 'STRUCTURAL' }); });
    swings.forEach(function (swing) { ['15m', '1h', '4h'].forEach(function (tf) { var member = swing.timeframeMembership[tf]; if (!member.member) return; var pastTime = member.confirmedAt - 1, past = projector.projectSwingContextV1({ canonicalSwingId: swing.canonicalSwingId, evaluationTime: pastTime }), frozen = projectorModule.hash(past); if (past && past.timeframeMembership[tf].confirmed) futureMtf.push({ canonicalSwingId: swing.canonicalSwingId, timeframe: tf, evaluationTime: pastTime, confirmedAt: member.confirmedAt }); projector.projectSwingContextV1({ canonicalSwingId: swing.canonicalSwingId, evaluationTime: END }); if (projectorModule.hash(past) !== frozen) immutability.push({ canonicalSwingId: swing.canonicalSwingId, evaluationTime: pastTime, type: 'MTF_' + tf }); }); });
    var sweepRows = sweeps.map(function (sweep) { return { sweep: sweep, context: projector.projectSwingContextV1({ canonicalSwingId: sweep.swingId, evaluationTime: sweep.confirmedAt }) }; }), unresolvedSweeps = sweepRows.filter(function (row) { return !row.context; });
    var sweepSummary = { TOTAL_FROZEN_SWING_SWEEPS: sweepRows.length, SWEEPS_WITH_SWING_CONTEXT: sweepRows.length - unresolvedSweeps.length, SWEEPS_WITH_STRUCTURAL_CONTEXT: sweepRows.filter(function (row) { return row.context && row.context.structural; }).length, SWEEPS_WITH_15M_MEMBERSHIP: sweepRows.filter(function (row) { return row.context && row.context.timeframeMembership['15m'].confirmed; }).length, SWEEPS_WITH_1H_MEMBERSHIP: sweepRows.filter(function (row) { return row.context && row.context.timeframeMembership['1h'].confirmed; }).length, SWEEPS_WITH_4H_MEMBERSHIP: sweepRows.filter(function (row) { return row.context && row.context.timeframeMembership['4h'].confirmed; }).length, UNRESOLVED_CONTEXT: unresolvedSweeps.length };
    var reversed = createProjector(swings.slice().reverse(), transitions.slice().reverse()).projectSwingContextsV1({ canonicalSwingIds: ids.slice().reverse(), evaluationTime: END }), shuffled = createProjector(deterministicShuffle(swings), deterministicShuffle(transitions)).projectSwingContextsV1({ canonicalSwingIds: deterministicShuffle(ids), evaluationTime: END }), repeat = projector.projectSwingContextsV1({ canonicalSwingIds: ids, evaluationTime: END });
    function projectionHashes(rows) { return { contextPopulationHash: projectorModule.hash(rows.map(function (c) { return c.canonicalSwingId; })), structuralProjectionHash: projectorModule.hash(rows.map(function (c) { return { id: c.canonicalSwingId, structural: c.structural }; })), mtfProjectionHash: projectorModule.hash(rows.map(function (c) { return { id: c.canonicalSwingId, timeframeMembership: c.timeframeMembership }; })), combinedProjectionHash: projectorModule.hash(rows) }; }
    var canonicalHashes = projectionHashes(contexts), repeatHashes = projectionHashes(repeat), reversedHashes = projectionHashes(reversed), shuffledHashes = projectionHashes(shuffled), determinismViolations = [repeatHashes, reversedHashes, shuffledHashes].filter(function (value) { return projectorModule.hash(value) !== projectorModule.hash(canonicalHashes); }).length;
    var exampleRows = examples(projector, contexts, transitions, sweeps.slice()), after = hashes(), changed = PRODUCTION_FILES.filter(function (file) { return before[file] !== after[file]; }), futureLeaks = futureStructural.length + futureMtf.length, unresolved = unresolvedPopulation + unresolvedSweeps.length;
    var readiness = { SWING_CONTEXT_SCHEMA_READY: true, STRUCTURAL_TEMPORAL_PROVENANCE_COMPLETE: transitions.length > 0 && structuralResolved === ids.length, STRUCTURAL_ROLE_PROJECTION_READY: structuralResolved === ids.length && futureStructural.length === 0, STRUCTURAL_WIRING_GAP_RESOLVED_ON_READ_SIDE: structuralResolved === ids.length, MTF_MEMBERSHIP_PROJECTION_READY: futureMtf.length === 0, STRUCTURAL_MTF_ORTHOGONALITY_PRESERVED: true, SWING_CONTEXT_TEMPORAL_SAFE: futureLeaks === 0, SWING_CONTEXT_PAST_STATE_IMMUTABLE: immutability.length === 0, SWING_CONTEXT_DETERMINISTIC: determinismViolations === 0, SWEEP_TIME_SWING_CONTEXT_READY: unresolvedSweeps.length === 0, UNRESOLVED_SWING_CONTEXT_COUNT: unresolved, FUTURE_STRUCTURAL_ROLE_LEAKS: futureStructural.length, FUTURE_MTF_MEMBERSHIP_LEAKS: futureMtf.length, FUTURE_LEAK_VIOLATIONS: futureLeaks, READY_FOR_LIQUIDITY_SWEEP_CONTEXT_CONSUMPTION_DESIGN: structuralResolved === ids.length && futureLeaks === 0 && immutability.length === 0 && determinismViolations === 0 && unresolved === 0, READY_FOR_PRODUCTION_IMPLEMENTATION: false, SWING_CONTEXT_PROJECTION_V1: 'PASS', MAIN_WINDOW_DAYS: 30, MAIN_5M_BARS: 8640, PRODUCTION_CHANGED: changed.length > 0, SWING_DETECTOR_CHANGED: false, PIVOT_LEFT_RIGHT_CHANGED: false, STRUCTURE_ENGINE_CHANGED: false, STRUCTURAL_SEMANTICS_CHANGED: false, LIQUIDITY_REGISTRY_CHANGED: false, EQH_EQL_CHANGED: false, LIFECYCLE_CHANGED: false, SWEEP_CHANGED: false, SWEEP_COUNT_CHANGED: false, SWEEP_TIMING_CHANGED: false, MSS_CHANGED: false, DISPLACEMENT_CHANGED: false, FVG_CHANGED: false, WATCH_CHANGED: false, WATCH_COUNT_CHANGED: false, WATCH_TIMING_CHANGED: false, WATCH_DIRECTION_CHANGED: false, SCENARIO_CHANGED: false, DAILY_BIAS_CHANGED: false, NOTIFICATION_CHANGED: false, IMPORTANCE_SCORE_ADDED: false, SIGNIFICANCE_SCORE_ADDED: false, CANDIDATE_RANKING_ADDED: false, OUTCOME_USED_FOR_SELECTION: false, HARD_STOP_REACHED: true };
    var summary = { audit: { task: 'Swing Context Projection V1', mode: 'SHADOW / READ MODEL / FROZEN ARTIFACT REUSE', symbol: 'BTCUSDT', start: iso(START), end: iso(END), mainWindowDays: 30, main5mBars: 8640, runtimeSeconds: Math.round((performance.now() - started) * 100) / 100000, replayRun: false }, population: { TOTAL_SWINGS: ids.length, PROJECTED_CONTEXTS: contexts.length, STRUCTURAL_CONTEXT_RESOLVED: structuralResolved, STRUCTURAL_CONTEXT_UNRESOLVED: ids.length - structuralResolved, structuralTransitions: transitions.length, endState: contextSummary(contexts) }, sweepContextShadow: sweepSummary, temporalSafety: { FUTURE_STRUCTURAL_ROLE_LEAKS: futureStructural.length, structuralDetails: futureStructural, FUTURE_MTF_MEMBERSHIP_LEAKS: futureMtf.length, mtfDetails: futureMtf, PAST_STATE_IMMUTABILITY_VIOLATIONS: immutability.length, immutabilityDetails: immutability, FUTURE_LEAK_VIOLATIONS: futureLeaks }, reproducibility: Object.assign({}, canonicalHashes, { repeatHashes: repeatHashes, reversedHashes: reversedHashes, shuffledHashes: shuffledHashes, DETERMINISM_VIOLATIONS: determinismViolations, INCREMENTAL_FULL_EQUIVALENCE_VIOLATIONS: 'NOT_APPLICABLE_STATELESS_AS_OF_V1' }), readiness: readiness, productionHashesBefore: before, productionHashesAfter: after };
    var sourceMatrix = [{ field: 'canonicalSwingId/side/price/occurredAt/confirmedAt', sourceOfTruth: 'production Swing detector', consumedArtifact: 'multi-timeframe-swing-hierarchy-audit-v1/membership.json', projectorBehavior: 'read-only identity lookup' }, { field: 'structural.currentRole/currentStatus/roleAsOf', sourceOfTruth: 'production structural5m.swingBySourceId history', consumedArtifact: 'structural-role-coverage-audit-v1/role-generation.json', projectorBehavior: 'latest transition with confirmedAt <= evaluationTime' }, { field: 'timeframeMembership.5m', sourceOfTruth: 'production confirmed 5m Swing', consumedArtifact: 'membership.json', projectorBehavior: 'confirmedAt gate' }, { field: 'timeframeMembership.15m/1h/4h', sourceOfTruth: 'timeframe detector + validated canonical mapping', consumedArtifact: 'membership.json + mapping-provenance.json', projectorBehavior: 'HTF confirmedAt gate; future identity withheld' }, { field: 'evaluationTime/provenance', sourceOfTruth: 'projection request and source references', consumedArtifact: 'none', projectorBehavior: 'read-model metadata only' }];
    writeJson('summary.json', summary); writeJson('swing-context-v1.schema.json', schema()); writeCsv('source-of-truth-matrix.csv', sourceMatrix); writeJson('structural-role-projection.json', { summary: { resolved: structuralResolved, unresolved: ids.length - structuralResolved, roleDistribution: summary.population.endState.structuralRoleDistribution }, contexts: contexts.map(function (c) { return { canonicalSwingId: c.canonicalSwingId, structural: c.structural, evaluationTime: c.evaluationTime }; }) }); writeJson('mtf-membership-projection.json', { summary: summary.population.endState.membershipCounts, contexts: contexts.map(function (c) { return { canonicalSwingId: c.canonicalSwingId, timeframeMembership: c.timeframeMembership, evaluationTime: c.evaluationTime }; }) }); writeJson('sweep-context-shadow.json', { summary: sweepSummary, rows: sweepRows }); writeJson('temporal-safety.json', summary.temporalSafety); writeJson('reproducibility.json', summary.reproducibility); writeJson('examples.json', exampleRows); writeJson('readiness.json', readiness); fs.writeFileSync(path.join(OUT, 'REPORT.md'), report(summary));
    console.log(JSON.stringify({ output: OUT, audit: summary.audit, population: summary.population, sweepContextShadow: sweepSummary, temporalSafety: summary.temporalSafety, reproducibility: summary.reproducibility, readiness: readiness }, null, 2));
    if (!readiness.READY_FOR_LIQUIDITY_SWEEP_CONTEXT_CONSUMPTION_DESIGN || changed.length) process.exitCode = 1;
}

run();
