#!/usr/bin/env node
'use strict';

/** Final audit-only SwingStateV1 integration and replay acceptance harness. */
var crypto=require('crypto'),fs=require('fs'),path=require('path');
var projector=require('../audit/swingStateProjectorV1');
var boundary=require('../audit/reactionBoundaryPolicyV1');
var baseAudit=require('./swingReactionLegStructuralAttributionAuditV1');
var design=require('./swingMultiDimensionalStateModelDesignV1');

var ROOT=path.resolve(__dirname,'..');
var VIS='/Users/yaodebao/.codex/visualizations/2026/08/24/01a031bc-fea2-7943-9b4f-2a5e77efcdda';
var OUT=path.resolve(process.argv[2]||path.join(VIS,'swing-state-finalization-v1'));
var PARAM=path.join(VIS,'reaction-leg-parameterization-audit-v1');
var EQ=path.join(VIS,'eq-historical-membership-event-stream-audit-v1-bounded-30d');
var CONTRACT=path.join(VIS,'reaction-boundary-policy-contract-v1');
var EXPECTED_POPULATION_HASH='f9f0d11436976f214682257318068ef3fe1f7e393c836deb6daf8bb1afa0310a';
var POLICY={B:boundary.POLICY_ID.RETURN_TO_SWING_ORIGIN,C:boundary.POLICY_ID.OPPOSITE_STRUCTURAL_RESET};
var PRODUCTION_FILES=['structure/pivotDetector.js','liquidity/swingLiquidity.js','liquidity/equalLiquidity.js','liquidity/liquidityLifecycle.js','structure/structuralProvenance5m.js','events/mssSignalDetector.js','events/displacementDetector.js','watch/displacementWatch.js'];

function read(file){return JSON.parse(fs.readFileSync(file,'utf8'));}function ensure(dir){fs.mkdirSync(dir,{recursive:true});}function write(name,value){var file=path.join(OUT,name);ensure(path.dirname(file));fs.writeFileSync(file,typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');}
function fileSha(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}function fileHashes(){var out={};PRODUCTION_FILES.forEach(function(f){var p=path.join(ROOT,f);if(fs.existsSync(p))out[f]=fileSha(p);});return out;}
function index(rows,key){var out={};rows.forEach(function(r){out[r[key]]=r;});return out;}function event(id,type,swingId,availableAt,sequence,payload,source){return{id:id,type:type,swingId:swingId,availableAt:availableAt,sequence:sequence,payload:payload,source:source};}
function policyEntry(letter){return boundary.getReactionBoundaryPolicy(POLICY[letter],'v1');}function policyValue(letter){return policyEntry(letter).reactionBoundaryPolicy;}function samePolicy(a,b){return a&&b&&a.policyId===b.policyId&&a.policyVersion===b.policyVersion;}

function verifyContract(){
 var summary=read(path.join(CONTRACT,'contract-summary.json')),eligible=boundary.listEligibleReactionBoundaryPolicies().map(function(x){return x.canonicalPolicyIdentity;}).sort();
 if(summary.readiness.REACTION_BOUNDARY_POLICY_CONTRACT_READY!==true||eligible.join('|')!==['OPPOSITE_STRUCTURAL_RESET:v1','RETURN_TO_SWING_ORIGIN:v1'].sort().join('|')||boundary.getProductionReactionBoundaryPolicy()!==null)throw new Error('REACTION_BOUNDARY_POLICY_CONTRACT_NOT_READY');
 return{REACTION_BOUNDARY_POLICY_CONTRACT_READY:true,eligiblePolicies:eligible,PRODUCTION_POLICY_SELECTED:false,REACTION_POLICY_SELECTION_RESOLVED:false,implicitPolicyFallback:false};
}

function computeRows(input,legs){
 var legBy=index(legs,'canonicalSwingId'),rows={};
 input.population.forEach(function(s){var f=input.formationById[s.id],leg=legBy[s.id];if(!leg)throw new Error('Missing frozen leg '+s.id);var opposite=f.side==='SWING_HIGH'?input.oppositeLists.SWING_LOW:input.oppositeLists.SWING_HIGH,snapshot=baseAudit.snapshotStructuralReferences(f,opposite,input.firstBreak),structure=baseAudit.structuralBreakFor(f,leg,snapshot,input.events.mss,input.swingById,input.firstBreak,input.candles),mss=baseAudit.attributeMss(f,leg,structure,input.events,input.swingById,input.firstBreak,input.candles),disp=baseAudit.attributeDisplacement(f,leg,mss,input.events,input.candles),follow=baseAudit.followThroughFor(f,disp,input.displacementById,input.candles);rows[s.id]=Object.assign({},f,leg,snapshot,structure,mss,disp,follow);});
 return rows;
}

function baseObjects(input){var out={};input.population.forEach(function(s){var f=input.formationById[s.id],b=design.baseFrom(f);b.formation.atrAtConfirmedAt=f.atrAtConfirmedAt;out[s.id]=b;});return out;}

function eqEvents(baseById){
 var memberships=read(path.join(EQ,'eq-membership-events.json')),lifecycle=read(path.join(EQ,'eq-lifecycle-events.json')),byObject={},bySwing={},violations=0,imported=0,lifecycleUpdates=0;
 memberships.forEach(function(m){if(!baseById[m.canonicalSwingId]){violations++;return;}var e=event('SWINGSTATE:'+m.eventId,'EQ_MEMBERSHIP_ASSIGNED',m.canonicalSwingId,m.effectiveAt,5,{eqObjectId:m.eqObjectId,eqRole:m.type+'_MEMBER',memberConfirmedAt:m.memberConfirmedAt,membershipEventId:m.eventId,objectLifecycleState:'ACTIVE',sourceOfTruth:'VALIDATED_EQ_TEMPORAL_EVENT_STREAM'},'EQ_TEMPORAL_BOUNDED_30D');(bySwing[m.canonicalSwingId]||(bySwing[m.canonicalSwingId]=[])).push(e);(byObject[m.eqObjectId]||(byObject[m.eqObjectId]=[])).push(m);imported++;});
 lifecycle.forEach(function(l){(byObject[l.eqObjectId]||[]).forEach(function(m){if(m.effectiveAt>l.effectiveAt)return;var e=event('SWINGSTATE:'+l.eventId+':'+m.canonicalSwingId,'EQ_MEMBERSHIP_LIFECYCLE_UPDATED',m.canonicalSwingId,l.effectiveAt,6,{eqObjectId:l.eqObjectId,objectLifecycleState:l.nextState,eqLifecycleEventId:l.eventId,sourceOfTruth:'VALIDATED_EQ_TEMPORAL_EVENT_STREAM'},'EQ_TEMPORAL_BOUNDED_30D');(bySwing[m.canonicalSwingId]||(bySwing[m.canonicalSwingId]=[])).push(e);lifecycleUpdates++;});});
 return{bySwing:bySwing,membershipEventsImported:imported,lifecycleUpdates:lifecycleUpdates,sourceViolations:violations,sourceSummary:read(path.join(EQ,'summary.json'))};
}

function reactionEvents(row,letter,input){
 var id=row.canonicalSwingId,p=policyValue(letter),identity=boundary.canonicalReactionBoundaryPolicyIdentity(p.policyId,p.policyVersion),legId=id+':REACTION_LEG:'+identity,out=[];
 if(row.observationStartAt!=null)out.push(event(legId+':OBSERVE','REACTION_OBSERVATION_STARTED',id,row.observationStartAt,10,{reactionLegId:legId,reactionBoundaryPolicy:p,parameterDependent:false},'FROZEN_REACTION_LEG_'+letter));
 if(row.reactionInitiatedIndex!=null&&input.candles[row.reactionInitiatedIndex])out.push(event(legId+':START','REACTION_STARTED',id,input.candles[row.reactionInitiatedIndex].closeTime,20,{reactionLegId:legId,reactionBoundaryPolicy:p,direction:row.reactionDirection},'FROZEN_REACTION_LEG_'+letter));
 if(row.endAt!=null){out.push(event(legId+':EVIDENCE','REACTION_EVIDENCE_UPDATED',id,row.endAt,30,{reactionLegId:legId,reactionBoundaryPolicy:p,frontier:row.frontierPrice,evidence:{mfeATR:row.mfeATR,maeATR:row.maeATR,barsAlive:row.barsAlive}},'FROZEN_REACTION_LEG_'+letter));var type=row.terminationReason==='MAX_HORIZON'?'REACTION_CAPPED':row.terminationReason==='DATA_END'?'REACTION_DATA_END':'REACTION_TERMINATED';out.push(event(legId+':END',type,id,row.endAt,90,{reactionLegId:legId,reactionBoundaryPolicy:p,endReason:row.terminationReason},'FROZEN_REACTION_LEG_'+letter));}
 return{legId:legId,events:out};
}

function structuralEvents(row,letter,legId,input){
 var id=row.canonicalSwingId,p=policyValue(letter),out=[];
 if(row.attributedMss){var ref=input.swingById[row.attributedMssReferenceId];out.push(event(id+':MSS:'+letter+':'+row.attributedMssId,'STRUCTURAL_MSS_ATTRIBUTED',id,row.attributedMssConfirmedAt,100,{sourceSwingId:id,sourceReactionLegId:legId,reactionBoundaryPolicy:{policyId:p.policyId,policyVersion:p.policyVersion},reference:{swingId:row.attributedMssReferenceId,price:row.structuralReferencePrice,confirmedAt:ref?ref.confirmedAt:null,breakAt:row.breakAt},mss:{id:row.attributedMssId,confirmedAt:row.attributedMssConfirmedAt,referenceSwingId:row.attributedMssReferenceId}},'STRICT_ATTRIBUTION_'+letter));}
 if(row.sameDeliveryDisplacement){out.push(event(id+':DISP:'+letter+':'+row.attributedDisplacementId,'DISPLACEMENT_ATTRIBUTED',id,row.attributedDisplacementConfirmedAt,110,{sourceSwingId:id,sourceReactionLegId:legId,reactionBoundaryPolicy:{policyId:p.policyId,policyVersion:p.policyVersion},sourceMssId:row.attributedMssId,displacementId:row.attributedDisplacementId,direction:row.attributedDisplacementDirection},'STRICT_ATTRIBUTION_'+letter));[3,5,10].forEach(function(h){var idx=row.attributedDisplacementIndex+h;if(!input.candles[idx]||row['followThroughATR_'+h]==null)return;out.push(event(id+':FOLLOW:'+letter+':'+h,'FOLLOW_THROUGH_UPDATED',id,input.candles[idx].closeTime,120+h,{sourceSwingId:id,sourceReactionLegId:legId,reactionBoundaryPolicy:{policyId:p.policyId,policyVersion:p.policyVersion},sourceMssId:row.attributedMssId,sourceDisplacementId:row.attributedDisplacementId,horizonBars:h,followThroughATR:row['followThroughATR_'+h]},'STRICT_ATTRIBUTION_'+letter));});}
 return out;
}

function buildStreams(input,baseById,rowsByPolicy,eq){
 var lifecycle={},streams={B:{},C:{}},counts={B:0,C:0,lifecycle:0,eqMembership:eq.membershipEventsImported,eqLifecycle:eq.lifecycleUpdates};
 input.population.forEach(function(s,n){var id=s.id;if(!lifecycle[id])lifecycle[id]=design.lifecycleEvents(baseById[id],input.candles);if(n===0)counts.lifecycle=0;counts.lifecycle+=lifecycle[id].length;['B','C'].forEach(function(letter){var r=reactionEvents(rowsByPolicy[letter][id],letter,input),events=[];Array.prototype.push.apply(events,eq.bySwing[id]||[]);Array.prototype.push.apply(events,r.events);Array.prototype.push.apply(events,structuralEvents(rowsByPolicy[letter][id],letter,r.legId,input));Array.prototype.push.apply(events,lifecycle[id]);events.sort(projector.eventOrder);streams[letter][id]=events;counts[letter]+=events.length;});if((n+1)%5000===0)console.log('[Build Event Stream] '+(n+1)+' / '+input.population.length);});
 return{streams:streams,counts:counts};
}

function validateEventProvenance(events,policy){var missing=0,mismatch=0,structural=0;events.forEach(function(e){if(/^REACTION_/.test(e.type)||/^(STRUCTURAL_MSS_ATTRIBUTED|DISPLACEMENT_ATTRIBUTED|FOLLOW_THROUGH_UPDATED)$/.test(e.type)){var p=e.payload.reactionBoundaryPolicy;if(!p)missing++;else if(!samePolicy(p,policy))mismatch++;}if(e.type==='STRUCTURAL_MSS_ATTRIBUTED'){structural++;if(!e.payload.sourceSwingId||!e.payload.sourceReactionLegId||!e.payload.reference||!e.payload.reference.swingId||!e.payload.mss||!e.payload.mss.id)missing++;}if(e.type==='DISPLACEMENT_ATTRIBUTED'&&(!e.payload.sourceSwingId||!e.payload.sourceReactionLegId||!e.payload.sourceMssId||!e.payload.displacementId))missing++;});return{missing:missing,mismatch:mismatch,structuralEvents:structural};}
function expectedLifecycle(events){var life=events.filter(function(e){return/^LIQUIDITY_/.test(e.type);}).sort(projector.eventOrder);if(!life.length)return'ACTIVE';var type=life[life.length-1].type;return type==='LIQUIDITY_TOUCHED'?'TOUCHED':type==='LIQUIDITY_SWEPT'?'SWEPT':'BROKEN';}
function expectedEq(events){var map={};events.filter(function(e){return/^EQ_MEMBERSHIP_/.test(e.type);}).sort(projector.eventOrder).forEach(function(e){if(e.type==='EQ_MEMBERSHIP_ASSIGNED')map[e.payload.eqObjectId]={state:e.payload.objectLifecycleState||'ACTIVE'};else if(map[e.payload.eqObjectId])map[e.payload.eqObjectId].state=e.payload.objectLifecycleState;});return map;}

function validatePolicy(letter,input,baseById,eventsById,rows){
 var policy=policyEntry(letter),result={projectable:0,unprojectable:0,schemaViolations:0,missingProvenance:0,policyMismatch:0,formationMutation:0,eqViolations:0,lifecycleViolations:0,structuralTraceabilityViolations:0,incrementalViolations:0,pastImmutabilityViolations:0,futureLeaks:0,determinismViolations:0,stateHashes:[],reverseStateHashes:[],exampleCandidates:[]};
 input.population.forEach(function(s,n){var id=s.id,base=baseById[id],events=eventsById[id],provenance=validateEventProvenance(events,policy.reactionBoundaryPolicy);result.missingProvenance+=provenance.missing;result.policyMismatch+=provenance.mismatch;events.forEach(function(e){if(e.availableAt<base.identity.confirmedAt&&e.type!=='EQ_MEMBERSHIP_ASSIGNED')result.futureLeaks++;});try{var finalState=projector.projectSwingState(base,events,input.endTime,policy);result.projectable++;['formation','topology','liquidityRoles','context','reaction','structuralImpact','lifecycle'].forEach(function(section){if(!finalState[section])result.schemaViolations++;});if(projector.stable(finalState.formation)!==projector.stable(base.formation))result.formationMutation++;var expected=expectedLifecycle(events);if(finalState.lifecycle.status!==expected)result.lifecycleViolations++;var eq=expectedEq(events),actual={};finalState.topology.eqMemberships.forEach(function(m){actual[m.eqObjectId]=m.objectLifecycleState||'ACTIVE';});if(projector.stable(eq)!==projector.stable(Object.keys(actual).reduce(function(o,k){o[k]={state:actual[k]};return o;},{})))result.eqViolations++;var row=rows[id];if(row.attributedMss&&(!finalState.structuralImpact.mss||finalState.structuralImpact.mss.id!==row.attributedMssId||finalState.structuralImpact.reference.swingId!==row.attributedMssReferenceId||!samePolicy(finalState.structuralImpact.reactionBoundaryPolicy,policy.reactionBoundaryPolicy)))result.structuralTraceabilityViolations++;if(row.sameDeliveryDisplacement&&(!finalState.structuralImpact.displacement||finalState.structuralImpact.displacement.displacementId!==row.attributedDisplacementId||finalState.structuralImpact.displacement.sourceMssId!==row.attributedMssId))result.structuralTraceabilityViolations++;var checkpoint=Math.min(input.endTime,base.identity.confirmedAt+20*300000),past=projector.projectSwingState(base,events,checkpoint,policy),pastHash=projector.stateHash(past),incremental=projector.advanceSwingState(past,events,input.endTime,policy);if(projector.stateHash(incremental)!==projector.stateHash(finalState))result.incrementalViolations++;if(projector.stateHash(past)!==pastHash)result.pastImmutabilityViolations++;var reversed=projector.projectSwingState(base,events.slice().reverse(),input.endTime,policy),hash=projector.stateHash(finalState),reverseHash=projector.stateHash(reversed);if(reverseHash!==hash)result.determinismViolations++;result.stateHashes.push([id,hash]);result.reverseStateHashes.push([id,reverseHash]);if(provenance.structuralEvents&&events.some(function(e){return/^LIQUIDITY_/.test(e.type);}))result.exampleCandidates.push(id);}catch(error){result.unprojectable++;if(error.code==='REACTION_BOUNDARY_POLICY_MISMATCH')result.policyMismatch++;else if(/PROVENANCE/.test(error.code||''))result.missingProvenance++;}if((n+1)%5000===0)console.log('[Project '+letter+'] '+(n+1)+' / '+input.population.length);});
 result.stateHash=baseAudit.sha(result.stateHashes);result.reverseInputStateHash=baseAudit.sha(result.reverseStateHashes);delete result.stateHashes;delete result.reverseStateHashes;result.exampleCandidates=result.exampleCandidates.sort().slice(0,5);return result;
}

function examples(ids,input,baseById,streams){ids.forEach(function(id,i){var timelines={};['B','C'].forEach(function(letter){var events=streams[letter][id],times=[baseById[id].identity.confirmedAt],reaction=events.filter(function(e){return e.type==='REACTION_STARTED';})[0],mss=events.filter(function(e){return e.type==='STRUCTURAL_MSS_ATTRIBUTED';})[0],life=events.filter(function(e){return/^LIQUIDITY_/.test(e.type);})[0];[reaction&&reaction.availableAt,mss&&mss.availableAt,life&&life.availableAt,input.endTime].filter(Number.isFinite).forEach(function(t){if(times.indexOf(t)<0)times.push(t);});times.sort(function(a,b){return a-b;});timelines[letter]=times.map(function(t){return{evaluationTime:t,state:projector.projectSwingState(baseById[id],events,t,policyEntry(letter))};});});write(path.join('examples','example-'+String(i+1).padStart(2,'0')+'.json'),{canonicalSwingId:id,selection:'DETERMINISTIC_CANONICAL_ID_WITH_STRUCTURAL_AND_LIFECYCLE_EVENTS',SHADOW_B:timelines.B,SHADOW_C:timelines.C});});}

function main(){var started=Date.now(),before=fileHashes();ensure(OUT);console.log('[Load] verify contract and frozen sources');var contract=verifyContract(),input=baseAudit.loadInput();if(!input.baselineMatch||input.populationHash!==EXPECTED_POPULATION_HASH)throw new Error('POPULATION_BASELINE_MISMATCH');var legBFile=path.join(PARAM,'reaction-legs-policy-b.json'),legCFile=path.join(PARAM,'reaction-legs-policy-c.json'),legsB=read(legBFile),legsC=read(legCFile),baseById=baseObjects(input),eq=eqEvents(baseById);console.log('[Load] bars='+input.auditBars.length+' swings='+input.population.length+' EQ memberships='+eq.membershipEventsImported);
 console.log('[Build Event Stream] frozen B/C legs + strict attribution + lifecycle + validated EQ');var rows={B:computeRows(input,legsB),C:computeRows(input,legsC)},built=buildStreams(input,baseById,rows,eq);
 console.log('[Project B]');var b=validatePolicy('B',input,baseById,built.streams.B,rows.B);console.log('[Project C]');var c=validatePolicy('C',input,baseById,built.streams.C,rows.C);
 console.log('[Incremental Equivalence] B='+b.incrementalViolations+' C='+c.incrementalViolations);console.log('[Past Immutability] B='+b.pastImmutabilityViolations+' C='+c.pastImmutabilityViolations);console.log('[Future Leak] '+(b.futureLeaks+c.futureLeaks));
 var exampleIds=Array.from(new Set(b.exampleCandidates.concat(c.exampleCandidates))).sort().slice(0,5);examples(exampleIds,input,baseById,built.streams);
 var acceptance={ACCEPTANCE_SCOPE:'FROZEN_180D_SWINGSTATE_WITH_VALIDATED_BOUNDED_30D_EQ_SOURCE',ACCEPTANCE_SCOPE_REASON:'180d frozen Swing/MSS/Displacement sources are fast; EQ consumes the already validated bounded 30d append-only stream and does not rerun frozen O(N^2) production EQ',TOTAL_SWINGS:input.population.length,PROJECTABLE_SWINGS_B:b.projectable,PROJECTABLE_SWINGS_C:c.projectable,UNPROJECTABLE_SWINGS_B:b.unprojectable,UNPROJECTABLE_SWINGS_C:c.unprojectable,SCHEMA_REQUIRED_SECTION_VIOLATIONS:b.schemaViolations+c.schemaViolations,MISSING_PROVENANCE_B:b.missingProvenance,MISSING_PROVENANCE_C:c.missingProvenance,POLICY_MISMATCH_VIOLATIONS:b.policyMismatch+c.policyMismatch,FORMATION_RETROACTIVE_MUTATION_COUNT:b.formationMutation+c.formationMutation,EQ_CONSUMPTION_VIOLATIONS:eq.sourceViolations+b.eqViolations+c.eqViolations,LIFECYCLE_TRACEABILITY_VIOLATIONS:b.lifecycleViolations+c.lifecycleViolations,STRUCTURAL_IMPACT_TRACEABILITY_VIOLATIONS_B:b.structuralTraceabilityViolations,STRUCTURAL_IMPACT_TRACEABILITY_VIOLATIONS_C:c.structuralTraceabilityViolations,INCREMENTAL_FULL_REPLAY_EQUIVALENCE_VIOLATIONS_B:b.incrementalViolations,INCREMENTAL_FULL_REPLAY_EQUIVALENCE_VIOLATIONS_C:c.incrementalViolations,PAST_STATE_IMMUTABILITY_VIOLATIONS_B:b.pastImmutabilityViolations,PAST_STATE_IMMUTABILITY_VIOLATIONS_C:c.pastImmutabilityViolations,FUTURE_LEAK_VIOLATIONS:b.futureLeaks+c.futureLeaks,DETERMINISM_VIOLATIONS:b.determinismViolations+c.determinismViolations};
 var pass=acceptance.TOTAL_SWINGS===14307&&acceptance.PROJECTABLE_SWINGS_B===14307&&acceptance.PROJECTABLE_SWINGS_C===14307&&Object.keys(acceptance).filter(function(k){return/VIOLATIONS|MUTATION|UNPROJECTABLE|MISSING_PROVENANCE/.test(k);}).every(function(k){return acceptance[k]===0;});console.log('[Acceptance] '+(pass?'PASS':'FAIL'));
 var after=fileHashes(),changed=Object.keys(before).filter(function(f){return before[f]!==after[f];}),runtime=(Date.now()-started)/1000,readiness={REACTION_BOUNDARY_POLICY_CONTRACT_READY:contract.REACTION_BOUNDARY_POLICY_CONTRACT_READY,SWINGSTATE_SHADOW_INTEGRATION_COMPLETE:pass,SWINGSTATE_REPLAY_ACCEPTANCE_PASSED:pass,SWINGSTATE_TEMPORAL_SAFE:pass,SWINGSTATE_PROVENANCE_COMPLETE:pass,SWINGSTATE_DETERMINISTIC:pass,SWINGSTATE_INCREMENTAL_REPLAY_EQUIVALENT:pass,SWINGSTATE_PAST_STATE_IMMUTABLE:pass,SHADOW_POLICY_B_SUPPORTED:pass,SHADOW_POLICY_C_SUPPORTED:pass,PRODUCTION_POLICY_SELECTED:false,REACTION_POLICY_SELECTION_RESOLVED:false,SWING_RESEARCH_COMPLETE:pass,FURTHER_SWING_OPTIMIZATION:pass?'STOP':'BLOCKED',READY_FOR_WATCH_CONSUMPTION_AUDIT:pass,READY_FOR_PRODUCTION_IMPLEMENTATION:false,HARD_STOP_TRIGGERED:true,HARD_STOP_REASON:pass?'SWING_RESEARCH_EXIT_PLAN_COMPLETE':'SWINGSTATE_ACCEPTANCE_FAILED'};
 var invariants={SHADOW_ONLY:true,PRODUCTION_CONSUMERS:0,PRODUCTION_CHANGED:changed.length>0,SWING_DETECTOR_CHANGED:false,EQH_EQL_CHANGED:false,EQ_TEMPORAL_CHANGED:false,LIQUIDITY_LIFECYCLE_CHANGED:false,MSS_PRODUCTION_CHANGED:false,DISPLACEMENT_PRODUCTION_CHANGED:false,REACTION_PRODUCTION_CHANGED:false,WATCH_CHANGED:false,NOTIFICATION_CHANGED:false,DAILY_BIAS_CHANGED:false,SCENARIO_CHANGED:false,ENTRY_CHANGED:false,PRODUCTION_THRESHOLD_ADDED:false,SIGNIFICANCE_SCORE_ADDED:false,OUTCOME_USED_FOR_SELECTION:false};
 var source={SwingIdentity:'production Swing detector via frozen 180d population',Formation:'frozen formation-features source',Topology:'frozen formation topology features',EqMembershipAndRoles:'validated bounded 30d EQ append-only event stream',Lifecycle:'production liquidityLifecycle source consumed by audit event capture',MSS:'production MSS event source',Displacement:'production Displacement event source',ReactionBoundary:'ReactionBoundaryPolicyV1 B/C eligible shadow registry',SwingState:'audit-only event-sourced projection/read model',populationHash:input.populationHash,policyBLegArtifactSha256:fileSha(legBFile),policyCLegArtifactSha256:fileSha(legCFile),eqMembershipEventHash:eq.sourceSummary.determinism.ProjectionA.membershipEventHash,eqLifecycleEventHash:eq.sourceSummary.determinism.ProjectionA.lifecycleEventHash,productionFileHashes:after};
 var provenance={SHADOW_B:{policy:policyEntry('B'),eventCount:built.counts.B,stateHash:b.stateHash},SHADOW_C:{policy:policyEntry('C'),eventCount:built.counts.C,stateHash:c.stateHash},policyMixingAllowed:false,consistencyGuard:'validateReactionBoundaryPolicyConsistency',productionPolicy:null};
 var reproducibility={populationHash:input.populationHash,SHADOW_B_STATE_HASH_CANONICAL_ORDER:b.stateHash,SHADOW_B_STATE_HASH_REVERSED_INPUT:b.reverseInputStateHash,SHADOW_C_STATE_HASH_CANONICAL_ORDER:c.stateHash,SHADOW_C_STATE_HASH_REVERSED_INPUT:c.reverseInputStateHash,reverseInputOrderDeterminismViolations:b.determinismViolations+c.determinismViolations,DETERMINISTIC:b.stateHash===b.reverseInputStateHash&&c.stateHash===c.reverseInputStateHash};
 var futureLeak={FUTURE_LEAK_VIOLATIONS:acceptance.FUTURE_LEAK_VIOLATIONS,policyB:b.futureLeaks,policyC:c.futureLeaks};var summary={task:'SwingState Finalization V1',mode:'SHADOW_ONLY_EVENT_SOURCED_REPLAY_ACCEPTANCE',runtimeSeconds:runtime,population:{POPULATION_BASELINE_MATCH:input.populationHash===EXPECTED_POPULATION_HASH,TOTAL_CONFIRMED_SWINGS:input.population.length,populationHash:input.populationHash},acceptance:acceptance,readiness:readiness,invariants:invariants,tests:{ALL_TARGETED_TESTS_PASSED:null,ALL_RELEVANT_TESTS_PASSED:null,ALL_TESTS_PASSED:null}};
 console.log('[Artifacts]');write('acceptance.json',acceptance);write('source-of-truth.json',source);write('policy-provenance.json',provenance);write('future-leak-audit.json',futureLeak);write('reproducibility.json',reproducibility);write('summary.json',summary);write('REPORT.md',report(summary));console.log(JSON.stringify({output:OUT,runtimeSeconds:runtime,acceptance:acceptance,readiness:readiness,invariants:invariants},null,2));if(!pass||changed.length)process.exitCode=1;}

function report(s){return'# SwingState Finalization V1\n\n## Outcome\n\n'+(s.readiness.SWINGSTATE_REPLAY_ACCEPTANCE_PASSED?'PASS':'FAIL')+'. SwingStateV1 is an audit-only, temporal, event-sourced, versioned read model with explicit independent B/C shadow projections. No production policy was selected.\n\n## Acceptance\n\n```json\n'+JSON.stringify(s.acceptance,null,2)+'\n```\n\n## Readiness\n\n```json\n'+JSON.stringify(s.readiness,null,2)+'\n```\n\n## Invariants\n\n```json\n'+JSON.stringify(s.invariants,null,2)+'\n```\n\nThe five deterministic temporal examples are in `examples/`. If PASS, the Swing Research Exit Plan is complete and the only next mainline is WATCH Consumption Audit.\n';}
if(require.main===module){try{main();}catch(error){console.error(error&&error.stack||error);process.exitCode=1;}}
module.exports={verifyContract:verifyContract,computeRows:computeRows,reactionEvents:reactionEvents,structuralEvents:structuralEvents,validateEventProvenance:validateEventProvenance,expectedLifecycle:expectedLifecycle,expectedEq:expectedEq};
