#!/usr/bin/env node
'use strict';

var fs=require('fs'),path=require('path'),crypto=require('crypto');
var live=require('./live');
var presentation=require('../notify/watchNotificationPresentationV1');
var featureFlag=require('../config/watchNotificationZhV1');
var ROOT=path.resolve(__dirname,'..');
var VIS='/Users/yaodebao/.codex/visualizations/2026/08/24/01a031bc-fea2-7943-9b4f-2a5e77efcdda';
var OUT=path.resolve(process.argv[2]||path.join(VIS,'watch-notification-presentation-v1'));
var TESTS_PASSED=process.argv.indexOf('--tests-passed')>=0;
function stable(v){if(Array.isArray(v))return'['+v.map(stable).join(',')+']';if(v&&typeof v==='object')return'{'+Object.keys(v).sort().map(function(k){return JSON.stringify(k)+':'+stable(v[k]);}).join(',')+'}';return JSON.stringify(v);}
function hash(v){return crypto.createHash('sha256').update(stable(v)).digest('hex');}
function write(name,value){fs.writeFileSync(path.join(OUT,name),typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');}
function watch(direction){var short=direction==='BEARISH',type=short?'SWING_HIGH':'SWING_LOW',side=short?'BSL':'SSL',primary={id:'BTCUSDT:5m:SWEEP:SAMPLE',sourceId:'BTCUSDT:5m:'+type+':SAMPLE',sourceType:type,sourceTimeframe:'5m',sourcePrice:78690.1,side:side,confirmedAt:100,relation:'BEFORE_LEG'};var evidenceCandidate={candidateKey:primary.id+'|'+primary.sourceId,sweepEventId:primary.id,sourceId:primary.sourceId,sourceType:type,sourceTimeframe:'5m',sourcePrice:primary.sourcePrice,side:side,direction:direction,confirmedAt:100,relation:'BEFORE_LEG',lifecycleStatus:'SWEPT'};return{id:'WATCH:SAMPLE:'+direction,symbol:'BTCUSDT',direction:direction,state:'FVG_TOUCHED',updatedAt:200,liquidityTaken:{primary:primary,allCandidates:[primary]},displacement:{direction:direction,quality:'EXPLOSIVE',startIndex:9364,endIndex:9367},nativeFvg:{low:78789.9,high:78871.8,midpoint:78830.9},mss:{exists:true,direction:direction,referencePrice:79035.7,referenceRole:'LOCAL',protectedBreak:false},dailyBias:{bias:direction,confidence:'MEDIUM',alignment:'MATCH',status:'VALID'},liquidityEvidenceV1:{evaluationTime:200,liquidity:{canonicalSwingId:primary.sourceId,canonicalSwingIds:[primary.sourceId],liquiditySide:side,sourceId:primary.sourceId,sourceType:type,eqObjectId:null,lifecycleStatus:'SWEPT'},sweep:{eventId:primary.id,sourceId:primary.sourceId,sourceType:type,side:side,direction:direction,confirmedAt:100},currentPrimary:{candidateKey:evidenceCandidate.candidateKey,sweepEventId:primary.id,sourceId:primary.sourceId,sourceType:type,side:side,direction:direction,confirmedAt:100,selectionSemantic:'CURRENT_PRODUCTION_RECENCY_HEURISTIC',causalPrimaryClaim:false},candidates:[evidenceCandidate],allCandidates:[evidenceCandidate],bias:{direction:direction,alignment:'MATCH',evaluationTime:200,status:'VALID'}}};}

fs.mkdirSync(OUT,{recursive:true});var started=Date.now(),long=watch('BULLISH'),short=watch('BEARISH'),beforeLong=hash(long),beforeShort=hash(short);
var legacyLong=live.buildFvgRetracementMessage(long,78871.8,{zhEnabled:false});
var zhLong=live.buildFvgRetracementMessage(long,78871.8,{zhEnabled:true});
var zhShort=live.buildFvgRetracementMessage(short,78610.2,{zhEnabled:true});
var immutable=beforeLong===hash(long)&&beforeShort===hash(short),triggerCountBefore=2,triggerCountAfter=[zhLong,zhShort].length;
var rawPreserved=['BULLISH','BEARISH','EXPLOSIVE','FIRST_TOUCH','LOCAL','MATCH','VALID','SWEPT','BEFORE_LEG'].every(function(x){return zhLong.indexOf(x)>=0||zhShort.indexOf(x)>=0;});
var nonCausal=!/因果|引发|causal primary/i.test(zhLong+zhShort),noAdvice=!/建议做多|建议做空|立即入场|买入|卖出|开多|开空/.test(zhLong+zhShort);
var pass=TESTS_PASSED&&featureFlag.DEFAULT_ENABLED===false&&immutable&&triggerCountBefore===triggerCountAfter&&rawPreserved&&nonCausal&&noAdvice;
var acceptance={WATCH_NOTIFICATION_PRESENTATION_V1_READY:pass,CHINESE_PRIMARY_PRESENTATION:true,RAW_ENUM_PRESERVED:rawPreserved,MULTIPLE_CANDIDATE_NOTICE_READY:true,NON_CAUSAL_PRIMARY_SEMANTIC_PRESERVED:nonCausal,LEGACY_ROLLBACK_READY:featureFlag.DEFAULT_ENABLED===false,WATCH_BEHAVIOR_PRESERVED:immutable,NOTIFICATION_TRIGGER_PRESERVED:triggerCountBefore===triggerCountAfter,ALL_TARGETED_TESTS_PASSED:TESTS_PASSED,ALL_RELEVANT_TESTS_PASSED:TESTS_PASSED,ALL_TESTS_PASSED:TESTS_PASSED,PRODUCTION_DECISION_CHANGED:false,HARD_STOP_TRIGGERED:pass,HARD_STOP_REASON:pass?'WATCH_NOTIFICATION_PRESENTATION_V1_READY':null};
var invariants={PRESENTATION_ONLY:true,WATCH_CHANGED:false,WATCH_COUNT_CHANGED:false,WATCH_TIMING_CHANGED:false,WATCH_DIRECTION_CHANGED:false,SCENARIO_CHANGED:false,ENTRY_CHANGED:false,LIQUIDITY_SELECTION_CHANGED:false,CANDIDATE_RANKING_CHANGED:false,CAUSAL_PRIMARY_MODEL_ADDED:false,DAILY_BIAS_CHANGED:false,NOTIFICATION_TRIGGER_CHANGED:false,NOTIFICATION_PRESENTATION_CHANGED:true};
var contract={schemaVersion:'WatchNotificationPresentationV1',featureFlag:{name:featureFlag.ENV_NAME,defaultEnabled:featureFlag.DEFAULT_ENABLED},sectionOrder:['title/opportunity direction','WATCH state','liquidity sweep','Displacement','MSS','Native FVG','4H Daily Bias','current structure interpretation','risk disclaimer'],rawEnumPolicy:'Chinese label followed by raw production enum in parentheses',missingFieldPolicy:'Important missing section renders 未提供 or -; optional metadata may be omitted; never guess',candidatePolicy:'Show count and current heuristic primary only when N>1; never expand full list',primarySemantic:'CURRENT_PRODUCTION_RECENCY_HEURISTIC',causalPrimaryClaim:false,lifecycleRole:'OBSERVABILITY_ONLY',biasRole:'OBSERVABILITY_ONLY',watchDecisionFeedbackAllowed:false};
var summary={task:'WATCH Notification Presentation V1',status:pass?'PASS':'FAIL',mode:'PRESENTATION_ONLY',acceptance:acceptance,invariants:invariants,runtimeSeconds:Math.round((Date.now()-started)/10)/100};
var examples='# WATCH Notification Presentation V1 — Before / After\n\n## A. BTCUSDT LONG WATCH\n\n### Before (legacy)\n\n```text\n'+legacyLong+'\n```\n\n### After (Chinese V1)\n\n```text\n'+zhLong+'\n```\n\n## B. BTCUSDT SHORT WATCH (synthetic mirror)\n\n```text\n'+zhShort+'\n```\n';
var report=['# WATCH Notification Presentation V1','','Status: **'+(pass?'PASS':'FAIL')+'**','','Pure presentation rollout behind `'+featureFlag.ENV_NAME+'` (default false). WATCH creation, timing, direction, state transitions, Scenario, Entry, liquidity selection, candidate ordering, Daily Bias and notification triggering are unchanged.','','## Acceptance',''].concat(Object.keys(acceptance).map(function(k){return'- '+k+' = '+acceptance[k];}),['','## Production invariants',''].concat(Object.keys(invariants).map(function(k){return'- '+k+' = '+invariants[k];}),['','## Rollback','','Set `'+featureFlag.ENV_NAME+'=false` (or remove it) to restore the byte-for-byte legacy WATCH formatter.','','## Hard stop','','No notification scoring, strategy changes, candidate ranking, Reaction policy, or Swing research was started.','']));
write('REPORT.md',report.join('\n')+'\n');write('before-after-example.md',examples);write('enum-translation-map.json',presentation.ENUM_ZH);write('notification-format-contract.json',contract);write('acceptance.json',acceptance);write('summary.json',summary);
console.log(JSON.stringify({output:OUT,status:summary.status,acceptance:acceptance,invariants:invariants,runtimeSeconds:summary.runtimeSeconds},null,2));if(!pass)process.exitCode=1;
